import logging
import re
import threading

from django.conf import settings
from django.core.exceptions import ValidationError
from django.core.mail import EmailMessage, get_connection
from django.core.validators import validate_email
from django.utils import timezone

from crm.models import Event


logger = logging.getLogger(__name__)


def parse_external_attendee_emails(value):
    raw_parts = re.split(r"[,;\n\r]+", value or "")
    emails = []
    seen = set()
    for part in raw_parts:
        email = (part or "").strip()
        if not email:
            continue
        try:
            validate_email(email)
        except ValidationError:
            logger.warning("Calendar invite skipped invalid external attendee", extra={"email": email})
            continue
        key = email.lower()
        if key not in seen:
            seen.add(key)
            emails.append(email)
    return emails


def _user_display_name(user):
    if not user:
        return ""
    full_name = (user.get_full_name() or "").strip()
    return full_name or getattr(user, "username", "") or str(user)


def _datetime_signature(value):
    if not value:
        return ""
    return timezone.localtime(value).replace(second=0, microsecond=0).isoformat()


def calendar_event_signature(event):
    attendee_ids = []
    external_emails = []
    if event.pk:
        attendee_ids = list(event.attendees.order_by("pk").values_list("pk", flat=True))
        external_emails = parse_external_attendee_emails(event.external_attendees)

    parts = [
        event.title or "",
        _datetime_signature(event.start_datetime),
        _datetime_signature(event.end_datetime),
        event.location or "",
        event.meeting_link or "",
        event.note or "",
        event.assigned_to_email or "",
        ",".join(str(pk) for pk in attendee_ids),
        ",".join(email.lower() for email in external_emails),
    ]
    return "|".join(parts)


def calendar_invite_recipients(event, *, include_creator=False):
    recipients = []
    seen = set()

    for user in event.attendees.all():
        email = (getattr(user, "email", "") or "").strip()
        if not email:
            continue
        key = email.lower()
        if key not in seen:
            seen.add(key)
            recipients.append(email)

    assigned_email = (event.assigned_to_email or "").strip()
    if assigned_email:
        try:
            validate_email(assigned_email)
        except ValidationError:
            logger.warning("Calendar invite skipped invalid assigned email", extra={"event_id": event.pk})
        else:
            key = assigned_email.lower()
            if key not in seen:
                seen.add(key)
                recipients.append(assigned_email)

    for email in parse_external_attendee_emails(event.external_attendees):
        key = email.lower()
        if key not in seen:
            seen.add(key)
            recipients.append(email)

    if include_creator and event.created_by and getattr(event.created_by, "email", ""):
        creator_email = event.created_by.email.strip()
        key = creator_email.lower()
        if creator_email and key not in seen:
            seen.add(key)
            recipients.append(creator_email)

    return recipients


def build_calendar_invite_email(event, *, action="created"):
    recipients = calendar_invite_recipients(event)
    if not recipients:
        return None

    local_start = timezone.localtime(event.start_datetime) if event.start_datetime else None
    local_end = timezone.localtime(event.end_datetime) if event.end_datetime else None
    organizer = _user_display_name(event.created_by) or "Iconic CRM"
    action_label = "Updated meeting" if action == "updated" else "Meeting invite"
    subject = f"{action_label}: {event.title}"

    lines = [
        f"{action_label}: {event.title}",
        "",
        f"Organizer: {organizer}",
        f"Date: {local_start.strftime('%Y-%m-%d') if local_start else 'Not set'}",
        f"Start: {local_start.strftime('%I:%M %p') if local_start else 'Not set'}",
        f"End: {local_end.strftime('%I:%M %p') if local_end else 'Not set'}",
    ]
    if event.location:
        lines.append(f"Location: {event.location}")
    if event.meeting_link:
        lines.append(f"Meeting link: {event.meeting_link}")
    if event.note:
        lines.extend(["", "Description:", event.note])
    lines.extend(["", "This invite was generated by Iconic CRM."])

    return {
        "subject": subject,
        "body": "\n".join(lines),
        "recipients": recipients,
        "from_email": getattr(settings, "DEFAULT_FROM_EMAIL", "info@iconicapparelhouse.com"),
    }


def send_calendar_invite_email(event_id, *, action="created"):
    event = (
        Event.objects.select_related("created_by")
        .prefetch_related("attendees")
        .filter(pk=event_id)
        .first()
    )
    if not event:
        logger.warning("Calendar invite skipped missing event", extra={"event_id": event_id})
        return False

    payload = build_calendar_invite_email(event, action=action)
    if not payload:
        logger.info("Calendar invite skipped: no recipients", extra={"event_id": event_id, "action": action})
        return False

    try:
        timeout = int(getattr(settings, "CALENDAR_EMAIL_TIMEOUT", getattr(settings, "EMAIL_TIMEOUT", 8)) or 8)
    except (TypeError, ValueError):
        timeout = 8

    try:
        connection = get_connection(timeout=timeout)
        message = EmailMessage(
            payload["subject"],
            payload["body"],
            payload["from_email"],
            payload["recipients"],
            connection=connection,
        )
        sent_count = message.send(fail_silently=False)
    except Exception:
        logger.exception("Calendar invite email failed", extra={"event_id": event_id, "action": action})
        return False

    if sent_count:
        logger.info(
            "Calendar invite email sent",
            extra={"event_id": event_id, "action": action, "recipient_count": len(payload["recipients"])},
        )
        return True

    logger.warning("Calendar invite email not sent", extra={"event_id": event_id, "action": action})
    return False


def queue_calendar_invite_email(event_id, *, action="created"):
    if not getattr(settings, "CALENDAR_INVITES_ASYNC", True):
        return send_calendar_invite_email(event_id, action=action)

    worker = threading.Thread(
        target=send_calendar_invite_email,
        kwargs={"event_id": event_id, "action": action},
        daemon=True,
    )
    worker.start()
    return True
