# Generated by Django 5.2.8 on 2026-02-01 23:32

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InsightItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('seo', 'SEO'), ('social', 'Social'), ('outreach', 'Outreach')], default='seo', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('reason', models.TextField(blank=True, default='')),
                ('recommended_action', models.TextField(blank=True, default='')),
                ('priority_score', models.IntegerField(default=50)),
                ('status', models.CharField(choices=[('open', 'Open'), ('done', 'Done'), ('snoozed', 'Snoozed')], default='open', max_length=20)),
                ('related_object_type', models.CharField(blank=True, default='', max_length=60)),
                ('related_object_id', models.CharField(blank=True, default='', max_length=60)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-priority_score', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='SeoProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('gsc_site_url', models.CharField(blank=True, default='', max_length=255)),
                ('ga4_property_id', models.CharField(blank=True, default='', max_length=60)),
                ('is_active', models.BooleanField(default=True)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('last_sync_status', models.CharField(blank=True, default='', max_length=30)),
                ('last_sync_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('goal', models.CharField(choices=[('leads', 'Leads'), ('meetings', 'Meetings'), ('quotes', 'Quotes'), ('samples', 'Samples')], default='leads', max_length=20)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('budget', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marketing_campaigns', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, default='', max_length=50)),
                ('first_name', models.CharField(blank=True, default='', max_length=100)),
                ('last_name', models.CharField(blank=True, default='', max_length=100)),
                ('company', models.CharField(blank=True, default='', max_length=200)),
                ('website', models.CharField(blank=True, default='', max_length=255)),
                ('city', models.CharField(blank=True, default='', max_length=120)),
                ('state', models.CharField(blank=True, default='', max_length=120)),
                ('country', models.CharField(blank=True, default='', max_length=120)),
                ('industry', models.CharField(blank=True, default='', max_length=120)),
                ('job_title', models.CharField(blank=True, default='', max_length=120)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('source', models.CharField(choices=[('upload', 'Upload'), ('website', 'Website'), ('referral', 'Referral'), ('manual', 'Manual')], default='upload', max_length=20)),
                ('consent_status', models.CharField(choices=[('unknown', 'Unknown'), ('opted_in', 'Opted In'), ('opted_out', 'Opted Out')], default='unknown', max_length=20)),
                ('do_not_contact', models.BooleanField(default=False)),
                ('unsubscribe_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('last_contacted_at', models.DateTimeField(blank=True, null=True)),
                ('last_reply_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['email'], name='marketing_c_email_d9f376_idx'), models.Index(fields=['company'], name='marketing_c_company_7ae5bb_idx'), models.Index(fields=['country'], name='marketing_c_country_ebfba8_idx')],
            },
        ),
        migrations.CreateModel(
            name='ContactList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_lists', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OutreachCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('channel', models.CharField(choices=[('email', 'Email'), ('phone', 'Phone')], default='email', max_length=10)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed')], default='draft', max_length=20)),
                ('sending_account', models.CharField(blank=True, default='', max_length=200)),
                ('daily_limit', models.PositiveIntegerField(default=30)),
                ('schedule_window_json', models.JSONField(blank=True, default=dict)),
                ('followup_rules_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contact_list', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='marketing.contactlist')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outreach_campaigns', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='CallTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority_score', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('called', 'Called'), ('no_answer', 'No answer'), ('callback', 'Call back'), ('not_interested', 'Not interested'), ('interested', 'Interested'), ('meeting_booked', 'Meeting booked')], default='queued', max_length=20)),
                ('next_call_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_tasks', to='marketing.contact')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_tasks', to='marketing.outreachcampaign')),
            ],
        ),
        migrations.CreateModel(
            name='OutreachMessageTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_template', models.CharField(max_length=255)),
                ('body_template', models.TextField()),
                ('variables_json', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='marketing.outreachcampaign')),
            ],
        ),
        migrations.CreateModel(
            name='SocialAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('facebook', 'Facebook'), ('instagram', 'Instagram'), ('tiktok', 'TikTok'), ('youtube', 'YouTube')], max_length=20)),
                ('external_account_id', models.CharField(blank=True, default='', max_length=120)),
                ('display_name', models.CharField(blank=True, default='', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('last_sync_status', models.CharField(blank=True, default='', max_length=30)),
                ('last_sync_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('platform', 'display_name'),
                'indexes': [models.Index(fields=['platform', 'external_account_id'], name='marketing_s_platfor_6e8ae1_idx')],
            },
        ),
        migrations.CreateModel(
            name='OAuthCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('gsc', 'Google Search Console'), ('ga4', 'Google Analytics 4'), ('meta', 'Meta'), ('tiktok', 'TikTok'), ('youtube', 'YouTube')], max_length=20)),
                ('encrypted_access_token', models.TextField(blank=True, default='')),
                ('encrypted_refresh_token', models.TextField(blank=True, default='')),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('scopes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('social_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credentials', to='marketing.socialaccount')),
            ],
        ),
        migrations.CreateModel(
            name='SocialContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('facebook', 'Facebook'), ('instagram', 'Instagram'), ('tiktok', 'TikTok'), ('youtube', 'YouTube')], max_length=20)),
                ('external_content_id', models.CharField(max_length=120)),
                ('content_type', models.CharField(choices=[('post', 'Post'), ('reel', 'Reel'), ('short', 'Short'), ('video', 'Video'), ('long_video', 'Long Video')], default='post', max_length=20)),
                ('title', models.CharField(blank=True, default='', max_length=300)),
                ('permalink', models.URLField(blank=True, default='')),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='marketing.socialaccount')),
            ],
            options={
                'ordering': ('-published_at', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='SocialMetricDaily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('impressions', models.PositiveIntegerField(default=0)),
                ('reach', models.PositiveIntegerField(default=0)),
                ('views', models.PositiveIntegerField(default=0)),
                ('likes', models.PositiveIntegerField(default=0)),
                ('comments', models.PositiveIntegerField(default=0)),
                ('shares', models.PositiveIntegerField(default=0)),
                ('saves', models.PositiveIntegerField(default=0)),
                ('clicks', models.PositiveIntegerField(default=0)),
                ('watch_time_seconds', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_metrics', to='marketing.socialcontent')),
            ],
            options={
                'ordering': ('-date',),
            },
        ),
        migrations.CreateModel(
            name='TrackedLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('base_url', models.URLField()),
                ('utm_source', models.CharField(blank=True, default='', max_length=120)),
                ('utm_medium', models.CharField(blank=True, default='', max_length=120)),
                ('utm_campaign', models.CharField(blank=True, default='', max_length=120)),
                ('utm_content', models.CharField(blank=True, default='', max_length=120)),
                ('utm_term', models.CharField(blank=True, default='', max_length=120)),
                ('final_url', models.URLField(blank=True, default='')),
                ('qr_png', models.ImageField(blank=True, null=True, upload_to='marketing/qr/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='marketing.campaign')),
            ],
        ),
        migrations.CreateModel(
            name='UnsubscribeEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(default='email', max_length=20)),
                ('event_at', models.DateTimeField(auto_now_add=True)),
                ('reason', models.CharField(blank=True, default='', max_length=255)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unsubscribe_events', to='marketing.contact')),
            ],
        ),
        migrations.CreateModel(
            name='ContactListMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='marketing.contact')),
                ('contact_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='marketing.contactlist')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('contact_list', 'contact'), name='contact_list_member_unique')],
            },
        ),
        migrations.CreateModel(
            name='OutreachSendLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('send_type', models.CharField(choices=[('initial', 'Initial'), ('followup1', 'Follow up 1'), ('followup2', 'Follow up 2')], default='initial', max_length=20)),
                ('queued_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('sent', 'Sent'), ('failed', 'Failed'), ('bounced', 'Bounced'), ('unsubscribed', 'Unsubscribed'), ('replied', 'Replied'), ('stopped', 'Stopped')], default='queued', max_length=20)),
                ('provider_message_id', models.CharField(blank=True, default='', max_length=200)),
                ('error_text', models.TextField(blank=True, default='')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='send_logs', to='marketing.outreachcampaign')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='send_logs', to='marketing.contact')),
            ],
            options={
                'indexes': [models.Index(fields=['status', 'sent_at'], name='marketing_o_status_6c4847_idx')],
                'constraints': [models.UniqueConstraint(fields=('campaign', 'contact', 'send_type'), name='outreach_send_unique')],
            },
        ),
        migrations.CreateModel(
            name='SeoPageDaily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('page', models.CharField(db_index=True, max_length=500)),
                ('clicks', models.PositiveIntegerField(default=0)),
                ('impressions', models.PositiveIntegerField(default=0)),
                ('ctr', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=6)),
                ('position', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_days', to='marketing.seoproperty')),
            ],
            options={
                'ordering': ('-date', 'page'),
                'constraints': [models.UniqueConstraint(fields=('property', 'date', 'page'), name='seo_page_daily_unique')],
            },
        ),
        migrations.CreateModel(
            name='SeoQueryDaily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('query', models.CharField(db_index=True, max_length=300)),
                ('page', models.CharField(db_index=True, max_length=500)),
                ('country', models.CharField(blank=True, default='', max_length=12)),
                ('device', models.CharField(blank=True, default='', max_length=20)),
                ('clicks', models.PositiveIntegerField(default=0)),
                ('impressions', models.PositiveIntegerField(default=0)),
                ('ctr', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=6)),
                ('position', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='query_days', to='marketing.seoproperty')),
            ],
            options={
                'ordering': ('-date', 'query'),
                'constraints': [models.UniqueConstraint(fields=('property', 'date', 'query', 'page', 'country', 'device'), name='seo_query_daily_unique')],
            },
        ),
        migrations.CreateModel(
            name='SocialAudienceDaily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('country_json', models.JSONField(blank=True, default=dict)),
                ('gender_age_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audience_days', to='marketing.socialaccount')),
            ],
            options={
                'ordering': ('-date',),
                'constraints': [models.UniqueConstraint(fields=('account', 'date'), name='social_audience_daily_unique')],
            },
        ),
        migrations.AddConstraint(
            model_name='socialcontent',
            constraint=models.UniqueConstraint(fields=('platform', 'external_content_id'), name='social_content_unique'),
        ),
        migrations.AddConstraint(
            model_name='socialmetricdaily',
            constraint=models.UniqueConstraint(fields=('content', 'date'), name='social_metric_daily_unique'),
        ),
        migrations.AddConstraint(
            model_name='trackedlink',
            constraint=models.UniqueConstraint(fields=('campaign', 'name'), name='tracked_link_unique'),
        ),
    ]
