# Generated by Django 5.2.8 on 2026-02-01 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='outreachcampaign',
            name='hourly_limit',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
