# Generated by Django 5.2.8 on 2026-02-08 10:13

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0002_outreachcampaign_hourly_limit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='insightitem',
            name='note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='insightitem',
            name='platform',
            field=models.CharField(blank=True, choices=[('facebook', 'Facebook'), ('meta_business', 'Meta Business Suite'), ('instagram', 'Instagram'), ('linkedin', 'LinkedIn'), ('tiktok', 'TikTok'), ('youtube', 'YouTube'), ('google_business', 'Google Business Profile')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='oauthcredential',
            name='platform_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='platform_credentials', to='marketing.socialaccount'),
        ),
        migrations.AddField(
            model_name='socialaccount',
            name='last_successful_sync',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='socialaccount',
            name='timezone',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='socialaccount',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='socialaudiencedaily',
            name='city_json',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='socialaudiencedaily',
            name='language_json',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='socialcontent',
            name='message_text',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='socialcontent',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='socialmetricdaily',
            name='avg_view_duration_seconds',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='socialmetricdaily',
            name='follows',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='socialmetricdaily',
            name='profile_visits',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='insightitem',
            name='source',
            field=models.CharField(choices=[('seo', 'SEO'), ('content', 'Content'), ('audience', 'Audience'), ('ads', 'Ads'), ('outreach', 'Outreach'), ('social', 'Social')], default='seo', max_length=20),
        ),
        migrations.AlterField(
            model_name='oauthcredential',
            name='platform',
            field=models.CharField(choices=[('gsc', 'Google Search Console'), ('ga4', 'Google Analytics 4'), ('meta', 'Meta'), ('facebook', 'Facebook'), ('meta_business', 'Meta Business Suite'), ('linkedin', 'LinkedIn'), ('tiktok', 'TikTok'), ('youtube', 'YouTube'), ('google_business', 'Google Business Profile')], max_length=20),
        ),
        migrations.AlterField(
            model_name='socialaccount',
            name='platform',
            field=models.CharField(choices=[('facebook', 'Facebook'), ('meta_business', 'Meta Business Suite'), ('instagram', 'Instagram'), ('linkedin', 'LinkedIn'), ('tiktok', 'TikTok'), ('youtube', 'YouTube'), ('google_business', 'Google Business Profile')], max_length=20),
        ),
        migrations.AlterField(
            model_name='socialcontent',
            name='content_type',
            field=models.CharField(choices=[('post', 'Post'), ('reel', 'Reel'), ('short', 'Short'), ('video', 'Video'), ('long_video', 'Long Video'), ('story', 'Story'), ('ad', 'Ad')], default='post', max_length=20),
        ),
        migrations.AlterField(
            model_name='socialcontent',
            name='platform',
            field=models.CharField(choices=[('facebook', 'Facebook'), ('meta_business', 'Meta Business Suite'), ('instagram', 'Instagram'), ('linkedin', 'LinkedIn'), ('tiktok', 'TikTok'), ('youtube', 'YouTube'), ('google_business', 'Google Business Profile')], max_length=20),
        ),
        migrations.CreateModel(
            name='AdAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_ad_account_id', models.CharField(max_length=120)),
                ('currency', models.CharField(blank=True, default='', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('platform_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ad_accounts', to='marketing.socialaccount')),
            ],
        ),
        migrations.CreateModel(
            name='AdCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_campaign_id', models.CharField(max_length=120)),
                ('name', models.CharField(blank=True, default='', max_length=200)),
                ('status', models.CharField(blank=True, default='', max_length=30)),
                ('objective', models.CharField(blank=True, default='', max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ad_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='marketing.adaccount')),
            ],
        ),
        migrations.CreateModel(
            name='AdMetricDaily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('spend', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('impressions', models.PositiveIntegerField(default=0)),
                ('clicks', models.PositiveIntegerField(default=0)),
                ('cpc', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=12)),
                ('cpm', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=12)),
                ('conversions', models.PositiveIntegerField(default=0)),
                ('cost_per_conversion', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ad_campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_metrics', to='marketing.adcampaign')),
            ],
            options={
                'ordering': ('-date',),
            },
        ),
        migrations.CreateModel(
            name='BestPracticeLibrary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('facebook', 'Facebook'), ('meta_business', 'Meta Business Suite'), ('instagram', 'Instagram'), ('linkedin', 'LinkedIn'), ('tiktok', 'TikTok'), ('youtube', 'YouTube'), ('google_business', 'Google Business Profile')], max_length=20)),
                ('category', models.CharField(choices=[('hooks', 'Hooks'), ('captions', 'Captions'), ('hashtags', 'Hashtags'), ('posting_times', 'Posting times'), ('creative', 'Creative checklist'), ('offers', 'Offers'), ('dos_donts', "Do and don't")], default='hooks', max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField(blank=True, default='')),
                ('examples_json', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marketing_best_practices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='AccountMetricDaily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('followers_total', models.PositiveIntegerField(default=0)),
                ('followers_change', models.IntegerField(default=0)),
                ('impressions', models.PositiveIntegerField(default=0)),
                ('reach', models.PositiveIntegerField(default=0)),
                ('views', models.PositiveIntegerField(default=0)),
                ('clicks', models.PositiveIntegerField(default=0)),
                ('engagement_total', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_days', to='marketing.socialaccount')),
            ],
            options={
                'ordering': ('-date',),
                'constraints': [models.UniqueConstraint(fields=('account', 'date'), name='account_metric_daily_unique')],
            },
        ),
        migrations.AddConstraint(
            model_name='adaccount',
            constraint=models.UniqueConstraint(fields=('platform_account', 'external_ad_account_id'), name='ad_account_unique'),
        ),
        migrations.AddConstraint(
            model_name='adcampaign',
            constraint=models.UniqueConstraint(fields=('ad_account', 'external_campaign_id'), name='ad_campaign_unique'),
        ),
        migrations.AddConstraint(
            model_name='admetricdaily',
            constraint=models.UniqueConstraint(fields=('ad_campaign', 'date'), name='ad_metric_daily_unique'),
        ),
    ]
