# Generated by Django 5.2.8 on 2026-02-08 21:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0003_insightitem_note_insightitem_platform_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='oauthcredential',
            name='platform',
            field=models.CharField(choices=[('gsc', 'Google Search Console'), ('ga4', 'Google Analytics 4'), ('meta', 'Meta'), ('facebook', 'Facebook'), ('meta_business', 'Meta Business Suite'), ('instagram', 'Instagram'), ('linkedin', 'LinkedIn'), ('tiktok', 'TikTok'), ('youtube', 'YouTube'), ('google_business', 'Google Business Profile')], max_length=20),
        ),
        migrations.CreateModel(
            name='OAuthConnectionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('gsc', 'Google Search Console'), ('ga4', 'Google Analytics 4'), ('meta', 'Meta'), ('facebook', 'Facebook'), ('meta_business', 'Meta Business Suite'), ('instagram', 'Instagram'), ('linkedin', 'LinkedIn'), ('tiktok', 'TikTok'), ('youtube', 'YouTube'), ('google_business', 'Google Business Profile')], max_length=20)),
                ('state', models.CharField(max_length=120, unique=True)),
                ('code', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('initiated', 'Initiated'), ('received', 'Received'), ('completed', 'Completed'), ('error', 'Error')], default='initiated', max_length=20)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['platform', 'status'], name='marketing_o_platfor_496c2c_idx')],
            },
        ),
    ]
