# Generated by Django 6.0 on 2026-04-24 17:50

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0004_alter_oauthcredential_platform_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketingCompetitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('website', models.URLField(blank=True, default='')),
                ('industry', models.CharField(blank=True, default='', max_length=120)),
                ('notes', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='MarketingCompetitorAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('instagram', 'Instagram'), ('facebook', 'Facebook'), ('linkedin', 'LinkedIn'), ('tiktok', 'TikTok'), ('youtube', 'YouTube'), ('google_business', 'Google Business')], max_length=20)),
                ('profile_url', models.URLField(blank=True, default='')),
                ('handle', models.CharField(blank=True, default='', max_length=120)),
                ('followers_count', models.PositiveIntegerField(default=0)),
                ('following_count', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('last_checked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('competitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='marketing.marketingcompetitor')),
            ],
            options={
                'ordering': ('competitor__name', 'platform', 'handle'),
            },
        ),
        migrations.CreateModel(
            name='MarketingCompetitorInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('reason', models.TextField(blank=True, default='')),
                ('recommended_action', models.TextField(blank=True, default='')),
                ('priority_score', models.IntegerField(default=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('competitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insights', to='marketing.marketingcompetitor')),
            ],
            options={
                'ordering': ('-priority_score', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='MarketingCompetitorPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_url', models.URLField(blank=True, default='')),
                ('caption_text', models.TextField(blank=True, default='')),
                ('content_type', models.CharField(choices=[('post', 'Post'), ('reel', 'Reel'), ('short', 'Short'), ('video', 'Video'), ('long_video', 'Long Video'), ('story', 'Story'), ('ad', 'Ad')], default='post', max_length=20)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('likes', models.PositiveIntegerField(default=0)),
                ('comments', models.PositiveIntegerField(default=0)),
                ('shares', models.PositiveIntegerField(default=0)),
                ('views', models.PositiveIntegerField(default=0)),
                ('saves', models.PositiveIntegerField(default=0)),
                ('engagement_score', models.PositiveIntegerField(default=0)),
                ('engagement_rate', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=8)),
                ('detected_theme', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('competitor_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='marketing.marketingcompetitoraccount')),
            ],
            options={
                'ordering': ('-published_at', '-created_at'),
            },
        ),
        migrations.AddConstraint(
            model_name='marketingcompetitoraccount',
            constraint=models.UniqueConstraint(fields=('competitor', 'platform', 'handle'), name='marketing_competitor_account_unique'),
        ),
    ]
