# Generated by Django 6.0 on 2026-04-24 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0005_marketingcompetitor_marketingcompetitoraccount_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='oauthcredential',
            options={'ordering': ('platform', 'account_name', 'account_id', '-updated_at')},
        ),
        migrations.AddField(
            model_name='oauthcredential',
            name='account_id',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='oauthcredential',
            name='account_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='oauthcredential',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='oauthcredential',
            name='last_error',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='oauthcredential',
            name='last_sync_status',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='oauthcredential',
            name='last_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='oauthcredential',
            index=models.Index(fields=['platform', 'is_active'], name='marketing_o_platfor_f0dc6f_idx'),
        ),
        migrations.AddIndex(
            model_name='oauthcredential',
            index=models.Index(fields=['platform', 'account_id'], name='marketing_o_platfor_dca47e_idx'),
        ),
    ]
