# Generated by Django 6.0 on 2026-05-10 18:12

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0006_alter_oauthcredential_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsitePageDaily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('page_path', models.CharField(db_index=True, max_length=500)),
                ('page_title', models.CharField(blank=True, default='', max_length=300)),
                ('visitors', models.PositiveIntegerField(default=0)),
                ('sessions', models.PositiveIntegerField(default=0)),
                ('page_views', models.PositiveIntegerField(default=0)),
                ('entrances', models.PositiveIntegerField(default=0)),
                ('exits', models.PositiveIntegerField(default=0)),
                ('conversions', models.PositiveIntegerField(default=0)),
                ('avg_engagement_seconds', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='website_page_days', to='marketing.seoproperty')),
            ],
            options={
                'ordering': ('-date', 'page_path'),
                'indexes': [models.Index(fields=['property', 'date'], name='marketing_w_propert_ac972e_idx'), models.Index(fields=['page_path'], name='marketing_w_page_pa_d8388e_idx')],
                'constraints': [models.UniqueConstraint(fields=('property', 'date', 'page_path'), name='website_page_daily_unique')],
            },
        ),
        migrations.CreateModel(
            name='WebsiteTrafficDaily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('channel', models.CharField(blank=True, db_index=True, default='', max_length=80)),
                ('source', models.CharField(blank=True, default='', max_length=120)),
                ('medium', models.CharField(blank=True, default='', max_length=120)),
                ('campaign', models.CharField(blank=True, default='', max_length=160)),
                ('visitors', models.PositiveIntegerField(default=0)),
                ('sessions', models.PositiveIntegerField(default=0)),
                ('engaged_sessions', models.PositiveIntegerField(default=0)),
                ('page_views', models.PositiveIntegerField(default=0)),
                ('events', models.PositiveIntegerField(default=0)),
                ('conversions', models.PositiveIntegerField(default=0)),
                ('engagement_rate', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=6)),
                ('avg_engagement_seconds', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traffic_days', to='marketing.seoproperty')),
            ],
            options={
                'ordering': ('-date', 'channel', 'source'),
                'indexes': [models.Index(fields=['property', 'date'], name='marketing_w_propert_0c8569_idx'), models.Index(fields=['channel', 'source'], name='marketing_w_channel_ff89db_idx')],
                'constraints': [models.UniqueConstraint(fields=('property', 'date', 'channel', 'source', 'medium', 'campaign'), name='website_traffic_daily_unique')],
            },
        ),
    ]
