# Generated by Django 6.0 on 2026-07-05 03:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


KEYWORD_SEEDS = [
    ("custom clothing manufacturer", "CA", "private_label_apparel"),
    ("clothing manufacturer Canada", "CA", "private_label_apparel"),
    ("apparel manufacturer Canada", "CA", "private_label_apparel"),
    ("private label clothing manufacturer", "CA", "private_label_apparel"),
    ("low MOQ clothing manufacturer", "CA", "low_moq_manufacturing"),
    ("hoodie manufacturer", "CA", "hoodies"),
    ("streetwear manufacturer", "CA", "streetwear"),
    ("activewear manufacturer", "CA", "activewear"),
    ("Bangladesh clothing factory", "BD", "bangladesh_garment_manufacturing"),
    ("garment manufacturer Bangladesh", "BD", "bangladesh_garment_manufacturing"),
    ("ethical clothing manufacturer", "CA", "private_label_apparel"),
    ("custom t shirt manufacturer", "CA", "t_shirts"),
    ("startup clothing brand manufacturer", "CA", "low_moq_manufacturing"),
]

CONTENT_SEEDS = [
    ("How to start a clothing brand with low MOQ", "blog", "website", "low MOQ clothing manufacturer"),
    ("Hoodie fabric guide for startup brands", "blog", "website", "hoodie manufacturer"),
    ("Bangladesh vs China garment manufacturing", "blog", "linkedin", "garment manufacturer Bangladesh"),
    ("How sampling works before bulk production", "video", "youtube", "custom clothing manufacturer"),
    ("What makes a premium streetwear hoodie", "instagram_carousel", "instagram", "streetwear manufacturer"),
    ("Behind the scenes in garment production", "reel", "instagram", "Bangladesh clothing factory"),
    ("How to choose the right activewear fabric", "blog", "website", "activewear manufacturer"),
    ("Common mistakes new clothing brands make", "linkedin_post", "linkedin", "startup clothing brand manufacturer"),
]

VIDEO_SEEDS = [
    ("From tech pack to sample", "youtube", "private_label_apparel", "custom clothing manufacturer"),
    ("How we inspect hoodie quality", "instagram", "hoodies", "hoodie manufacturer"),
    ("Cotton fleece vs French terry", "youtube", "hoodies", "hoodie manufacturer"),
    ("How private label manufacturing works", "linkedin", "private_label_apparel", "private label clothing manufacturer"),
    ("Factory packing and shipment process", "youtube", "bangladesh_garment_manufacturing", "Bangladesh clothing factory"),
    ("How brands save cost with Bangladesh production", "linkedin", "bangladesh_garment_manufacturing", "garment manufacturer Bangladesh"),
]


def seed_marketing_intelligence(apps, schema_editor):
    Keyword = apps.get_model("marketing", "MarketingKeywordPlan")
    Content = apps.get_model("marketing", "MarketingContentIdea")
    Video = apps.get_model("marketing", "MarketingVideoIdea")
    for keyword, country, category in KEYWORD_SEEDS:
        Keyword.objects.get_or_create(
            keyword=keyword,
            target_country=country,
            defaults={
                "target_audience": "Startup and growing clothing brands",
                "product_category": category,
                "search_intent": "commercial",
                "priority": "medium",
                "trend_status": "unknown",
                "difficulty_estimate": "unknown",
                "content_type": "landing_page",
                "status": "idea",
            },
        )
    for title, content_type, platform, keyword in CONTENT_SEEDS:
        Content.objects.get_or_create(
            title=title,
            defaults={
                "content_type": content_type,
                "target_platform": platform,
                "keyword": keyword,
                "audience": "Startup and growing clothing brands",
                "funnel_stage": "awareness",
                "priority": "medium",
                "status": "idea",
            },
        )
    for title, platform, category, keyword in VIDEO_SEEDS:
        Video.objects.get_or_create(
            video_title=title,
            defaults={
                "platform": platform,
                "hook": f"What brands should know about {title.lower()}",
                "main_talking_points": "Problem, production insight, quality checkpoint, and next step.",
                "product_category": category,
                "target_keyword": keyword,
                "status": "idea",
            },
        )


def remove_marketing_intelligence_seeds(apps, schema_editor):
    Keyword = apps.get_model("marketing", "MarketingKeywordPlan")
    Content = apps.get_model("marketing", "MarketingContentIdea")
    Video = apps.get_model("marketing", "MarketingVideoIdea")
    Keyword.objects.filter(keyword__in=[row[0] for row in KEYWORD_SEEDS], created_by__isnull=True).delete()
    Content.objects.filter(title__in=[row[0] for row in CONTENT_SEEDS], created_by__isnull=True).delete()
    Video.objects.filter(video_title__in=[row[0] for row in VIDEO_SEEDS], created_by__isnull=True).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0008_socialaccount_profile_url_socialaccount_username'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql='ALTER TABLE "marketing_marketingcompetitor" ADD COLUMN "category" varchar(120) NOT NULL DEFAULT \'\';',
                    reverse_sql='ALTER TABLE "marketing_marketingcompetitor" DROP COLUMN "category";',
                ),
                migrations.RunSQL(
                    sql='ALTER TABLE "marketing_marketingcompetitor" ADD COLUMN "country" varchar(2) NOT NULL DEFAULT \'\';',
                    reverse_sql='ALTER TABLE "marketing_marketingcompetitor" DROP COLUMN "country";',
                ),
                migrations.RunSQL(
                    sql='ALTER TABLE "marketing_marketingcompetitor" ADD COLUMN "last_checked_at" datetime NULL;',
                    reverse_sql='ALTER TABLE "marketing_marketingcompetitor" DROP COLUMN "last_checked_at";',
                ),
                migrations.RunSQL(
                    sql='ALTER TABLE "marketing_marketingcompetitor" ADD COLUMN "status" varchar(20) NOT NULL DEFAULT \'watching\';',
                    reverse_sql='ALTER TABLE "marketing_marketingcompetitor" DROP COLUMN "status";',
                ),
            ],
            state_operations=[
                migrations.AddField(
                    model_name='marketingcompetitor',
                    name='category',
                    field=models.CharField(blank=True, default='', max_length=120),
                ),
                migrations.AddField(
                    model_name='marketingcompetitor',
                    name='country',
                    field=models.CharField(blank=True, choices=[('CA', 'Canada'), ('US', 'USA'), ('GB', 'UK'), ('AU', 'Australia'), ('AE', 'UAE'), ('BD', 'Bangladesh')], default='', max_length=2),
                ),
                migrations.AddField(
                    model_name='marketingcompetitor',
                    name='last_checked_at',
                    field=models.DateTimeField(blank=True, null=True),
                ),
                migrations.AddField(
                    model_name='marketingcompetitor',
                    name='status',
                    field=models.CharField(choices=[('watching', 'Watching'), ('paused', 'Paused'), ('archived', 'Archived')], default='watching', max_length=20),
                ),
            ],
        ),
        migrations.CreateModel(
            name='MarketingContentIdea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('content_type', models.CharField(choices=[('blog', 'Blog'), ('video', 'Video'), ('reel', 'Reel'), ('linkedin_post', 'LinkedIn post'), ('instagram_carousel', 'Instagram carousel'), ('tiktok_video', 'TikTok video'), ('google_business_post', 'Google Business post'), ('email_campaign', 'Email campaign'), ('case_study', 'Case study')], default='blog', max_length=30)),
                ('target_platform', models.CharField(choices=[('website', 'Website'), ('linkedin', 'LinkedIn'), ('instagram', 'Instagram'), ('tiktok', 'TikTok'), ('google_business', 'Google Business'), ('youtube', 'YouTube'), ('email', 'Email')], default='website', max_length=30)),
                ('keyword', models.CharField(blank=True, default='', max_length=240)),
                ('audience', models.CharField(blank=True, default='', max_length=240)),
                ('funnel_stage', models.CharField(choices=[('awareness', 'Awareness'), ('consideration', 'Consideration'), ('conversion', 'Conversion'), ('retention', 'Retention')], default='awareness', max_length=20)),
                ('priority', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=10)),
                ('due_date', models.DateField(blank=True, db_index=True, null=True)),
                ('status', models.CharField(choices=[('idea', 'Idea'), ('approved', 'Approved'), ('assigned', 'Assigned'), ('in_progress', 'In progress'), ('ready_for_review', 'Ready for review'), ('published', 'Published'), ('archived', 'Archived')], db_index=True, default='idea', max_length=30)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_marketing_content_ideas', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_marketing_content_ideas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('due_date', '-created_at'),
                'indexes': [models.Index(fields=['target_platform', 'status'], name='marketing_m_target__53be66_idx')],
            },
        ),
        migrations.CreateModel(
            name='MarketingKeywordPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(db_index=True, max_length=240)),
                ('target_country', models.CharField(choices=[('CA', 'Canada'), ('US', 'USA'), ('GB', 'UK'), ('AU', 'Australia'), ('AE', 'UAE'), ('BD', 'Bangladesh')], default='CA', max_length=2)),
                ('target_audience', models.CharField(blank=True, default='', max_length=240)),
                ('product_category', models.CharField(choices=[('hoodies', 'Hoodies'), ('t_shirts', 'T shirts'), ('activewear', 'Activewear'), ('streetwear', 'Streetwear'), ('uniforms', 'Uniforms'), ('kids_clothing', 'Kids clothing'), ('private_label_apparel', 'Private label apparel'), ('low_moq_manufacturing', 'Low MOQ manufacturing'), ('bangladesh_garment_manufacturing', 'Bangladesh garment manufacturing')], default='private_label_apparel', max_length=50)),
                ('search_intent', models.CharField(choices=[('informational', 'Informational'), ('commercial', 'Commercial'), ('transactional', 'Transactional'), ('navigational', 'Navigational')], default='commercial', max_length=20)),
                ('priority', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=10)),
                ('trend_status', models.CharField(choices=[('rising', 'Rising'), ('stable', 'Stable'), ('declining', 'Declining'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('difficulty_estimate', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('content_type', models.CharField(choices=[('landing_page', 'Landing page'), ('blog', 'Blog'), ('video', 'Video'), ('case_study', 'Case study'), ('social', 'Social content')], default='landing_page', max_length=20)),
                ('landing_page_suggestion', models.CharField(blank=True, default='', max_length=300)),
                ('status', models.CharField(choices=[('idea', 'Idea'), ('approved', 'Approved'), ('in_progress', 'In progress'), ('published', 'Published'), ('paused', 'Paused')], default='idea', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marketing_keyword_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['status', 'priority'], name='marketing_m_status_cd0953_idx'), models.Index(fields=['target_country', 'product_category'], name='marketing_m_target__d423c4_idx')],
            },
        ),
        migrations.CreateModel(
            name='MarketingVideoIdea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_title', models.CharField(max_length=300)),
                ('platform', models.CharField(choices=[('youtube', 'YouTube'), ('linkedin', 'LinkedIn'), ('instagram', 'Instagram'), ('tiktok', 'TikTok'), ('facebook', 'Facebook')], default='youtube', max_length=20)),
                ('hook', models.CharField(blank=True, default='', max_length=500)),
                ('main_talking_points', models.TextField(blank=True, default='')),
                ('product_category', models.CharField(choices=[('hoodies', 'Hoodies'), ('t_shirts', 'T shirts'), ('activewear', 'Activewear'), ('streetwear', 'Streetwear'), ('uniforms', 'Uniforms'), ('kids_clothing', 'Kids clothing'), ('private_label_apparel', 'Private label apparel'), ('low_moq_manufacturing', 'Low MOQ manufacturing'), ('bangladesh_garment_manufacturing', 'Bangladesh garment manufacturing')], default='private_label_apparel', max_length=50)),
                ('target_keyword', models.CharField(blank=True, default='', max_length=240)),
                ('status', models.CharField(choices=[('idea', 'Idea'), ('approved', 'Approved'), ('assigned', 'Assigned'), ('in_progress', 'In progress'), ('ready_for_review', 'Ready for review'), ('published', 'Published'), ('archived', 'Archived')], db_index=True, default='idea', max_length=30)),
                ('due_date', models.DateField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_marketing_video_ideas', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_marketing_video_ideas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('due_date', '-created_at'),
                'indexes': [models.Index(fields=['platform', 'status'], name='marketing_m_platfor_0b04ad_idx')],
            },
        ),
        migrations.RunPython(seed_marketing_intelligence, remove_marketing_intelligence_seeds),
    ]
