# Generated by Django 6.0 on 2026-07-05; hardened for additive SQLite changes.

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def add_column(table, name, definition):
    return migrations.RunSQL(
        sql=f'ALTER TABLE "{table}" ADD COLUMN "{name}" {definition};',
        reverse_sql=f'ALTER TABLE "{table}" DROP COLUMN "{name}";',
    )


class Migration(migrations.Migration):
    dependencies = [
        ("marketing", "0009_marketing_intelligence_center"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                add_column("marketing_marketingcompetitor", "content_frequency", "varchar(120) NOT NULL DEFAULT ''"),
                add_column("marketing_marketingcompetitor", "keywords", "text NOT NULL DEFAULT ''"),
                add_column("marketing_marketingcompetitor", "strengths", "text NOT NULL DEFAULT ''"),
                add_column("marketing_marketingcompetitor", "weaknesses", "text NOT NULL DEFAULT ''"),
                add_column("marketing_marketingcontentidea", "author_id", 'bigint NULL REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED'),
                migrations.RunSQL(
                    sql='CREATE INDEX "marketing_marketingcontentidea_author_id_phase2" ON "marketing_marketingcontentidea" ("author_id");',
                    reverse_sql='DROP INDEX "marketing_marketingcontentidea_author_id_phase2";',
                ),
                add_column("marketing_marketingcontentidea", "call_to_action", "varchar(300) NOT NULL DEFAULT ''"),
                add_column("marketing_marketingcontentidea", "estimated_read_time", "smallint unsigned NULL CHECK (estimated_read_time >= 0)"),
                add_column("marketing_marketingcontentidea", "meta_description", "varchar(500) NOT NULL DEFAULT ''"),
                add_column("marketing_marketingcontentidea", "meta_title", "varchar(300) NOT NULL DEFAULT ''"),
                add_column("marketing_marketingcontentidea", "outline", "text NOT NULL DEFAULT ''"),
                add_column("marketing_marketingcontentidea", "secondary_keywords", "text NOT NULL DEFAULT ''"),
                add_column("marketing_marketingkeywordplan", "competition", "varchar(20) NOT NULL DEFAULT 'unknown'"),
                add_column("marketing_marketingkeywordplan", "monthly_search_estimate", "integer unsigned NULL CHECK (monthly_search_estimate >= 0)"),
                add_column("marketing_marketingkeywordplan", "suggested_article", "varchar(300) NOT NULL DEFAULT ''"),
                add_column("marketing_marketingkeywordplan", "suggested_video", "varchar(300) NOT NULL DEFAULT ''"),
                add_column("marketing_marketingvideoidea", "closing_cta", "varchar(300) NOT NULL DEFAULT ''"),
                add_column("marketing_marketingvideoidea", "opening", "text NOT NULL DEFAULT ''"),
                add_column("marketing_marketingvideoidea", "thumbnail_text", "varchar(200) NOT NULL DEFAULT ''"),
                add_column("marketing_marketingvideoidea", "video_length", "varchar(80) NOT NULL DEFAULT ''"),
            ],
            state_operations=[
                migrations.AddField(model_name="marketingcompetitor", name="content_frequency", field=models.CharField(blank=True, default="", max_length=120)),
                migrations.AddField(model_name="marketingcompetitor", name="keywords", field=models.TextField(blank=True, default="")),
                migrations.AddField(model_name="marketingcompetitor", name="strengths", field=models.TextField(blank=True, default="")),
                migrations.AddField(model_name="marketingcompetitor", name="weaknesses", field=models.TextField(blank=True, default="")),
                migrations.AddField(
                    model_name="marketingcontentidea",
                    name="author",
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="authored_marketing_content_ideas", to=settings.AUTH_USER_MODEL),
                ),
                migrations.AddField(model_name="marketingcontentidea", name="call_to_action", field=models.CharField(blank=True, default="", max_length=300)),
                migrations.AddField(model_name="marketingcontentidea", name="estimated_read_time", field=models.PositiveSmallIntegerField(blank=True, null=True)),
                migrations.AddField(model_name="marketingcontentidea", name="meta_description", field=models.CharField(blank=True, default="", max_length=500)),
                migrations.AddField(model_name="marketingcontentidea", name="meta_title", field=models.CharField(blank=True, default="", max_length=300)),
                migrations.AddField(model_name="marketingcontentidea", name="outline", field=models.TextField(blank=True, default="")),
                migrations.AddField(model_name="marketingcontentidea", name="secondary_keywords", field=models.TextField(blank=True, default="")),
                migrations.AddField(
                    model_name="marketingkeywordplan",
                    name="competition",
                    field=models.CharField(choices=[("low", "Low"), ("medium", "Medium"), ("high", "High"), ("unknown", "Unknown")], default="unknown", max_length=20),
                ),
                migrations.AddField(model_name="marketingkeywordplan", name="monthly_search_estimate", field=models.PositiveIntegerField(blank=True, null=True)),
                migrations.AddField(model_name="marketingkeywordplan", name="suggested_article", field=models.CharField(blank=True, default="", max_length=300)),
                migrations.AddField(model_name="marketingkeywordplan", name="suggested_video", field=models.CharField(blank=True, default="", max_length=300)),
                migrations.AddField(model_name="marketingvideoidea", name="closing_cta", field=models.CharField(blank=True, default="", max_length=300)),
                migrations.AddField(model_name="marketingvideoidea", name="opening", field=models.TextField(blank=True, default="")),
                migrations.AddField(model_name="marketingvideoidea", name="thumbnail_text", field=models.CharField(blank=True, default="", max_length=200)),
                migrations.AddField(model_name="marketingvideoidea", name="video_length", field=models.CharField(blank=True, default="", max_length=80)),
                migrations.AlterField(
                    model_name="marketingcontentidea",
                    name="status",
                    field=models.CharField(choices=[("idea", "Idea"), ("approved", "Approved"), ("assigned", "Assigned"), ("in_progress", "In progress"), ("ready_for_review", "Ready for review"), ("scheduled", "Scheduled"), ("published", "Published"), ("archived", "Archived")], db_index=True, default="idea", max_length=30),
                ),
                migrations.AlterField(
                    model_name="marketingvideoidea",
                    name="status",
                    field=models.CharField(choices=[("idea", "Idea"), ("approved", "Approved"), ("assigned", "Assigned"), ("in_progress", "In progress"), ("ready_for_review", "Ready for review"), ("scheduled", "Scheduled"), ("published", "Published"), ("archived", "Archived")], db_index=True, default="idea", max_length=30),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MarketingKeywordGeneration",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("country", models.CharField(choices=[("CA", "Canada"), ("US", "USA"), ("GB", "UK"), ("AU", "Australia"), ("AE", "UAE"), ("BD", "Bangladesh")], default="CA", max_length=2)),
                ("industry", models.CharField(max_length=160)),
                ("product", models.CharField(max_length=160)),
                ("target_customer", models.CharField(max_length=240)),
                ("primary_keywords", models.JSONField(blank=True, default=list)),
                ("secondary_keywords", models.JSONField(blank=True, default=list)),
                ("long_tail_keywords", models.JSONField(blank=True, default=list)),
                ("customer_questions", models.JSONField(blank=True, default=list)),
                ("comparison_keywords", models.JSONField(blank=True, default=list)),
                ("buying_intent_keywords", models.JSONField(blank=True, default=list)),
                ("commercial_keywords", models.JSONField(blank=True, default=list)),
                ("local_keywords", models.JSONField(blank=True, default=list)),
                ("brand_keywords", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="marketing_keyword_generations", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "ordering": ("-created_at",),
                "indexes": [models.Index(fields=["country", "created_at"], name="marketing_m_country_80b6b2_idx")],
            },
        ),
    ]
