# Generated by Django 6.0 on 2026-07-05 05:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def add_column(table, name, definition):
    return migrations.RunSQL(
        sql=f'ALTER TABLE "{table}" ADD COLUMN "{name}" {definition};',
        reverse_sql=f'ALTER TABLE "{table}" DROP COLUMN "{name}";',
    )


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0010_marketing_intelligence_phase2'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                add_column('marketing_marketingcompetitor', 'content_ideas', "text NOT NULL DEFAULT ''"),
                add_column('marketing_marketingkeywordgeneration', 'blog_ideas', "text NOT NULL DEFAULT '[]' CHECK ((JSON_VALID(\"blog_ideas\") OR \"blog_ideas\" IS NULL))"),
                add_column('marketing_marketingkeywordgeneration', 'email_campaign_ideas', "text NOT NULL DEFAULT '[]' CHECK ((JSON_VALID(\"email_campaign_ideas\") OR \"email_campaign_ideas\" IS NULL))"),
                add_column('marketing_marketingkeywordgeneration', 'google_business_post_ideas', "text NOT NULL DEFAULT '[]' CHECK ((JSON_VALID(\"google_business_post_ideas\") OR \"google_business_post_ideas\" IS NULL))"),
                add_column('marketing_marketingkeywordgeneration', 'social_post_ideas', "text NOT NULL DEFAULT '[]' CHECK ((JSON_VALID(\"social_post_ideas\") OR \"social_post_ideas\" IS NULL))"),
                add_column('marketing_marketingkeywordgeneration', 'video_ideas', "text NOT NULL DEFAULT '[]' CHECK ((JSON_VALID(\"video_ideas\") OR \"video_ideas\" IS NULL))"),
            ],
            state_operations=[
                migrations.AddField(model_name='marketingcompetitor', name='content_ideas', field=models.TextField(blank=True, default='')),
                migrations.AddField(model_name='marketingkeywordgeneration', name='blog_ideas', field=models.JSONField(blank=True, default=list)),
                migrations.AddField(model_name='marketingkeywordgeneration', name='email_campaign_ideas', field=models.JSONField(blank=True, default=list)),
                migrations.AddField(model_name='marketingkeywordgeneration', name='google_business_post_ideas', field=models.JSONField(blank=True, default=list)),
                migrations.AddField(model_name='marketingkeywordgeneration', name='social_post_ideas', field=models.JSONField(blank=True, default=list)),
                migrations.AddField(model_name='marketingkeywordgeneration', name='video_ideas', field=models.JSONField(blank=True, default=list)),
                migrations.AlterField(
                    model_name='marketingcontentidea',
                    name='content_type',
                    field=models.CharField(choices=[('blog', 'Blog'), ('video', 'Video'), ('reel', 'Reel'), ('linkedin_post', 'LinkedIn post'), ('instagram_carousel', 'Instagram carousel'), ('tiktok_video', 'TikTok video'), ('youtube_short', 'YouTube Short'), ('google_business_post', 'Google Business post'), ('email_campaign', 'Email campaign'), ('case_study', 'Case study')], default='blog', max_length=30),
                ),
            ],
        ),
        migrations.CreateModel(
            name='MarketingTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('due_date', models.DateField(blank=True, db_index=True, null=True)),
                ('priority', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=10)),
                ('platform', models.CharField(choices=[('website', 'Website'), ('google_business', 'Google Business'), ('linkedin', 'LinkedIn'), ('facebook', 'Facebook'), ('instagram', 'Instagram'), ('tiktok', 'TikTok'), ('youtube', 'YouTube'), ('email', 'Email')], default='website', max_length=30)),
                ('status', models.CharField(choices=[('assigned', 'Assigned'), ('in_progress', 'In progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='assigned', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_marketing_tasks', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_marketing_tasks', to=settings.AUTH_USER_MODEL)),
                ('source_content', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marketing_tasks', to='marketing.marketingcontentidea')),
                ('source_keyword', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marketing_tasks', to='marketing.marketingkeywordplan')),
            ],
            options={
                'ordering': ('due_date', '-priority', '-created_at'),
                'indexes': [models.Index(fields=['status', 'priority'], name='marketing_m_status_0dddc5_idx')],
            },
        ),
        migrations.CreateModel(
            name='MarketingTrendEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trend_category', models.CharField(max_length=120)),
                ('country', models.CharField(choices=[('CA', 'Canada'), ('US', 'USA'), ('GB', 'UK'), ('AU', 'Australia'), ('AE', 'UAE'), ('BD', 'Bangladesh')], default='CA', max_length=2)),
                ('product', models.CharField(max_length=160)),
                ('keyword', models.CharField(db_index=True, max_length=240)),
                ('trend_direction', models.CharField(choices=[('rising', 'Rising'), ('stable', 'Stable'), ('declining', 'Declining'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('recommended_content_idea', models.CharField(blank=True, default='', max_length=300)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marketing_trend_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-updated_at',),
                'indexes': [models.Index(fields=['country', 'trend_direction'], name='marketing_m_country_3aaa59_idx')],
            },
        ),
    ]
