# Generated by Django 5.2.8 on 2026-07-25

from decimal import Decimal

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketing", "0011_marketing_operations_center"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="websitetrafficdaily",
            options={"ordering": ("-date", "row_type", "channel", "source")},
        ),
        migrations.RemoveConstraint(
            model_name="websitetrafficdaily",
            name="website_traffic_daily_unique",
        ),
        migrations.RemoveIndex(
            model_name="websitetrafficdaily",
            name="marketing_w_channel_ff89db_idx",
        ),
        migrations.AddField(
            model_name="seoproperty",
            name="google_account_email",
            field=models.EmailField(blank=True, default="", max_length=254),
        ),
        migrations.AddField(
            model_name="seoproperty",
            name="google_account_id",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
        migrations.AddField(
            model_name="seoproperty",
            name="last_ga4_sync_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="seoproperty",
            name="last_ga4_sync_message",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="seoproperty",
            name="last_ga4_sync_status",
            field=models.CharField(blank=True, default="", max_length=30),
        ),
        migrations.AddField(
            model_name="seoproperty",
            name="last_gsc_sync_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="seoproperty",
            name="last_gsc_sync_message",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="seoproperty",
            name="last_gsc_sync_status",
            field=models.CharField(blank=True, default="", max_length=30),
        ),
        migrations.AddField(
            model_name="websitetrafficdaily",
            name="avg_session_duration_seconds",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="websitetrafficdaily",
            name="bounce_rate",
            field=models.DecimalField(decimal_places=4, default=Decimal("0"), max_digits=6),
        ),
        migrations.AddField(
            model_name="websitetrafficdaily",
            name="country",
            field=models.CharField(blank=True, db_index=True, default="", max_length=80),
        ),
        migrations.AddField(
            model_name="websitetrafficdaily",
            name="device",
            field=models.CharField(blank=True, db_index=True, default="", max_length=40),
        ),
        migrations.AddField(
            model_name="websitetrafficdaily",
            name="row_type",
            field=models.CharField(blank=True, db_index=True, default="source", max_length=20),
        ),
        migrations.AlterField(
            model_name="oauthconnectionrequest",
            name="platform",
            field=models.CharField(
                choices=[
                    ("gsc", "Google Search Console"),
                    ("ga4", "Google Analytics 4"),
                    ("meta", "Meta"),
                    ("facebook", "Facebook"),
                    ("meta_business", "Meta Business Suite"),
                    ("instagram", "Instagram"),
                    ("linkedin", "LinkedIn"),
                    ("tiktok", "TikTok"),
                    ("youtube", "YouTube"),
                    ("google_business", "Google Business Profile"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="oauthcredential",
            name="platform",
            field=models.CharField(
                choices=[
                    ("gsc", "Google Search Console"),
                    ("ga4", "Google Analytics 4"),
                    ("meta", "Meta"),
                    ("facebook", "Facebook"),
                    ("meta_business", "Meta Business Suite"),
                    ("instagram", "Instagram"),
                    ("linkedin", "LinkedIn"),
                    ("tiktok", "TikTok"),
                    ("youtube", "YouTube"),
                    ("google_business", "Google Business Profile"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="websitetrafficdaily",
            index=models.Index(fields=["row_type", "channel", "source"], name="marketing_w_row_typ_608230_idx"),
        ),
        migrations.AddIndex(
            model_name="websitetrafficdaily",
            index=models.Index(fields=["row_type", "country", "device"], name="marketing_w_row_typ_9e8ff8_idx"),
        ),
        migrations.AddConstraint(
            model_name="websitetrafficdaily",
            constraint=models.UniqueConstraint(
                fields=(
                    "property",
                    "date",
                    "row_type",
                    "channel",
                    "source",
                    "medium",
                    "campaign",
                    "country",
                    "device",
                ),
                name="website_traffic_daily_unique",
            ),
        ),
    ]
