server {
    listen 80;
    server_name kpi-staging.100-51-11-48.sslip.io;

    location /.well-known/acme-challenge/ {
        root /home/ec2-user/iconic_kpi_staging/var/acme;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}
