# Generated by Django 6.0 on 2026-04-17 22:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leadbrain', '0005_upload_status_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadBrainWorker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('status', models.CharField(choices=[('starting', 'Starting'), ('idle', 'Idle'), ('running', 'Running'), ('stopped', 'Stopped'), ('failed', 'Failed')], default='starting', max_length=20)),
                ('hostname', models.CharField(blank=True, max_length=255)),
                ('pid', models.PositiveIntegerField(blank=True, null=True)),
                ('heartbeat_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('processed_batches', models.PositiveIntegerField(default=0)),
                ('processed_rows', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_upload', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='worker_assignments', to='leadbrain.leadbrainupload')),
            ],
            options={
                'ordering': ['name', 'id'],
            },
        ),
    ]
