# Generated by Django 6.0 on 2026-04-18 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leadbrain', '0006_leadbrainworker'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadbrainupload',
            name='imported_rows',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='leadbrainupload',
            name='invalid_rows',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='leadbrainupload',
            name='skipped_duplicate_rows',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='leadbrainupload',
            name='source_row_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
