# Generated by Django 6.0 on 2026-04-18 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leadbrain', '0007_leadbrainupload_imported_rows_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadbraincompany',
            name='research_claim_token',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name='leadbraincompany',
            name='research_claimed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
