# Generated by Django 6.0 on 2026-04-19 17:53

from django.conf import settings
from django.db import migrations, models


def migrate_pending_uploads_to_queued(apps, schema_editor):
    LeadBrainUpload = apps.get_model('leadbrain', 'LeadBrainUpload')
    LeadBrainUpload.objects.filter(status='pending').update(status='queued')


class Migration(migrations.Migration):

    dependencies = [
        ('leadbrain', '0008_leadbraincompany_research_claim_token_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='leadbrainupload',
            name='leadbrain_active_upload_per_user_hash',
        ),
        migrations.AddField(
            model_name='leadbrainupload',
            name='detected_columns_json',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='leadbrainupload',
            name='file_size',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='leadbrainupload',
            name='invalid_row_examples_json',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='leadbrainupload',
            name='sample_rows_json',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='leadbrainupload',
            name='status',
            field=models.CharField(choices=[('queued', 'Queued'), ('parsing', 'Parsing'), ('processing', 'Processing'), ('partial', 'Partial'), ('complete', 'Complete'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='queued', max_length=20),
        ),
        migrations.RunPython(migrate_pending_uploads_to_queued, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='leadbrainupload',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['queued', 'parsing', 'processing']), models.Q(('file_hash', ''), _negated=True)), fields=('uploaded_by', 'file_hash'), name='leadbrain_active_upload_per_user_hash'),
        ),
    ]
