# Generated by Django 6.0 on 2026-04-20 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leadbrain', '0009_remove_leadbrainupload_leadbrain_active_upload_per_user_hash_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadbrainupload',
            name='blank_rows',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='leadbrainupload',
            name='duplicate_row_examples_json',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
