# Generated by Django 6.0 on 2026-04-22 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0133_merge_20260325_0000"),
        ("leadbrain", "0010_leadbrainupload_blank_rows_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="leadbraincompany",
            name="moved_to_lead",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="leadbrain_companies",
                to="crm.lead",
            ),
        ),
        migrations.AddField(
            model_name="leadbraincompany",
            name="moved_to_leads",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="leadbraincompany",
            name="moved_to_leads_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
