# Generated by Django 6.0 on 2026-04-22 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leadbrain", "0011_leadbraincompany_moved_to_lead_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="leadbraincompany",
            name="moved_to_lead_code",
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
