# Generated by Django 6.0 on 2026-04-22 21:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leadbrain", "0012_leadbraincompany_moved_to_lead_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="leadbraincompany",
            name="duplicate_of",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="inactive_duplicates",
                to="leadbrain.leadbraincompany",
            ),
        ),
        migrations.AddField(
            model_name="leadbraincompany",
            name="inactive_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="leadbraincompany",
            name="inactive_reason",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="leadbraincompany",
            name="is_active",
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name="leadbrainupload",
            name="inactive_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="leadbrainupload",
            name="inactive_reason",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="leadbrainupload",
            name="is_active",
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
