# Generated by Django 6.0 on 2026-04-22 20:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leadbrain', '0013_leadbrain_cleanup_flags'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadBrainDiscoveryJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('web_search', 'Public Web Search'), ('business_directories', 'Business Directories'), ('shopify_stores', 'Shopify Related Stores')], max_length=40)),
                ('country', models.CharField(choices=[('Canada', 'Canada'), ('USA', 'USA')], max_length=40)),
                ('niche', models.CharField(choices=[('streetwear', 'Streetwear'), ('activewear', 'Activewear'), ('kidswear', 'Kidswear'), ('ecommerce_apparel', 'Ecommerce Apparel'), ('boutique_fashion', 'Boutique Fashion'), ('private_label', 'Private Label'), ('uniforms', 'Uniforms'), ('merch', 'Merch')], max_length=40)),
                ('max_results', models.PositiveIntegerField(default=25)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('processing', 'Processing'), ('complete', 'Complete'), ('partial', 'Partial'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='queued', max_length=20)),
                ('results_found', models.PositiveIntegerField(default=0)),
                ('candidates_saved', models.PositiveIntegerField(default=0)),
                ('duplicates_skipped', models.PositiveIntegerField(default=0)),
                ('weak_skipped', models.PositiveIntegerField(default=0)),
                ('failed_candidates', models.PositiveIntegerField(default=0)),
                ('status_note', models.TextField(blank=True)),
                ('sample_results_json', models.JSONField(blank=True, default=list)),
                ('duplicate_examples_json', models.JSONField(blank=True, default=list)),
                ('saved_examples_json', models.JSONField(blank=True, default=list)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leadbrain_discovery_jobs', to=settings.AUTH_USER_MODEL)),
                ('upload', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discovery_jobs', to='leadbrain.leadbrainupload')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
