# Generated by Django 6.0 on 2026-04-23 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leadbrain", "0014_leadbraindiscoveryjob"),
    ]

    operations = [
        migrations.AddField(
            model_name="leadbraindiscoveryjob",
            name="query_plan_json",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="leadbraindiscoveryjob",
            name="scheduled_for_date",
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="leadbraindiscoveryjob",
            name="scheduled_slot",
            field=models.CharField(
                blank=True,
                choices=[("canada_morning", "Canada Morning"), ("usa_afternoon", "USA Afternoon")],
                default="",
                max_length=40,
            ),
        ),
        migrations.AddField(
            model_name="leadbraindiscoveryjob",
            name="trigger_mode",
            field=models.CharField(
                choices=[("manual", "Manual"), ("scheduled", "Scheduled")],
                default="manual",
                max_length=20,
            ),
        ),
    ]
