# Generated by Django 6.0 on 2026-04-23 01:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leadbrain', '0015_leadbraindiscoveryjob_query_plan_json_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadbraindiscoveryjob',
            name='apparel_only',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='leadbraindiscoveryjob',
            name='is_paused',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='leadbraindiscoveryjob',
            name='max_runs_per_day',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='leadbraindiscoveryjob',
            name='minimum_score',
            field=models.PositiveSmallIntegerField(default=65),
        ),
        migrations.AddField(
            model_name='leadbraindiscoveryjob',
            name='name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='leadbraindiscoveryjob',
            name='next_run_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='leadbraindiscoveryjob',
            name='schedule_type',
            field=models.CharField(choices=[('manual', 'Manual'), ('daily', 'Daily'), ('weekly', 'Weekly')], default='manual', max_length=20),
        ),
        migrations.AddField(
            model_name='leadbraindiscoveryjob',
            name='selected_sources_json',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='leadbraindiscoveryjob',
            name='total_leads_found',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='leadbraindiscoveryjob',
            name='total_runs',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='leadbraindiscoveryjob',
            name='total_strong_fits',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='leadbraindiscoveryjob',
            name='source_type',
            field=models.CharField(choices=[('web_search', 'Google Search Patterns'), ('business_directories', 'Business Directories'), ('shopify_stores', 'Shopify Store Detection')], max_length=40),
        ),
        migrations.CreateModel(
            name='LeadBrainDiscoveryRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('processing', 'Processing'), ('complete', 'Complete'), ('partial', 'Partial'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='queued', max_length=20)),
                ('results_found', models.PositiveIntegerField(default=0)),
                ('candidates_saved', models.PositiveIntegerField(default=0)),
                ('duplicates_skipped', models.PositiveIntegerField(default=0)),
                ('weak_skipped', models.PositiveIntegerField(default=0)),
                ('failed_candidates', models.PositiveIntegerField(default=0)),
                ('strong_fits_found', models.PositiveIntegerField(default=0)),
                ('status_note', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='leadbrain.leadbraindiscoveryjob')),
                ('upload', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discovery_runs', to='leadbrain.leadbrainupload')),
            ],
            options={
                'ordering': ['-started_at', '-id'],
            },
        ),
    ]
