# Generated by Django 6.0 on 2026-05-04 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leadbrain', '0017_discovery_engine_backend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadbraindiscoveryjob',
            name='country',
            field=models.CharField(choices=[('Canada', 'Canada'), ('USA', 'USA'), ('North America', 'North America')], max_length=40),
        ),
        migrations.AlterField(
            model_name='leadbraindiscoveryjob',
            name='niche',
            field=models.CharField(choices=[('streetwear', 'Streetwear'), ('activewear', 'Activewear'), ('kidswear', 'Kidswear'), ('fashion', 'Fashion'), ('swimwear', 'Swimwear'), ('hoodies', 'Hoodies'), ('t_shirts', 'T Shirts'), ('ecommerce_apparel', 'Ecommerce Apparel'), ('boutique_fashion', 'Boutique Fashion'), ('private_label', 'Private Label'), ('uniforms', 'Uniforms'), ('merch', 'Merch')], max_length=40),
        ),
        migrations.AlterField(
            model_name='leadbraindiscoveryjob',
            name='source_type',
            field=models.CharField(choices=[('web_search', 'Google Search Patterns'), ('business_directories', 'Business Directories'), ('shopify_stores', 'Shopify Store Detection'), ('shopify_clothing_directory', 'Shopify Clothing Directory')], max_length=40),
        ),
    ]
