# Generated by Django 5.2.8 on 2025-11-13 00:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market', models.CharField(choices=[('BD', 'Bangladesh'), ('CA', 'Canada'), ('BOTH', 'Both'), ('OTHER', 'Other')], default='BD', max_length=10)),
                ('lead_id', models.CharField(blank=True, max_length=50, unique=True)),
                ('account_brand', models.CharField(max_length=200)),
                ('contact_name', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('source', models.CharField(choices=[('Website Inquiry', 'Website Inquiry'), ('Instagram', 'Instagram'), ('LinkedIn', 'LinkedIn'), ('Email Campaign', 'Email Campaign'), ('Referral', 'Referral'), ('Google Search / SEO', 'Google Search / SEO'), ('Trade Show / Event', 'Trade Show / Event'), ('WhatsApp', 'WhatsApp'), ('Returning Client', 'Returning Client'), ('Other', 'Other')], db_index=True, default='Website Inquiry', max_length=50)),
                ('lead_type', models.CharField(choices=[('Startup / New Brand', 'Startup / New Brand'), ('Brand Owner / Designer', 'Brand Owner / Designer'), ('Retail Store / Boutique', 'Retail Store / Boutique'), ('Corporate Client', 'Corporate Client'), ('Distributor / Wholesaler', 'Distributor / Wholesaler'), ('Private Label Client', 'Private Label Client'), ('Manufacturer Collaboration', 'Manufacturer Collaboration'), ('Influencer / Content Creator', 'Influencer / Content Creator'), ('Returning Customer', 'Returning Customer'), ('Other', 'Other')], db_index=True, default='Startup / New Brand', max_length=50)),
                ('lead_status', models.CharField(choices=[('New', 'New'), ('Working', 'Working'), ('Nurturing', 'Nurturing'), ('Qualified', 'Qualified'), ('Unqualified', 'Unqualified'), ('Converted', 'Converted'), ('On Hold', 'On Hold'), ('Lost', 'Lost')], db_index=True, default='New', max_length=50)),
                ('priority', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Hot', 'Hot')], db_index=True, default='Medium', max_length=20)),
                ('owner', models.CharField(blank=True, max_length=100)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('next_followup', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_code', models.CharField(blank=True, max_length=50, unique=True)),
                ('account_brand', models.CharField(max_length=200)),
                ('contact_name', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('market', models.CharField(blank=True, max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('lead', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to='crm.lead')),
            ],
        ),
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opportunity_id', models.CharField(blank=True, max_length=50, unique=True)),
                ('stage', models.CharField(choices=[('Prospecting', 'Prospecting'), ('Qualification', 'Qualification'), ('Needs Analysis', 'Needs Analysis'), ('Proposal', 'Proposal or Quote'), ('Negotiation', 'Negotiation'), ('Sampling', 'Sampling'), ('Production', 'Production'), ('Shipment Complete', 'Shipment Complete'), ('Closed Won', 'Closed Won'), ('Closed Lost', 'Closed Lost')], default='Prospecting', max_length=50)),
                ('product_type', models.CharField(blank=True, max_length=100)),
                ('product_category', models.CharField(blank=True, max_length=100)),
                ('moq_units', models.IntegerField(blank=True, null=True)),
                ('order_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('next_followup', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('is_open', models.BooleanField(default=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opportunities', to='crm.lead')),
            ],
        ),
    ]
