# Generated by Django 5.2.8 on 2025-11-13 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_alter_customer_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunity',
            name='product_category',
            field=models.CharField(choices=[('Swimwear', 'Swimwear'), ('Athleticwear', 'Athleticwear'), ('Activewear', 'Activewear'), ('Streetwear', 'Streetwear'), ('Undergarments', 'Undergarments'), ('Kids', 'Kids'), ('Corporate', 'Corporate'), ('Promo', 'Promotional'), ('Other', 'Other')], default='Other', max_length=50),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='product_type',
            field=models.CharField(choices=[('T Shirt', 'T Shirt'), ('Hoodie', 'Hoodie'), ('Sweatpant', 'Sweatpant'), ('Short', 'Short'), ('Legging', 'Legging'), ('Sports Bra', 'Sports Bra'), ('Swimsuit', 'Swimsuit'), ('Jacket', 'Jacket'), ('Set', 'Set'), ('Other', 'Other')], default='Other', max_length=50),
        ),
    ]
