# Generated by Django 5.2.8 on 2025-11-14 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_alter_opportunity_product_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='lead_files/'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='market',
            field=models.CharField(choices=[('BD', 'Bangladesh'), ('CA', 'Canada'), ('USA', 'USA'), ('OTHER', 'Other')], default='BD', max_length=10),
        ),
    ]
