# Generated by Django 5.2.8 on 2025-11-16 04:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_lead_budget_lead_city_lead_company_website_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='shipping_address1',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='customer',
            name='shipping_address2',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='customer',
            name='shipping_city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='customer',
            name='shipping_country',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='customer',
            name='shipping_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='customer',
            name='shipping_postcode',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='customer',
            name='shipping_state',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='lead',
            name='company_website',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='product_category',
            field=models.CharField(choices=[('Leggings', 'Leggings'), ('Sports Bra', 'Sports Bra'), ('Crop Top', 'Crop Top'), ('Yoga Set', 'Yoga Set'), ('Tank Top', 'Tank Top'), ('Joggers', 'Joggers'), ('Track Pants', 'Track Pants'), ('Tracksuit Set', 'Tracksuit Set'), ('Training Jacket', 'Training Jacket'), ('Windbreaker', 'Windbreaker'), ('Hoodie', 'Hoodie'), ('Sweatshirt', 'Sweatshirt'), ('Cargo Pants', 'Cargo Pants'), ('Oversized Tee', 'Oversized Tee'), ('Denim Jacket', 'Denim Jacket'), ('Bikini Set', 'Bikini Set'), ('One Piece', 'One Piece'), ('Mens Trunk', 'Mens Trunk'), ('Rash Guard', 'Rash Guard'), ('Mens Boxer', 'Mens Boxer'), ('Brief', 'Brief'), ('Womens Panty', 'Womens Panty'), ('Bra', 'Bra'), ('Camisole', 'Camisole'), ('Padded Jacket', 'Padded Jacket'), ('Light Jacket', 'Light Jacket'), ('Pullover', 'Pullover'), ('Zip Up Hoodie', 'Zip Up Hoodie'), ('T Shirt', 'T Shirt'), ('Polo Shirt', 'Polo Shirt'), ('Lounge Set', 'Lounge Set'), ('Shorts', 'Shorts'), ('Onesie', 'Onesie'), ('Romper', 'Romper'), ('Hoodie Set', 'Hoodie Set'), ('Jogger Set', 'Jogger Set'), ('Baby Sleeper', 'Baby Sleeper'), ('Office Shirt', 'Office Shirt'), ('Polo Uniform', 'Polo Uniform'), ('Work Jacket', 'Work Jacket'), ('Promotional Tee', 'Promotional Tee'), ('Organic Cotton Wear', 'Organic Cotton Wear'), ('Recycled Polyester', 'Recycled Polyester'), ('Eco Fabric Product', 'Eco Fabric Product'), ('Cap', 'Cap'), ('Tote Bag', 'Tote Bag'), ('Socks', 'Socks'), ('Headband', 'Headband'), ('Other', 'Other')], default='Other', max_length=50),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='product_type',
            field=models.CharField(choices=[('Activewear', 'Activewear'), ('Athleticwear', 'Athleticwear'), ('Streetwear', 'Streetwear'), ('Swimwear', 'Swimwear'), ('Undergarments', 'Undergarments'), ('Outerwear', 'Outerwear'), ('Casualwear', 'Casualwear'), ('Kidswear', 'Kidswear'), ('Corporate / Uniforms', 'Corporate / Uniforms'), ('Sustainable Collection', 'Sustainable Collection'), ('Accessories', 'Accessories'), ('Other', 'Other')], default='Other', max_length=50),
        ),
        migrations.CreateModel(
            name='LeadActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activity_type', models.CharField(choices=[('lead_created', 'Lead created'), ('converted', 'Converted to opportunity'), ('ai_summary', 'AI summary created'), ('file_uploaded', 'File uploaded'), ('note_added', 'Note added'), ('task_created', 'Task created'), ('task_completed', 'Task completed')], max_length=40)),
                ('description', models.TextField(blank=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='crm.lead')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LeadComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.CharField(blank=True, max_length=100)),
                ('content', models.TextField()),
                ('pinned', models.BooleanField(default=False)),
                ('is_ai', models.BooleanField(default=False)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='crm.lead')),
            ],
            options={
                'ordering': ['-pinned', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LeadTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Open', 'Open'), ('In Progress', 'In Progress'), ('Done', 'Done')], default='Open', max_length=20)),
                ('priority', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Hot', 'Hot')], default='Medium', max_length=20)),
                ('assigned_to', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='crm.lead')),
            ],
            options={
                'ordering': ['status', 'due_date', '-created_at'],
            },
        ),
    ]
