# Generated by Django 5.2.8 on 2025-11-16 21:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_customer_shipping_address1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadcomment',
            name='opportunity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='crm.opportunity'),
        ),
    ]
