# Generated by Django 5.2.8 on 2025-11-17 02:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0008_opportunitytask'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadactivity',
            name='activity_type',
            field=models.CharField(choices=[('lead_created', 'Lead created'), ('converted', 'Converted to opportunity'), ('ai_summary', 'AI summary created'), ('file_uploaded', 'File uploaded'), ('file_deleted', 'File deleted'), ('note_added', 'Note added'), ('task_created', 'Task created'), ('task_completed', 'Task completed'), ('shipping_updated', 'Shipping updated'), ('stage_updated', 'Stage updated')], max_length=40),
        ),
        migrations.CreateModel(
            name='OpportunityFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='opportunity_files/')),
                ('original_name', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.CharField(blank=True, max_length=100)),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='crm.opportunity')),
            ],
        ),
    ]
