# Generated by Django 5.2.8 on 2025-11-21 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0010_product_alter_opportunityfile_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accessory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accessory_code', models.CharField(blank=True, max_length=50, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('accessory_type', models.CharField(blank=True, max_length=100)),
                ('size', models.CharField(blank=True, max_length=100)),
                ('color', models.CharField(blank=True, max_length=100)),
                ('material', models.CharField(blank=True, max_length=100)),
                ('finish', models.CharField(blank=True, max_length=100)),
                ('supplier', models.CharField(blank=True, max_length=200)),
                ('price_per_unit', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Fabric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fabric_code', models.CharField(blank=True, max_length=50, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('fabric_group', models.CharField(blank=True, max_length=100)),
                ('fabric_type', models.CharField(blank=True, max_length=100)),
                ('weave', models.CharField(blank=True, max_length=100)),
                ('knit_structure', models.CharField(blank=True, max_length=100)),
                ('construction', models.CharField(blank=True, max_length=200)),
                ('composition', models.CharField(blank=True, max_length=200)),
                ('gsm', models.CharField(blank=True, max_length=50)),
                ('stretch_type', models.CharField(blank=True, max_length=100)),
                ('surface', models.CharField(blank=True, max_length=100)),
                ('handfeel', models.CharField(blank=True, max_length=100)),
                ('drape', models.CharField(blank=True, max_length=100)),
                ('warmth', models.CharField(blank=True, max_length=100)),
                ('weight_class', models.CharField(blank=True, max_length=100)),
                ('breathability', models.CharField(blank=True, max_length=100)),
                ('sheerness', models.CharField(blank=True, max_length=100)),
                ('shrinkage', models.CharField(blank=True, max_length=100)),
                ('durability', models.CharField(blank=True, max_length=100)),
                ('color_options', models.CharField(blank=True, max_length=255)),
                ('finish', models.CharField(blank=True, max_length=200)),
                ('treatments', models.CharField(blank=True, max_length=255)),
                ('dye_type', models.CharField(blank=True, max_length=100)),
                ('print_compatibility', models.CharField(blank=True, max_length=200)),
                ('typical_uses', models.TextField(blank=True)),
                ('price_per_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('price_per_meter', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ThreadOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thread_code', models.CharField(blank=True, max_length=50, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('thread_type', models.CharField(blank=True, max_length=100)),
                ('count', models.CharField(blank=True, max_length=100)),
                ('color', models.CharField(blank=True, max_length=100)),
                ('brand', models.CharField(blank=True, max_length=100)),
                ('use_for', models.CharField(blank=True, max_length=200)),
                ('price_per_cone', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Trim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trim_code', models.CharField(blank=True, max_length=50, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('trim_type', models.CharField(blank=True, max_length=100)),
                ('width', models.CharField(blank=True, max_length=50)),
                ('color', models.CharField(blank=True, max_length=100)),
                ('material', models.CharField(blank=True, max_length=100)),
                ('price_per_meter', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
