# Generated by Django 5.2.8 on 2025-11-21 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0011_accessory_fabric_threadoption_trim'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fabric',
            name='dye_type',
        ),
        migrations.RemoveField(
            model_name='fabric',
            name='finish',
        ),
        migrations.RemoveField(
            model_name='fabric',
            name='print_compatibility',
        ),
        migrations.RemoveField(
            model_name='fabric',
            name='treatments',
        ),
        migrations.RemoveField(
            model_name='fabric',
            name='typical_uses',
        ),
        migrations.AddField(
            model_name='accessory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='accessory_images/'),
        ),
        migrations.AddField(
            model_name='fabric',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='fabric_images/'),
        ),
        migrations.AddField(
            model_name='threadoption',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='thread_images/'),
        ),
        migrations.AddField(
            model_name='trim',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='trim_images/'),
        ),
    ]
