# Generated by Django 5.2.8 on 2025-11-23 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0014_fabricgroupmaster_fabrictypemaster_handfeelmaster_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FabricChoiceMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('category', models.CharField(choices=[('group', 'Fabric Group'), ('type', 'Fabric Type'), ('structure', 'Knit Structure'), ('weave', 'Weave'), ('surface', 'Surface'), ('handfeel', 'Handfeel')], default='group', max_length=50)),
            ],
        ),
    ]
