# Generated by Django 5.2.8 on 2025-11-24 02:29

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0015_fabricchoicemaster'),
    ]

    operations = [
        migrations.CreateModel(
            name='FabricNameMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='GSMRangeMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProductCategoryMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProductTypeMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='fabricgroupmaster',
            options={'verbose_name': 'Fabric group', 'verbose_name_plural': 'Fabric groups'},
        ),
        migrations.RemoveField(
            model_name='threadoption',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='threadoption',
            name='color',
        ),
        migrations.RemoveField(
            model_name='threadoption',
            name='count',
        ),
        migrations.RemoveField(
            model_name='threadoption',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='threadoption',
            name='image',
        ),
        migrations.RemoveField(
            model_name='threadoption',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='threadoption',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='threadoption',
            name='price_per_cone',
        ),
        migrations.RemoveField(
            model_name='threadoption',
            name='thread_type',
        ),
        migrations.RemoveField(
            model_name='threadoption',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='threadoption',
            name='use_for',
        ),
        migrations.AddField(
            model_name='fabricgroupmaster',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fabricgroupmaster',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='fabricgroupmaster',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('thread', 'Thread'), ('needle', 'Needle'), ('accessory', 'Accessory'), ('trim', 'Trim'), ('fabric_roll', 'Fabric roll'), ('polybag', 'Polybag'), ('carton', 'Carton'), ('other', 'Other')], default='other', max_length=50)),
                ('sku', models.CharField(blank=True, max_length=100)),
                ('code', models.CharField(blank=True, max_length=100)),
                ('unit_type', models.CharField(default='pcs', max_length=50)),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('min_level', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='inventory_images/')),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('accessory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.accessory')),
                ('fabric', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.fabric')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.product')),
                ('thread_option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.threadoption')),
                ('trim', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.trim')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
