# Generated by Django 5.2.8 on 2025-11-24 23:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0016_fabricnamemaster_gsmrangemaster_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryReorder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reorders', to='crm.inventoryitem')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
