# Generated by Django 5.2.8 on 2025-11-26 19:57

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0018_inventoryreorder_created_by'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventoryreorder',
            options={},
        ),
        migrations.RemoveField(
            model_name='inventoryreorder',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='inventoryreorder',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='inventoryreorder',
            name='item',
        ),
        migrations.RemoveField(
            model_name='inventoryreorder',
            name='note',
        ),
        migrations.RemoveField(
            model_name='inventoryreorder',
            name='quantity',
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('start_datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_datetime', models.DateTimeField(blank=True, null=True)),
                ('event_type', models.CharField(choices=[('call', 'Call or online meeting'), ('meeting', 'Office meeting'), ('follow_up', 'Follow up'), ('sample', 'Sample work'), ('production', 'Production'), ('shipping', 'Shipping'), ('payment', 'Payment'), ('other', 'Other')], default='call', max_length=20)),
                ('owner_name', models.CharField(blank=True, help_text='Person in Iconic who owns this event', max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='crm.customer')),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='crm.lead')),
                ('opportunity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='crm.opportunity')),
            ],
            options={
                'ordering': ['start_datetime'],
            },
        ),
    ]
