# Generated by Django 5.2.8 on 2025-11-27 04:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0019_alter_inventoryreorder_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='event',
            name='lead',
        ),
        migrations.RemoveField(
            model_name='event',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='event',
            name='opportunity',
        ),
        migrations.RemoveField(
            model_name='event',
            name='owner_name',
        ),
        migrations.AddField(
            model_name='event',
            name='ai_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='event',
            name='note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='event',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10),
        ),
        migrations.AddField(
            model_name='event',
            name='related_lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='crm.lead'),
        ),
        migrations.AddField(
            model_name='event',
            name='related_opportunity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='crm.opportunity'),
        ),
        migrations.AddField(
            model_name='event',
            name='reminder_minutes_before',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('planned', 'Planned'), ('in_progress', 'In work'), ('done', 'Done')], default='planned', max_length=20),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('call', 'Client call'), ('followup', 'Follow up'), ('sample', 'Sample work'), ('shipping', 'Shipping'), ('factory', 'Factory work'), ('internal', 'Internal task')], default='call', max_length=20),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
