# Generated by Django 5.2.8 on 2025-11-27 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0020_remove_event_customer_remove_event_lead_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='related_lead',
            new_name='lead',
        ),
        migrations.RemoveField(
            model_name='event',
            name='related_opportunity',
        ),
        migrations.AddField(
            model_name='event',
            name='opportunity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='crm.opportunity'),
        ),
        migrations.AddField(
            model_name='event',
            name='production_stage',
            field=models.CharField(blank=True, choices=[('', 'No production link'), ('sampling', 'Sampling'), ('bulk', 'Bulk Production'), ('shipping', 'Shipping')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('call', 'Call'), ('follow_up', 'Follow up'), ('sample', 'Sample Work'), ('shipping', 'Shipping'), ('production', 'Production'), ('meeting', 'Meeting')], default='call', max_length=50),
        ),
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('planned', 'Planned'), ('in_progress', 'In Progress'), ('done', 'Done')], default='planned', max_length=20),
        ),
    ]
