# Generated by Django 5.2.8 on 2025-11-27 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0021_rename_related_lead_event_lead_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='note',
        ),
        migrations.RemoveField(
            model_name='event',
            name='production_stage',
        ),
        migrations.RemoveField(
            model_name='event',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='event',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.customer'),
        ),
        migrations.AddField(
            model_name='event',
            name='short_note',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='ai_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('call', 'Call'), ('follow_up', 'Follow Up'), ('sample', 'Sample Work'), ('shipping', 'Shipping'), ('factory', 'Factory Work'), ('meeting', 'Meeting')], default='call', max_length=20),
        ),
        migrations.AlterField(
            model_name='event',
            name='lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.lead'),
        ),
        migrations.AlterField(
            model_name='event',
            name='opportunity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.opportunity'),
        ),
        migrations.AlterField(
            model_name='event',
            name='reminder_minutes_before',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_datetime',
            field=models.DateTimeField(),
        ),
    ]
