# Generated by Django 5.2.8 on 2025-11-27 19:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0022_remove_event_note_remove_event_production_stage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='reminder_minutes_before',
        ),
        migrations.RemoveField(
            model_name='event',
            name='short_note',
        ),
        migrations.AddField(
            model_name='event',
            name='note',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='ai_note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='event',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='crm.customer'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('call', 'Call'), ('follow_up', 'Follow up'), ('sample', 'Sample work'), ('shipping', 'Shipping'), ('factory', 'Factory work'), ('other', 'Other')], default='call', max_length=20),
        ),
        migrations.AlterField(
            model_name='event',
            name='lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='crm.lead'),
        ),
        migrations.AlterField(
            model_name='event',
            name='opportunity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='crm.opportunity'),
        ),
        migrations.AlterField(
            model_name='event',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=20),
        ),
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('planned', 'Planned'), ('in_progress', 'In progress'), ('done', 'Done')], default='planned', max_length=20),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
