# Generated by Django 5.2.8 on 2025-11-27 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0023_remove_event_reminder_minutes_before_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='assigned_to_email',
            field=models.EmailField(blank=True, help_text='Their email for alerts', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='assigned_to_name',
            field=models.CharField(blank=True, help_text='Person who will follow up', max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='production_stage',
            field=models.CharField(blank=True, choices=[('development', 'Development'), ('sampling', 'Sampling'), ('bulk_cutting', 'Bulk cutting'), ('sewing', 'Sewing'), ('finishing', 'Finishing'), ('packing', 'Packing'), ('shipped', 'Shipped')], max_length=40),
        ),
        migrations.AddField(
            model_name='event',
            name='reminder_minutes_before',
            field=models.PositiveIntegerField(blank=True, help_text='Minutes before to send reminder', null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='reminder_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('call', 'Call'), ('follow_up', 'Follow up'), ('sample', 'Sample work'), ('production', 'Production'), ('shipping', 'Shipping'), ('payment', 'Payment reminder'), ('other', 'Other')], default='call', max_length=50),
        ),
        migrations.AlterField(
            model_name='event',
            name='note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('planned', 'Planned'), ('in_work', 'In work'), ('done', 'Done')], default='planned', max_length=20),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
