# Generated by Django 5.2.8 on 2025-11-27 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0024_event_assigned_to_email_event_assigned_to_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='ai_note',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
