# Generated by Django 5.2.8 on 2025-11-28 23:50

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0025_alter_event_ai_note"),
    ]

    operations = [
        migrations.CreateModel(
            name="AIAgent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "category",
                    models.CharField(
                        max_length=30,
                        choices=[
                            ("lead", "Lead helper"),
                            ("opportunity", "Opportunity helper"),
                            ("customer", "Customer helper"),
                            ("general", "General"),
                        ],
                        default="lead",
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "system_prompt",
                    models.TextField(
                        blank=True,
                        help_text="Main instructions this AI agent should follow.",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),

        migrations.AlterModelOptions(
            name="event",
            options={"ordering": ["start_datetime", "title"]},
        ),

        # InventoryReorder extra fields
        migrations.AddField(
            model_name="inventoryreorder",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="inventoryreorder",
            name="inventory_item",
            field=models.ForeignKey(
                null=True,
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reorders",
                to="crm.inventoryitem",
            ),
        ),
        migrations.AddField(
            model_name="inventoryreorder",
            name="quantity",
            field=models.PositiveIntegerField(default=0),
        ),

        # ThreadOption extra fields
        migrations.AddField(
            model_name="threadoption",
            name="brand",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="threadoption",
            name="color",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="threadoption",
            name="count",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="threadoption",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="threadoption",
            name="image",
            field=models.ImageField(
                upload_to="thread_images/",
                blank=True,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="threadoption",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="threadoption",
            name="notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="threadoption",
            name="price_per_cone",
            field=models.DecimalField(
                max_digits=10,
                decimal_places=2,
                blank=True,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="threadoption",
            name="thread_type",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="threadoption",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="threadoption",
            name="use_for",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]