# Generated by Django 5.2.8 on 2025-11-28 23:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0026_aiagent_alter_event_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryreorder',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='inventoryreorder',
            name='inventory_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reorders', to='crm.inventoryitem'),
        ),
        migrations.AlterField(
            model_name='inventoryreorder',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
