# Generated by Django 5.2.8 on 2025-11-29 04:36

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0028_alter_event_options_alter_event_assigned_to_email_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aiagent',
            options={},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['start_datetime', 'title']},
        ),
        migrations.RemoveField(
            model_name='aiagent',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='aiagent',
            name='category',
            field=models.CharField(choices=[('sales', 'Sales and follow up'), ('summary', 'Summary and notes'), ('risk', 'Risk and mood'), ('product', 'Product and collection ideas'), ('general', 'General helper')], default='general', max_length=20),
        ),
        migrations.AlterField(
            model_name='aiagent',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='aiagent',
            name='system_prompt',
            field=models.TextField(help_text='System instructions for this AI agent.'),
        ),
        migrations.AlterField(
            model_name='event',
            name='assigned_to_email',
            field=models.EmailField(blank=True, help_text='Their email for alerts', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='assigned_to_name',
            field=models.CharField(blank=True, help_text='Person who will follow up', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='reminder_minutes_before',
            field=models.PositiveIntegerField(blank=True, help_text='Minutes before to send reminder', null=True),
        ),
        migrations.CreateModel(
            name='LeadAIMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(choices=[('user', 'User'), ('ai', 'AI')], max_length=10)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, max_length=120, null=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='crm.aiagent')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_messages', to='crm.lead')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
