# Generated by Django 5.2.8 on 2025-11-29 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0029_alter_aiagent_options_alter_event_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='threadoption',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
