# Generated by Django 5.2.8 on 2025-12-01 17:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0030_alter_threadoption_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_code', models.CharField(blank=True, max_length=50, unique=True)),
                ('order_type', models.CharField(choices=[('BD_FOB', 'Bangladesh FOB full service'), ('BD_SEW', 'Bangladesh sewing charge only'), ('CA_FULL', 'Canada full service door to door')], default='BD_FOB', max_length=20)),
                ('factory_location', models.CharField(blank=True, help_text='BD or CA or other', max_length=50)),
                ('style_name', models.CharField(blank=True, max_length=200)),
                ('style_ref', models.CharField(blank=True, max_length=100)),
                ('planned_qty', models.PositiveIntegerField(default=0)),
                ('finished_qty', models.PositiveIntegerField(default=0)),
                ('reject_qty', models.PositiveIntegerField(default=0)),
                ('sample_start_date', models.DateField(blank=True, null=True)),
                ('sample_target_days', models.PositiveIntegerField(default=21)),
                ('bulk_start_date', models.DateField(blank=True, null=True)),
                ('production_target_weeks_min', models.PositiveIntegerField(default=4)),
                ('production_target_weeks_max', models.PositiveIntegerField(default=8)),
                ('planned_ship_date', models.DateField(blank=True, null=True)),
                ('actual_ship_date', models.DateField(blank=True, null=True)),
                ('fabric_cost_tk', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('trims_cost_tk', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('sewing_cost_tk', models.DecimalField(blank=True, decimal_places=2, help_text='Main sewing charge total in TK', max_digits=12, null=True)),
                ('printing_cost_tk', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('embroidery_cost_tk', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('washing_cost_tk', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('packing_cost_tk', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('shipping_cost_tk', models.DecimalField(blank=True, decimal_places=2, help_text='Inside production job, in TK', max_digits=12, null=True)),
                ('misc_cost_tk', models.DecimalField(blank=True, decimal_places=2, help_text='Any extra cost, rent share, tea, taxi, small tools', max_digits=12, null=True)),
                ('notes', models.TextField(blank=True)),
                ('ai_summary', models.TextField(blank=True)),
                ('ai_risks', models.TextField(blank=True)),
                ('ai_next_steps', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_orders', to='crm.customer')),
                ('opportunity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_orders', to='crm.opportunity')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
