# Generated by Django 5.2.8 on 2025-12-01 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0031_productionorder"),
    ]

    operations = [
        # New table for production stages
        migrations.CreateModel(
            name="ProductionStage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("order", models.PositiveIntegerField(default=0)),
                ("color", models.CharField(max_length=20, default="#4caf50")),
            ],
            options={
                "ordering": ["order"],
            },
        ),

        # Rename old fields on ProductionOrder so they match the new model
        migrations.RenameField(
            model_name="productionorder",
            old_name="ai_next_steps",
            new_name="ai_note",
        ),
        migrations.RenameField(
            model_name="productionorder",
            old_name="actual_ship_date",
            new_name="bulk_target_date",
        ),
        migrations.RenameField(
            model_name="productionorder",
            old_name="embroidery_cost_tk",
            new_name="fabric_cost",
        ),
        migrations.RenameField(
            model_name="productionorder",
            old_name="fabric_cost_tk",
            new_name="misc_cost",
        ),
        migrations.RenameField(
            model_name="productionorder",
            old_name="finished_qty",
            new_name="reject_pieces",
        ),
        migrations.RenameField(
            model_name="productionorder",
            old_name="bulk_start_date",
            new_name="sample_target_date",
        ),
        migrations.RenameField(
            model_name="productionorder",
            old_name="packing_cost_tk",
            new_name="sewing_cost",
        ),
        migrations.RenameField(
            model_name="productionorder",
            old_name="planned_ship_date",
            new_name="ship_target_date",
        ),
        migrations.RenameField(
            model_name="productionorder",
            old_name="planned_qty",
            new_name="total_pieces",
        ),
        migrations.RenameField(
            model_name="productionorder",
            old_name="printing_cost_tk",
            new_name="trims_cost",
        ),

        # Remove old fields we no longer use
        migrations.RemoveField(model_name="productionorder", name="ai_risks"),
        migrations.RemoveField(model_name="productionorder", name="ai_summary"),
        migrations.RemoveField(model_name="productionorder", name="factory_location"),
        migrations.RemoveField(model_name="productionorder", name="misc_cost_tk"),
        migrations.RemoveField(model_name="productionorder", name="notes"),
        migrations.RemoveField(
            model_name="productionorder", name="production_target_weeks_max"
        ),
        migrations.RemoveField(
            model_name="productionorder", name="production_target_weeks_min"
        ),
        migrations.RemoveField(model_name="productionorder", name="reject_qty"),
        migrations.RemoveField(model_name="productionorder", name="sample_start_date"),
        migrations.RemoveField(model_name="productionorder", name="sample_target_days"),
        migrations.RemoveField(model_name="productionorder", name="sewing_cost_tk"),
        migrations.RemoveField(model_name="productionorder", name="shipping_cost_tk"),
        migrations.RemoveField(model_name="productionorder", name="style_ref"),
        migrations.RemoveField(model_name="productionorder", name="trims_cost_tk"),
        migrations.RemoveField(model_name="productionorder", name="updated_at"),
        migrations.RemoveField(model_name="productionorder", name="washing_cost_tk"),

        # New style image field
        migrations.AddField(
            model_name="productionorder",
            name="style_image",
            field=models.ImageField(
                upload_to="production_styles/", blank=True, null=True
            ),
        ),

        # Small tweaks to existing fields
        migrations.AlterField(
            model_name="productionorder",
            name="order_code",
            field=models.CharField(max_length=40, unique=True, blank=True),
        ),
        migrations.AlterField(
            model_name="productionorder",
            name="order_type",
            field=models.CharField(
                max_length=20,
                choices=[
                    ("bd_fob", "Bangladesh FOB full service"),
                    ("bd_sewing", "Bangladesh sewing charge"),
                    ("ca_full", "Canada door to door"),
                ],
                default="bd_fob",
            ),
        ),
        migrations.AlterField(
            model_name="productionorder",
            name="style_name",
            field=models.CharField(max_length=120, blank=True),
        ),

        # Link each production order to a current stage
        migrations.AddField(
            model_name="productionorder",
            name="current_stage",
            field=models.ForeignKey(
                to="crm.productionstage",
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="orders",
                null=True,
                blank=True,
            ),
        ),
    ]