# Generated by Django 5.2.8 on 2025-12-01 19:51

import django.db.models.deletion
from django.db import migrations, models
import django.utils.timezone

class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0032_productionstage_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aiagent',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='leadaimessage',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='productionstage',
            options={'ordering': ['order', 'planned_start', 'stage_key']},
        ),
        migrations.RenameField(
            model_name='productionorder',
            old_name='bulk_target_date',
            new_name='bulk_deadline',
        ),
        migrations.RenameField(
            model_name='productionorder',
            old_name='fabric_cost',
            new_name='cost_per_piece_tk',
        ),
        migrations.RenameField(
            model_name='productionorder',
            old_name='reject_pieces',
            new_name='qty_reject',
        ),
        migrations.RenameField(
            model_name='productionorder',
            old_name='total_pieces',
            new_name='qty_total',
        ),
        migrations.RenameField(
            model_name='productionorder',
            old_name='sample_target_date',
            new_name='sample_deadline',
        ),
        migrations.RemoveField(
            model_name='leadaimessage',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='leadaimessage',
            name='sender',
        ),
        migrations.RemoveField(
            model_name='productionorder',
            name='current_stage',
        ),
        migrations.RemoveField(
            model_name='productionorder',
            name='ship_target_date',
        ),
        migrations.RemoveField(
            model_name='productionorder',
            name='style_image',
        ),
        migrations.RemoveField(
            model_name='productionorder',
            name='style_name',
        ),
        migrations.RemoveField(
            model_name='productionstage',
            name='color',
        ),
        migrations.RemoveField(
            model_name='productionstage',
            name='name',
        ),
        migrations.AddField(
            model_name='aiagent',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='leadaimessage',
            name='message_type',
            field=models.CharField(choices=[('summary', 'Summary'), ('idea', 'Idea'), ('follow_up', 'Follow up'), ('note', 'Note')], default='summary', max_length=20),
        ),
        migrations.AddField(
            model_name='productionorder',
            name='bulk_lead_weeks_max',
            field=models.PositiveIntegerField(default=8),
        ),
        migrations.AddField(
            model_name='productionorder',
            name='bulk_lead_weeks_min',
            field=models.PositiveIntegerField(default=4),
        ),
        migrations.AddField(
            model_name='productionorder',
            name='fabric_used_kg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='productionorder',
            name='factory_location',
            field=models.CharField(choices=[('bd', 'Bangladesh'), ('ca', 'Canada')], default='bd', max_length=10),
        ),
        migrations.AddField(
            model_name='productionorder',
            name='lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_orders', to='crm.lead'),
        ),
        migrations.AddField(
            model_name='productionorder',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='productionorder',
            name='other_material_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='productionorder',
            name='overhead_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='productionorder',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_orders', to='crm.product'),
        ),
        migrations.AddField(
            model_name='productionorder',
            name='sample_lead_days',
            field=models.PositiveIntegerField(default=21),
        ),
        migrations.AddField(
            model_name='productionorder',
            name='status',
            field=models.CharField(choices=[('planning', 'Planning'), ('in_progress', 'In progress'), ('hold', 'On hold'), ('done', 'Done')], default='planning', max_length=20),
        ),
        migrations.AddField(
            model_name='productionorder',
            name='thread_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='productionorder',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='productionorder',
            name='total_cost_tk',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='productionorder',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='productionstage',
            name='actual_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productionstage',
            name='actual_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productionstage',
            name='ai_note',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='productionstage',
            name='color_tag',
            field=models.CharField(blank=True, help_text='CSS color name or code for stage card', max_length=20),
        ),
        migrations.AddField(
            model_name='productionstage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productionstage',
            name='display_name',
            field=models.CharField(blank=True, help_text='Optional nice label for this stage', max_length=50),
        ),
        migrations.AddField(
            model_name='productionstage',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='productionstage',
            name='planned_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productionstage',
            name='planned_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productionstage',
            name='stage_key',
            field=models.CharField(choices=[('development', 'Development'), ('sampling', 'Sampling'), ('cutting', 'Cutting'), ('sewing', 'Sewing'), ('ironing', 'Ironing'), ('qc', 'QC'), ('finishing', 'Finishing'), ('packing', 'Packing'), ('shipping', 'Shipping')], default='development', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productionstage',
            name='status',
            field=models.CharField(choices=[('planned', 'Planned'), ('in_progress', 'In progress'), ('hold', 'On hold'), ('done', 'Done'), ('delay', 'Delayed')], default='planned', max_length=20),
        ),
        migrations.AddField(
            model_name='productionstage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='aiagent',
            name='category',
            field=models.CharField(choices=[('lead', 'Lead helper'), ('opportunity', 'Opportunity helper'), ('customer', 'Customer helper'), ('production', 'Production helper'), ('general', 'General')], default='lead', max_length=30),
        ),
        migrations.AlterField(
            model_name='aiagent',
            name='system_prompt',
            field=models.TextField(blank=True, help_text='Main instructions this AI agent should follow.'),
        ),
        migrations.AlterField(
            model_name='productionorder',
            name='ai_note',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='productionorder',
            name='misc_cost',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Extra expense in taka', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='productionorder',
            name='order_code',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='productionorder',
            name='order_type',
            field=models.CharField(choices=[('fob', 'FOB full service BD'), ('sewing_charge', 'Sewing charge only'), ('canada_full', 'Canada door to door')], default='fob', max_length=20),
        ),
        migrations.AlterField(
            model_name='productionstage',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='crm.productionorder'),
        ),
    ]
