# Generated by Django 5.2.8 on 2025-12-02 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0033_alter_aiagent_options_alter_leadaimessage_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionorder',
            name='style_image',
            field=models.ImageField(blank=True, null=True, upload_to='production_styles/'),
        ),
        migrations.AlterField(
            model_name='productionorder',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
