# Generated by Django 5.2.8 on 2025-12-02 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0034_productionorder_style_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionorder',
            name='actual_cost_per_piece_bdt',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Actual cost per piece in taka', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='productionorder',
            name='actual_total_cost_bdt',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Production total cost plus remake cost in taka', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='productionorder',
            name='fabric_cost_per_kg_bdt',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Fabric cost in taka per kg', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='productionorder',
            name='fabric_leftover_kg',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Fabric left after production in kg', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='productionorder',
            name='fabric_received_kg',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='How much fabric was sent to the factory in kg', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='productionorder',
            name='fabric_required_kg',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='How much fabric should be needed for this order in kg', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='productionorder',
            name='fabric_total_cost_bdt',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total fabric cost in taka', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='productionorder',
            name='fabric_waste_kg',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Calculated waste in kg', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='productionorder',
            name='fabric_waste_percent',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Waste percent based on required fabric', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='productionorder',
            name='material_total_cost_bdt',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Fabric plus trims plus thread plus other material cost in taka', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='productionorder',
            name='production_total_cost_bdt',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Material cost plus sewing plus overhead plus misc in taka', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='productionorder',
            name='remake_cost_bdt',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Extra cost in taka for remake', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='productionorder',
            name='remake_qty',
            field=models.PositiveIntegerField(blank=True, help_text='How many pieces we remade at our cost', null=True),
        ),
        migrations.AddField(
            model_name='productionorder',
            name='remake_reason',
            field=models.CharField(blank=True, help_text='Short reason why remake was needed', max_length=255),
        ),
        migrations.AddField(
            model_name='productionorder',
            name='remake_required',
            field=models.BooleanField(default=False, help_text='Turn on if we had to remake at our own cost'),
        ),
    ]
