# Generated by Django 5.2.8 on 2025-12-03 04:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0035_productionorder_actual_cost_per_piece_bdt_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productionorder',
            options={},
        ),
        migrations.RemoveField(
            model_name='productionorder',
            name='bulk_lead_weeks_max',
        ),
        migrations.RemoveField(
            model_name='productionorder',
            name='bulk_lead_weeks_min',
        ),
        migrations.RemoveField(
            model_name='productionorder',
            name='cost_per_piece_tk',
        ),
        migrations.RemoveField(
            model_name='productionorder',
            name='misc_cost',
        ),
        migrations.RemoveField(
            model_name='productionorder',
            name='other_material_cost',
        ),
        migrations.RemoveField(
            model_name='productionorder',
            name='overhead_cost',
        ),
        migrations.RemoveField(
            model_name='productionorder',
            name='remake_reason',
        ),
        migrations.RemoveField(
            model_name='productionorder',
            name='sample_lead_days',
        ),
        migrations.RemoveField(
            model_name='productionorder',
            name='sewing_cost',
        ),
        migrations.RemoveField(
            model_name='productionorder',
            name='thread_cost',
        ),
        migrations.RemoveField(
            model_name='productionorder',
            name='total_cost_tk',
        ),
        migrations.RemoveField(
            model_name='productionorder',
            name='trims_cost',
        ),
        migrations.AddField(
            model_name='productionorder',
            name='material_accessories_cost_bdt',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='productionorder',
            name='material_label_cost_bdt',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='productionorder',
            name='material_other_cost_bdt',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='productionorder',
            name='material_thread_cost_bdt',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='productionorder',
            name='material_zipper_cost_bdt',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='productionorder',
            name='production_cutting_cost_bdt',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='productionorder',
            name='production_finishing_cost_bdt',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='productionorder',
            name='production_other_cost_bdt',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='productionorder',
            name='production_overhead_cost_bdt',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='productionorder',
            name='production_packing_cost_bdt',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='productionorder',
            name='production_sewing_cost_bdt',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='productionorder',
            name='actual_cost_per_piece_bdt',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='productionorder',
            name='actual_total_cost_bdt',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='productionorder',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.customer'),
        ),
        migrations.AlterField(
            model_name='productionorder',
            name='fabric_cost_per_kg_bdt',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='productionorder',
            name='fabric_leftover_kg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='productionorder',
            name='fabric_received_kg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='productionorder',
            name='fabric_required_kg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='productionorder',
            name='fabric_total_cost_bdt',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='productionorder',
            name='fabric_waste_kg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='productionorder',
            name='fabric_waste_percent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='productionorder',
            name='lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.lead'),
        ),
        migrations.AlterField(
            model_name='productionorder',
            name='material_total_cost_bdt',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='productionorder',
            name='opportunity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.opportunity'),
        ),
        migrations.AlterField(
            model_name='productionorder',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.product'),
        ),
        migrations.AlterField(
            model_name='productionorder',
            name='production_total_cost_bdt',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='productionorder',
            name='remake_cost_bdt',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='productionorder',
            name='remake_qty',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productionorder',
            name='remake_required',
            field=models.BooleanField(default=False),
        ),
    ]
