# Generated by Django 5.2.8 on 2025-12-05 23:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0037_alter_productionorder_options_opportunity_customer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opportunityfile',
            name='customer',
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opportunities', to='crm.customer'),
        ),
    ]
