# Generated by Django 5.2.8 on 2025-12-06 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0038_remove_opportunityfile_customer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionorder',
            name='accessories_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='productionorder',
            name='color_info',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='productionorder',
            name='extra_order_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='productionorder',
            name='packaging_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='productionorder',
            name='size_ratio_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='productionorder',
            name='style_name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
