# Generated by Django 5.2.8 on 2025-12-07 20:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0039_productionorder_accessories_note_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionOrderAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='production_attachments/')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='crm.productionorder')),
            ],
        ),
    ]
