# Generated by Django 5.2.8 on 2025-12-07 23:20

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0040_productionorderattachment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=50, unique=True)),
                ('issue_date', models.DateField(default=django.utils.timezone.now)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('currency', models.CharField(choices=[('USD', 'USD'), ('CAD', 'CAD'), ('BDT', 'BDT')], default='USD', max_length=10)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('shipping_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent to client'), ('partial', 'Partly paid'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.customer')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='crm.productionorder')),
            ],
            options={
                'ordering': ['-issue_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carrier', models.CharField(choices=[('fedex', 'FedEx'), ('dhl', 'DHL'), ('ups', 'UPS'), ('other', 'Other')], default='dhl', max_length=20)),
                ('tracking_number', models.CharField(blank=True, max_length=100)),
                ('ship_date', models.DateField(blank=True, null=True)),
                ('shipment_type', models.CharField(choices=[('sample', 'Sample'), ('bulk', 'Bulk'), ('remake', 'Remake')], default='bulk', max_length=20)),
                ('box_count', models.PositiveIntegerField(blank=True, null=True)),
                ('total_weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cost_bdt', models.DecimalField(blank=True, decimal_places=2, help_text='Bangladesh team enters cost in taka', max_digits=14, null=True)),
                ('rate_bdt_per_usd', models.DecimalField(decimal_places=4, default=Decimal('120.00'), help_text='How many taka per one dollar', max_digits=10)),
                ('cost_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('booked', 'Booked'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='planned', max_length=20)),
                ('last_tracking_status', models.CharField(blank=True, max_length=200)),
                ('last_tracking_check', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipments', to='crm.customer')),
                ('opportunity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipments', to='crm.opportunity')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shipments', to='crm.productionorder')),
            ],
            options={
                'ordering': ['-ship_date', '-created_at'],
            },
        ),
    ]
