# Generated by Django 5.2.8 on 2025-12-08 06:24

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0041_invoice_shipment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shipment',
            old_name='cost_usd',
            new_name='cost_cad',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='rate_bdt_per_usd',
        ),
        migrations.AddField(
            model_name='shipment',
            name='rate_bdt_per_cad',
            field=models.DecimalField(decimal_places=4, default=Decimal('90.00'), help_text='How many taka for one Canadian dollar', max_digits=10),
        ),
    ]
