# Generated by Django 5.2.8 on 2025-12-09 23:03

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0042_rename_cost_usd_shipment_cost_cad_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountingEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('side', models.CharField(choices=[('BD', 'Bangladesh'), ('CA', 'Canada')], max_length=2)),
                ('direction', models.CharField(choices=[('IN', 'Money in'), ('OUT', 'Money out')], max_length=3)),
                ('main_type', models.CharField(choices=[('INCOME', 'Income'), ('COGS', 'Cost of goods'), ('EXPENSE', 'Expense'), ('TRANSFER', 'Transfer'), ('TAX', 'Tax'), ('OTHER', 'Other')], default='OTHER', max_length=10)),
                ('sub_type', models.CharField(blank=True, help_text='Short label like fabric, trims, salary, rent, courier, client payment', max_length=100)),
                ('currency', models.CharField(choices=[('BDT', 'Bangladesh taka'), ('CAD', 'Canadian dollar'), ('USD', 'United States dollar')], default='CAD', max_length=3)),
                ('amount_original', models.DecimalField(decimal_places=2, help_text='Amount in original currency', max_digits=14)),
                ('rate_to_cad', models.DecimalField(blank=True, decimal_places=4, help_text='One unit of this currency in CAD', max_digits=14, null=True)),
                ('rate_to_bdt', models.DecimalField(blank=True, decimal_places=4, help_text='One unit of this currency in BDT', max_digits=14, null=True)),
                ('amount_cad', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('amount_bdt', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('description', models.TextField(blank=True)),
                ('note_internal', models.TextField(blank=True, help_text='Internal note like bank ref, cash note, who approved')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_accounting_entries', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accounting_entries', to='crm.customer')),
                ('opportunity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accounting_entries', to='crm.opportunity')),
                ('production_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accounting_entries', to='crm.productionorder')),
                ('shipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accounting_entries', to='crm.shipment')),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
    ]
