# Generated by Django 5.2.8 on 2025-12-10 05:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0043_accountingentry'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeBD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('role_title', models.CharField(blank=True, help_text='Position like operator, helper, cutting master, merchandiser', max_length=120)),
                ('base_salary_bdt', models.DecimalField(decimal_places=2, help_text='Monthly salary in BDT', max_digits=12)),
                ('overtime_rate_bdt_per_hour', models.DecimalField(decimal_places=2, default=0, help_text='Overtime pay per hour in BDT', max_digits=10)),
                ('start_date', models.DateField(blank=True, help_text='When this person started working', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck when the employee leaves the factory')),
                ('notes', models.TextField(blank=True, help_text='Extra info like department, skill, or comments')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_bd_employees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
