# Generated by Django 5.2.8 on 2025-12-10 06:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0044_employeebd'),
    ]

    operations = [
        migrations.CreateModel(
            name='BDStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('role', models.CharField(blank=True, help_text='Example operator, helper, cutting master, merchandiser', max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('base_salary_bdt', models.DecimalField(decimal_places=2, default=0, help_text='Monthly base salary in BDT', max_digits=12)),
                ('join_date', models.DateField(blank=True, null=True)),
                ('note', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BDStaffMonth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('base_salary_bdt', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('overtime_hours', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('overtime_rate_bdt', models.DecimalField(decimal_places=2, default=0, help_text='Extra pay per overtime hour', max_digits=10)),
                ('overtime_total_bdt', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('bonus_bdt', models.DecimalField(decimal_places=2, default=0, help_text='Any extra bonus for this month', max_digits=12)),
                ('deduction_bdt', models.DecimalField(decimal_places=2, default=0, help_text='Any deduction like late or leave', max_digits=12)),
                ('final_pay_bdt', models.DecimalField(decimal_places=2, default=0, help_text='What we really pay for this month', max_digits=12)),
                ('is_paid', models.BooleanField(default=False)),
                ('paid_date', models.DateField(blank=True, null=True)),
                ('note', models.TextField(blank=True)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='month_rows', to='crm.bdstaff')),
            ],
            options={
                'ordering': ['-year', '-month', 'staff__name'],
                'unique_together': {('staff', 'year', 'month')},
            },
        ),
    ]
