# Generated by Django 5.2.8 on 2025-12-11 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0045_bdstaff_bdstaffmonth'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountingentry',
            name='status',
            field=models.CharField(choices=[('PLANNED', 'Planned'), ('DUE', 'Due'), ('PARTIAL', 'Part paid'), ('PAID', 'Paid')], default='PLANNED', help_text='Planned, due, part paid or fully paid', max_length=10),
        ),
    ]
