# Generated by Django 5.2.8 on 2025-12-12 22:38

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0046_accountingentry_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountingentry',
            name='linked_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_entries', to='crm.accountingentry'),
        ),
        migrations.AlterField(
            model_name='accountingentry',
            name='date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.DeleteModel(
            name='EmployeeBD',
        ),
    ]
