# Generated by Django 5.2.8 on 2025-12-13 19:48

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0047_accountingentry_linked_entry_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cad_to_bdt', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=14)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
