# Generated by Django 5.2.8 on 2025-12-13 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0048_exchangerate'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoneyTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_cad', models.DecimalField(decimal_places=2, max_digits=12)),
                ('amount_bdt', models.DecimalField(decimal_places=2, max_digits=12)),
                ('receiver_name', models.CharField(max_length=120)),
                ('note', models.TextField(blank=True)),
                ('sent_method', models.CharField(choices=[('bank', 'Bank'), ('app', 'Online App'), ('cash', 'Cash')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
