# Generated by Django 5.2.8 on 2025-12-13 21:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0049_moneytransfer'),
    ]

    operations = [
        migrations.AddField(
            model_name='moneytransfer',
            name='bd_entry',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='money_transfer', to='crm.accountingentry'),
        ),
    ]
