# Generated by Django 5.2.8 on 2025-12-14 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0050_moneytransfer_bd_entry'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accountingentry',
            old_name='note_internal',
            new_name='internal_note',
        ),
        migrations.AddField(
            model_name='accountingentry',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='accounting_attachments/'),
        ),
        migrations.AddField(
            model_name='accountingentry',
            name='transfer_ref',
            field=models.CharField(blank=True, help_text='Same id for both CA and BD transfer entries', max_length=64),
        ),
    ]
