# Generated by Django 5.2.8 on 2025-12-14 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0051_rename_note_internal_accountingentry_internal_note_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountingentry',
            name='amount_original',
            field=models.DecimalField(decimal_places=2, max_digits=14),
        ),
        migrations.AlterField(
            model_name='accountingentry',
            name='internal_note',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='accountingentry',
            name='rate_to_bdt',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='accountingentry',
            name='rate_to_cad',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='accountingentry',
            name='status',
            field=models.CharField(choices=[('PLANNED', 'Planned'), ('DUE', 'Due'), ('PARTIAL', 'Part paid'), ('PAID', 'Paid')], default='PLANNED', max_length=10),
        ),
        migrations.AlterField(
            model_name='accountingentry',
            name='sub_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='accountingentry',
            name='transfer_ref',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
