# Generated by Django 5.2.8 on 2025-12-15 01:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0052_alter_accountingentry_amount_original_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountingAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='accounting_attachments/')),
                ('title', models.CharField(blank=True, max_length=120)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='crm.accountingentry')),
            ],
            options={
                'ordering': ['-uploaded_at', '-id'],
            },
        ),
    ]
