# Generated by Django 5.2.8 on 2025-12-15 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0053_accountingattachment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountingentry',
            name='attachment',
        ),
    ]
