# Generated by Django 5.2.8 on 2025-12-15 22:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0055_remove_accountingattachment_title_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountingMonthClose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('side', models.CharField(choices=[('CA', 'Canada'), ('BD', 'Bangladesh'), ('ALL', 'All')], default='ALL', max_length=3)),
                ('is_closed', models.BooleanField(default=True)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('closed_at', models.DateTimeField(auto_now_add=True)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Accounting Month Close',
                'verbose_name_plural': 'Accounting Month Closes',
                'unique_together': {('year', 'month', 'side')},
            },
        ),
    ]
