# Generated by Django 5.2.8 on 2025-12-16 00:06

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0057_accountingauditlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accountingauditlog',
            options={'ordering': ['-created_at', '-id']},
        ),
        migrations.AlterField(
            model_name='accountingauditlog',
            name='entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='system_audit_logs', related_query_name='system_audit_log', to='crm.accountingentry'),
        ),
        migrations.CreateModel(
            name='AccountingEntryAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('FILES', 'Files')], max_length=10)),
                ('changed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('before_data', models.JSONField(blank=True, null=True)),
                ('after_data', models.JSONField(blank=True, null=True)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('ip_address', models.CharField(blank=True, default='', max_length=64)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entry_audits', related_query_name='entry_audit', to='crm.accountingentry')),
            ],
            options={
                'ordering': ['-changed_at', '-id'],
            },
        ),
    ]
