# Generated by Django 5.2.8 on 2025-12-16 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0058_alter_accountingauditlog_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AccountingAuditLog',
        ),
    ]
