# Generated by Django 5.2.8 on 2025-12-16 19:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0059_delete_accountingauditlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accountingentryaudit',
            options={'ordering': ['-changed_at']},
        ),
        migrations.RemoveField(
            model_name='accountingentryaudit',
            name='ip_address',
        ),
        migrations.AddField(
            model_name='accountingentryaudit',
            name='entry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='accountingentryaudit',
            name='entry_pk',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='accountingentryaudit',
            name='action',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='accountingentryaudit',
            name='changed_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='accountingentryaudit',
            name='changed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accounting_audits', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='accountingentryaudit',
            name='entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entry_audits', to='crm.accountingentry'),
        ),
    ]
