# Generated by Django 5.2.8 on 2025-12-16 21:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0060_alter_accountingentryaudit_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountingentry',
            name='currency',
            field=models.CharField(choices=[('BDT', 'Bangladesh taka'), ('CAD', 'Canadian dollar'), ('USD', 'United States dollar')], db_index=True, default='CAD', max_length=3),
        ),
        migrations.AlterField(
            model_name='accountingentry',
            name='date',
            field=models.DateField(db_index=True, default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name='accountingentry',
            name='direction',
            field=models.CharField(choices=[('IN', 'Money in'), ('OUT', 'Money out')], db_index=True, max_length=3),
        ),
        migrations.AlterField(
            model_name='accountingentry',
            name='main_type',
            field=models.CharField(choices=[('INCOME', 'Income'), ('COGS', 'Cost of goods'), ('EXPENSE', 'Expense'), ('TRANSFER', 'Transfer'), ('TAX', 'Tax'), ('OTHER', 'Other')], db_index=True, default='OTHER', max_length=10),
        ),
        migrations.AlterField(
            model_name='accountingentry',
            name='side',
            field=models.CharField(choices=[('BD', 'Bangladesh'), ('CA', 'Canada')], db_index=True, max_length=2),
        ),
        migrations.AlterField(
            model_name='accountingentry',
            name='status',
            field=models.CharField(choices=[('PLANNED', 'Planned'), ('DUE', 'Due'), ('PARTIAL', 'Part paid'), ('PAID', 'Paid')], db_index=True, default='PLANNED', max_length=10),
        ),
        migrations.AlterField(
            model_name='accountingentry',
            name='transfer_ref',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
    ]
