# Generated by Django 6.0 on 2025-12-23 05:02

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0061_alter_accountingentry_currency_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accountingentry',
            options={},
        ),
        migrations.AlterModelOptions(
            name='accountingentryaudit',
            options={'ordering': ['-changed_at', '-id']},
        ),
        migrations.RemoveField(
            model_name='accountingentry',
            name='transfer_ref',
        ),
        migrations.RemoveField(
            model_name='accountingentryaudit',
            name='entry_date',
        ),
        migrations.RemoveField(
            model_name='accountingentryaudit',
            name='entry_pk',
        ),
        migrations.AlterField(
            model_name='accountingattachment',
            name='original_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='accountingattachment',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accounting_attachments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='accountingentry',
            name='amount_bdt',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14),
        ),
        migrations.AlterField(
            model_name='accountingentry',
            name='amount_cad',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14),
        ),
        migrations.AlterField(
            model_name='accountingentry',
            name='amount_original',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14),
        ),
        migrations.AlterField(
            model_name='accountingentry',
            name='currency',
            field=models.CharField(default='CAD', max_length=3),
        ),
        migrations.AlterField(
            model_name='accountingentry',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='accountingentry',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='accountingentry',
            name='direction',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='accountingentry',
            name='internal_note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='accountingentry',
            name='linked_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_children', to='crm.accountingentry'),
        ),
        migrations.AlterField(
            model_name='accountingentry',
            name='main_type',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='accountingentry',
            name='rate_to_bdt',
            field=models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=14),
        ),
        migrations.AlterField(
            model_name='accountingentry',
            name='rate_to_cad',
            field=models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=14),
        ),
        migrations.AlterField(
            model_name='accountingentry',
            name='side',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='accountingentry',
            name='status',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='accountingentry',
            name='sub_type',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AlterField(
            model_name='accountingentryaudit',
            name='action',
            field=models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('FILES', 'Files')], max_length=10),
        ),
        migrations.AlterField(
            model_name='accountingentryaudit',
            name='changed_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='accountingentryaudit',
            name='changed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accounting_entry_audits', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='accountingentryaudit',
            name='entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entry_audits', related_query_name='entry_audit', to='crm.accountingentry'),
        ),
    ]
