# Generated by Django 6.0 on 2025-12-25 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0063_accountingmonthlock'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountingentry',
            name='transfer_ref',
            field=models.CharField(blank=True, db_index=True, default='', max_length=50),
        ),
    ]
