# Generated by Django 6.0 on 2025-12-26 22:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0064_accountingentry_transfer_ref'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountingattachment',
            name='file',
            field=models.FileField(upload_to='accounting/'),
        ),
        migrations.AlterField(
            model_name='accountingattachment',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='AccountingDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('side', models.CharField(choices=[('CA', 'CA'), ('BD', 'BD')], default='CA', max_length=2)),
                ('doc_type', models.CharField(choices=[('INVOICE', 'Invoice'), ('RECEIPT', 'Receipt'), ('BILL', 'Bill'), ('OTHER', 'Other')], default='INVOICE', max_length=20)),
                ('title', models.CharField(blank=True, default='', max_length=200)),
                ('vendor', models.CharField(blank=True, default='', max_length=200)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('doc_date', models.DateField(blank=True, null=True)),
                ('file', models.FileField(upload_to='accounting_docs/')),
                ('original_name', models.CharField(blank=True, default='', max_length=255)),
                ('note', models.TextField(blank=True, default='')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('linked_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='crm.accountingentry')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at', '-id'],
            },
        ),
    ]
