# Generated by Django 6.0 on 2025-12-29 00:24

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0065_alter_accountingattachment_file_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountingMonthlyTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('side', models.CharField(choices=[('BD', 'Bangladesh'), ('CA', 'Canada')], default='BD', max_length=2)),
                ('year', models.PositiveIntegerField()),
                ('month', models.PositiveIntegerField()),
                ('target_bdt', models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=14)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monthly_targets_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-year', '-month', 'side'),
                'unique_together': {('side', 'year', 'month')},
            },
        ),
    ]
