# Generated by Django 5.2.8 on 2025-12-30 06:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0068_aihealthcheck_bdmonthlytarget'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIHealthIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('details', models.TextField(blank=True)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('critical', 'Critical')], default='info', max_length=10)),
                ('source', models.CharField(blank=True, max_length=80)),
                ('is_resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_health_issues', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'crm_aihealthcheck',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='AIHealthRunCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('ok', 'OK'), ('warn', 'Warning'), ('bad', 'Bad')], default='ok', max_length=10)),
                ('detail', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_health_run_checks', to=settings.AUTH_USER_MODEL)),
                ('run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='checks', to='crm.aihealthrun')),
            ],
            options={
                'db_table': 'crm_aihealthruncheck',
                'ordering': ('id',),
            },
        ),
        migrations.DeleteModel(
            name='AIHealthCheck',
        ),
    ]
