# Generated by Django 5.2.8 on 2025-12-30 06:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0069_aihealthissue_aihealthruncheck_delete_aihealthcheck'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aihealthruncheck',
            name='run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checks', to='crm.aihealthrun'),
        ),
    ]
