# Generated by Django 5.2.8 on 2025-12-30 07:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0070_alter_aihealthruncheck_run'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aihealthruncheck',
            options={'ordering': ('-created_at',)},
        ),
        migrations.CreateModel(
            name='AISystemLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('feature', models.CharField(default='unknown', max_length=80)),
                ('provider', models.CharField(default='openai', max_length=40)),
                ('model_name', models.CharField(blank=True, default='', max_length=80)),
                ('level', models.CharField(choices=[('info', 'Info'), ('warn', 'Warning'), ('error', 'Error')], default='info', max_length=10)),
                ('message', models.CharField(blank=True, default='', max_length=255)),
                ('error_type', models.CharField(blank=True, default='', max_length=120)),
                ('error_detail', models.TextField(blank=True, default='')),
                ('latency_ms', models.IntegerField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_system_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
