# Generated by Django 5.2.8 on 2025-12-30 07:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0071_alter_aihealthruncheck_options_aisystemlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('area', models.CharField(default='crm', max_length=50)),
                ('action', models.CharField(default='view', max_length=50)),
                ('level', models.CharField(choices=[('info', 'Info'), ('warn', 'Warn'), ('error', 'Error')], default='info', max_length=10)),
                ('path', models.CharField(blank=True, default='', max_length=255)),
                ('method', models.CharField(blank=True, default='', max_length=10)),
                ('model_label', models.CharField(blank=True, default='', max_length=80)),
                ('object_id', models.CharField(blank=True, default='', max_length=64)),
                ('message', models.CharField(blank=True, default='', max_length=255)),
                ('meta_json', models.TextField(blank=True, default='')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='system_activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
