# Generated by Django 5.2.8 on 2025-12-31 03:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0072_systemactivitylog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='aihealthissue',
            name='details',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='aihealthissue',
            name='source',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AlterField(
            model_name='aisystemlog',
            name='feature',
            field=models.CharField(db_index=True, default='unknown', max_length=80),
        ),
        migrations.AlterField(
            model_name='aisystemlog',
            name='level',
            field=models.CharField(choices=[('info', 'Info'), ('warn', 'Warning'), ('error', 'Error')], db_index=True, default='info', max_length=10),
        ),
        migrations.AlterField(
            model_name='aisystemlog',
            name='provider',
            field=models.CharField(choices=[('openai', 'OpenAI'), ('anthropic', 'Anthropic'), ('local', 'Local')], db_index=True, default='openai', max_length=40),
        ),
        migrations.AddIndex(
            model_name='aisystemlog',
            index=models.Index(fields=['provider', 'level'], name='crm_aisyste_provide_05a970_idx'),
        ),
        migrations.AddIndex(
            model_name='aisystemlog',
            index=models.Index(fields=['created_at'], name='crm_aisyste_created_6fd11a_idx'),
        ),
        migrations.AlterModelTable(
            name='aihealthissue',
            table='crm_aihealthissue',
        ),
    ]
