# Generated by Django 5.2.8 on 2025-12-31 19:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0074_whatsappthread_whatsappmessage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappthread',
            name='ai_draft',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='whatsappthread',
            name='ai_sent',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='whatsappthread',
            name='last_auto_reply_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='whatsappthread',
            name='needs_human',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddIndex(
            model_name='whatsappmessage',
            index=models.Index(fields=['thread', 'created_at'], name='crm_whatsap_thread__f07801_idx'),
        ),
        migrations.AddIndex(
            model_name='whatsappmessage',
            index=models.Index(fields=['meta_id'], name='crm_whatsap_meta_id_7f2da5_idx'),
        ),
        migrations.AddIndex(
            model_name='whatsappthread',
            index=models.Index(fields=['wa_phone'], name='crm_whatsap_wa_phon_bed0b4_idx'),
        ),
        migrations.AddIndex(
            model_name='whatsappthread',
            index=models.Index(fields=['needs_human', 'ai_sent'], name='crm_whatsap_needs_h_5a6e9f_idx'),
        ),
        migrations.AddIndex(
            model_name='whatsappthread',
            index=models.Index(fields=['last_message_at'], name='crm_whatsap_last_me_8797aa_idx'),
        ),
    ]
