# Generated by Django 5.2.8 on 2025-12-31 23:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0075_whatsappthread_ai_draft_whatsappthread_ai_sent_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='whatsappmessage',
            name='crm_whatsap_thread__f07801_idx',
        ),
        migrations.RemoveIndex(
            model_name='whatsappmessage',
            name='crm_whatsap_meta_id_7f2da5_idx',
        ),
        migrations.RemoveIndex(
            model_name='whatsappthread',
            name='crm_whatsap_wa_phon_bed0b4_idx',
        ),
        migrations.RemoveIndex(
            model_name='whatsappthread',
            name='crm_whatsap_needs_h_5a6e9f_idx',
        ),
        migrations.RemoveIndex(
            model_name='whatsappthread',
            name='crm_whatsap_last_me_8797aa_idx',
        ),
        migrations.RemoveField(
            model_name='whatsappthread',
            name='ai_sent',
        ),
        migrations.RemoveField(
            model_name='whatsappthread',
            name='last_auto_reply_at',
        ),
        migrations.AddField(
            model_name='whatsappthread',
            name='ai_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='whatsappthread',
            name='lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wa_threads', to='crm.lead'),
        ),
        migrations.AlterField(
            model_name='whatsappthread',
            name='needs_human',
            field=models.BooleanField(default=False),
        ),
    ]
