# Generated by Django 5.2.8 on 2026-01-01 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0076_remove_whatsappmessage_crm_whatsap_thread__f07801_idx_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='whatsappthread',
            index=models.Index(fields=['wa_phone'], name='crm_whatsap_wa_phon_bed0b4_idx'),
        ),
        migrations.AddIndex(
            model_name='whatsappthread',
            index=models.Index(fields=['last_message_at'], name='crm_whatsap_last_me_8797aa_idx'),
        ),
        migrations.AddIndex(
            model_name='whatsappthread',
            index=models.Index(fields=['needs_human', 'ai_enabled'], name='crm_whatsap_needs_h_2e73eb_idx'),
        ),
    ]
