# Generated by Django 5.2.8 on 2026-01-02 05:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0077_whatsappthread_crm_whatsap_wa_phon_bed0b4_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappthread',
            name='last_auto_reply_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='whatsappmessage',
            constraint=models.UniqueConstraint(fields=('thread', 'meta_id'), name='uniq_wa_thread_meta_id'),
        ),
    ]
