# Generated by Django 5.2.8 on 2026-01-02 07:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0078_whatsappthread_last_auto_reply_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailThread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(db_index=True, max_length=30)),
                ('mailbox', models.CharField(blank=True, default='', max_length=150)),
                ('subject', models.CharField(blank=True, default='', max_length=255)),
                ('from_email', models.CharField(blank=True, default='', max_length=255)),
                ('from_name', models.CharField(blank=True, default='', max_length=255)),
                ('last_message_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-last_message_at', '-id'),
                'indexes': [models.Index(fields=['label'], name='crm_emailth_label_5b35fe_idx'), models.Index(fields=['last_message_at'], name='crm_emailth_last_me_b05071_idx')],
            },
        ),
        migrations.CreateModel(
            name='EmailMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imap_uid', models.CharField(db_index=True, max_length=80)),
                ('subject', models.CharField(blank=True, default='', max_length=255)),
                ('from_email', models.CharField(blank=True, default='', max_length=255)),
                ('from_name', models.CharField(blank=True, default='', max_length=255)),
                ('to_email', models.CharField(blank=True, default='', max_length=255)),
                ('body_text', models.TextField(blank=True, default='')),
                ('body_html', models.TextField(blank=True, default='')),
                ('is_form_entry', models.BooleanField(default=False)),
                ('is_lead_candidate', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='crm.emailthread')),
            ],
            options={
                'ordering': ('id',),
                'constraints': [models.UniqueConstraint(fields=('thread', 'imap_uid'), name='uniq_email_thread_uid')],
            },
        ),
    ]
