# Generated by Django 5.2.8 on 2026-01-02 08:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0079_emailthread_emailmessage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='emailmessage',
            name='form_entry_no',
            field=models.CharField(blank=True, db_index=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='emailmessage',
            name='is_important',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='emailmessage',
            name='lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_messages', to='crm.lead'),
        ),
        migrations.AddField(
            model_name='emailthread',
            name='lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_threads', to='crm.lead'),
        ),
        migrations.AddIndex(
            model_name='emailmessage',
            index=models.Index(fields=['is_lead_candidate', 'is_form_entry'], name='crm_emailme_is_lead_d4ad15_idx'),
        ),
        migrations.AddIndex(
            model_name='emailmessage',
            index=models.Index(fields=['form_entry_no'], name='crm_emailme_form_en_ef6a78_idx'),
        ),
        migrations.AddIndex(
            model_name='emailmessage',
            index=models.Index(fields=['is_important'], name='crm_emailme_is_impo_817e47_idx'),
        ),
        migrations.AddIndex(
            model_name='emailmessage',
            index=models.Index(fields=['lead'], name='crm_emailme_lead_id_329b14_idx'),
        ),
        migrations.AddIndex(
            model_name='emailthread',
            index=models.Index(fields=['lead'], name='crm_emailth_lead_id_be2e14_idx'),
        ),
    ]
