# Generated by Django 5.2.8 on 2026-01-02 18:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0080_emailmessage_form_entry_no_emailmessage_is_important_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OutboundEmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_email', models.CharField(blank=True, default='', max_length=255)),
                ('subject', models.CharField(blank=True, default='', max_length=255)),
                ('body', models.TextField(blank=True, default='')),
                ('message_type', models.CharField(blank=True, default='', max_length=40)),
                ('sent_ok', models.BooleanField(default=False)),
                ('error', models.CharField(blank=True, default='', max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outbound_emails', to='crm.lead')),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['message_type'], name='crm_outboun_message_2c3adb_idx'), models.Index(fields=['sent_ok'], name='crm_outboun_sent_ok_1e0a25_idx'), models.Index(fields=['created_at'], name='crm_outboun_created_95dcd8_idx')],
            },
        ),
    ]
