# Generated by Django 5.2.8 on 2026-01-02 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0081_outboundemaillog'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailInboxConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(choices=[('lead', 'Lead inbox'), ('info', 'Info inbox')], max_length=30, unique=True)),
                ('imap_host', models.CharField(blank=True, default='imap.gmail.com', max_length=120)),
                ('imap_port', models.IntegerField(default=993)),
                ('username', models.CharField(blank=True, default='', max_length=150)),
                ('password', models.CharField(blank=True, default='', max_length=150)),
                ('use_ssl', models.BooleanField(default=True)),
                ('is_enabled', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('label',),
            },
        ),
        migrations.AlterModelOptions(
            name='aisystemlog',
            options={'managed': False, 'ordering': ('-created_at',)},
        ),
    ]
