# Generated by Django 5.2.8 on 2026-01-03 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0082_emailinboxconfig_alter_aisystemlog_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='aisystemlog',
            table='crm_aisystemlog',
        ),
    ]
