# Generated by Django 5.2.8 on 2026-01-09 23:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0083_alter_aisystemlog_table'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aihealthruncheck',
            options={'ordering': ('id',)},
        ),
        migrations.RemoveField(
            model_name='aihealthruncheck',
            name='created_by',
        ),
        migrations.AlterField(
            model_name='aihealthruncheck',
            name='name',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='aihealthruncheck',
            name='status',
            field=models.CharField(default='ok', max_length=20),
        ),
        migrations.AlterModelTable(
            name='aihealthruncheck',
            table='crm_aihealthcheck',
        ),
        migrations.CreateModel(
            name='UserAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_leads', models.BooleanField(default=True)),
                ('can_opportunities', models.BooleanField(default=True)),
                ('can_customers', models.BooleanField(default=True)),
                ('can_inventory', models.BooleanField(default=True)),
                ('can_production', models.BooleanField(default=True)),
                ('can_shipping', models.BooleanField(default=True)),
                ('can_ai', models.BooleanField(default=True)),
                ('can_calendar', models.BooleanField(default=True)),
                ('can_accounting_bd', models.BooleanField(default=True)),
                ('can_accounting_ca', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
