# Generated by Django 6.0 on 2026-01-13 04:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0084_alter_aihealthruncheck_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='useraccess',
            options={'verbose_name': 'User Access', 'verbose_name_plural': 'User Access'},
        ),
        migrations.AddField(
            model_name='useraccess',
            name='role',
            field=models.CharField(choices=[('CA', 'CA Team'), ('BD', 'BD Team')], default='BD', max_length=2),
        ),
        migrations.AlterField(
            model_name='useraccess',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='access', to=settings.AUTH_USER_MODEL),
        ),
    ]
