# Generated by Django 5.2.8 on 2026-01-19 19:08

import django.utils.timezone
from django.db import migrations, models


def ensure_useraccess_table_and_column(apps, schema_editor):
    """
    Fix for sqlite where crm_useraccess table is missing.
    Safe to run on AWS too because we use IF NOT EXISTS and column checks.
    """
    connection = schema_editor.connection

    with connection.cursor() as cursor:
        # 1) Create table if missing
        cursor.execute(
            """
            CREATE TABLE IF NOT EXISTS crm_useraccess (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                role VARCHAR(2) NOT NULL DEFAULT 'BD',

                can_leads BOOLEAN NOT NULL DEFAULT 1,
                can_opportunities BOOLEAN NOT NULL DEFAULT 1,
                can_customers BOOLEAN NOT NULL DEFAULT 1,
                can_inventory BOOLEAN NOT NULL DEFAULT 1,
                can_production BOOLEAN NOT NULL DEFAULT 1,
                can_shipping BOOLEAN NOT NULL DEFAULT 1,
                can_ai BOOLEAN NOT NULL DEFAULT 1,
                can_calendar BOOLEAN NOT NULL DEFAULT 1,

                can_accounting_bd BOOLEAN NOT NULL DEFAULT 1,
                can_accounting_ca BOOLEAN NOT NULL DEFAULT 0,
                can_library BOOLEAN NOT NULL DEFAULT 0,

                updated_at DATETIME NOT NULL,
                user_id INTEGER NOT NULL UNIQUE
            )
            """
        )

        # 2) Ensure can_library column exists (for older tables)
        cursor.execute("PRAGMA table_info(crm_useraccess)")
        cols = [row[1] for row in cursor.fetchall()]
        if "can_library" not in cols:
            cursor.execute(
                "ALTER TABLE crm_useraccess ADD COLUMN can_library BOOLEAN NOT NULL DEFAULT 0"
            )

        # 3) Ensure updated_at exists (if table was created in a broken state before)
        cursor.execute("PRAGMA table_info(crm_useraccess)")
        cols2 = [row[1] for row in cursor.fetchall()]
        if "updated_at" not in cols2:
            cursor.execute(
                "ALTER TABLE crm_useraccess ADD COLUMN updated_at DATETIME NOT NULL DEFAULT '2000-01-01 00:00:00'"
            )


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0085_alter_useraccess_options_useraccess_role_and_more"),
    ]

    operations = [
        migrations.RunPython(ensure_useraccess_table_and_column, migrations.RunPython.noop),

        # Do NOT keep AddField here, because it crashes if the table is missing.
        # The RunPython above already ensures can_library exists.

        migrations.AlterField(
            model_name="accountingentry",
            name="direction",
            field=models.CharField(
                choices=[("IN", "In"), ("OUT", "Out")],
                db_index=True,
                max_length=3,
            ),
        ),
        migrations.AlterField(
            model_name="accountingentry",
            name="side",
            field=models.CharField(
                choices=[("CA", "Canada"), ("BD", "Bangladesh")],
                db_index=True,
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="created_date",
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name="lead",
            name="account_brand",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="lead",
            name="contact_name",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="lead",
            name="created_date",
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name="lead",
            name="lead_id",
            field=models.CharField(blank=True, db_index=True, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name="lead",
            name="market",
            field=models.CharField(
                choices=[("BD", "Bangladesh"), ("CA", "Canada"), ("USA", "USA"), ("OTHER", "Other")],
                default="CA",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="leadactivity",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="leadcomment",
            name="author",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="leadtask",
            name="assigned_to",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="leadtask",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
    ]