# Generated by Django 5.2.8 on 2026-01-19 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0086_useraccess_can_library_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccess',
            name='can_library',
            field=models.BooleanField(default=False),
        ),
    ]
