# Generated by Django 5.2.8 on 2026-01-31 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0087_useraccess_can_library'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='product_category',
            field=models.CharField(blank=True, choices=[('Swimwear', 'Swimwear'), ('Athleticwear', 'Athleticwear'), ('Activewear', 'Activewear'), ('Streetwear', 'Streetwear'), ('Undergarments', 'Undergarments'), ('T Shirts', 'T Shirts'), ('Hoodies', 'Hoodies'), ('Padded Jackets', 'Padded Jackets'), ('Kids Wear', 'Kids Wear'), ('Other', 'Other')], max_length=100),
        ),
        migrations.AlterField(
            model_name='lead',
            name='product_interest',
            field=models.CharField(blank=True, choices=[('Sampling', 'Sampling'), ('Bulk Order', 'Bulk Order'), ('Pricing Quote', 'Pricing Quote'), ('Fabric Sourcing', 'Fabric Sourcing'), ('Print and Embroidery', 'Print and Embroidery'), ('Branding and Labels', 'Branding and Labels'), ('Shipping and DDP', 'Shipping and DDP'), ('Not Sure Yet', 'Not Sure Yet'), ('Other', 'Other')], max_length=200),
        ),
    ]
