# Generated by Django 5.2.8 on 2026-01-31 20:47

import crm.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0088_lead_product_category_alter_lead_product_interest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='product_category',
            field=models.CharField(blank=True, choices=crm.models.lead_product_category_choices, max_length=100),
        ),
        migrations.AlterField(
            model_name='lead',
            name='product_interest',
            field=models.CharField(blank=True, choices=crm.models.lead_product_interest_choices, max_length=200),
        ),
    ]
