# Generated by Django 5.2.8 on 2026-01-31 21:38

import django.db.models.deletion
from django.db import migrations, models


def forwards(apps, schema_editor):
    Lead = apps.get_model("crm", "Lead")
    Customer = apps.get_model("crm", "Customer")
    Opportunity = apps.get_model("crm", "Opportunity")
    ProductionOrder = apps.get_model("crm", "ProductionOrder")

    # Ensure customer codes exist for legacy rows
    for customer in Customer.objects.filter(models.Q(customer_code__isnull=True) | models.Q(customer_code="")):
        Customer.objects.filter(pk=customer.pk).update(customer_code=f"CUST-{customer.pk}")

    # Link customers that already had a lead attached
    for customer in Customer.objects.exclude(lead__isnull=True):
        Lead.objects.filter(pk=customer.lead_id, customer__isnull=True).update(
            customer_id=customer.id
        )

    # Attach remaining leads by email or create new customer
    for lead in Lead.objects.filter(customer__isnull=True):
        email = (lead.email or "").strip()
        customer = None

        if email:
            customer = Customer.objects.filter(email__iexact=email).first()

        if not customer and lead.account_brand:
            customer = Customer.objects.filter(
                account_brand__iexact=lead.account_brand,
                phone=lead.phone or "",
            ).first()

        if not customer:
            display = lead.account_brand or lead.contact_name or "Customer"
            code = f"CUST-L{lead.pk}"
            if Customer.objects.filter(customer_code=code).exists():
                code = f"CUST-{lead.lead_id or lead.pk}"
            customer = Customer.objects.create(
                customer_code=code,
                account_brand=display,
                contact_name=lead.contact_name or "",
                email=lead.email or "",
                phone=lead.phone or "",
                market=getattr(lead, "market", "") or "",
                notes=lead.notes or "",
            )

        Lead.objects.filter(pk=lead.pk).update(customer_id=customer.id)

    # Backfill opportunity.customer
    for opp in Opportunity.objects.filter(customer__isnull=True):
        if not opp.lead_id:
            continue
        lead_customer_id = Lead.objects.filter(pk=opp.lead_id).values_list(
            "customer_id", flat=True
        ).first()
        if lead_customer_id:
            Opportunity.objects.filter(pk=opp.pk).update(customer_id=lead_customer_id)

    # Backfill production order customer
    for order in ProductionOrder.objects.filter(customer__isnull=True):
        customer_id = None
        if order.opportunity_id:
            customer_id = Opportunity.objects.filter(pk=order.opportunity_id).values_list(
                "customer_id", flat=True
            ).first()
        if not customer_id and order.lead_id:
            customer_id = Lead.objects.filter(pk=order.lead_id).values_list(
                "customer_id", flat=True
            ).first()
        if customer_id:
            ProductionOrder.objects.filter(pk=order.pk).update(customer_id=customer_id)



class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0089_alter_lead_product_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='address_line1',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='customer',
            name='address_line2',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='customer',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='customer',
            name='country',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='customer',
            name='industry',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='customer',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='customer',
            name='province',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='customer',
            name='state',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='customer',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='website',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='lead',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='crm.customer'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='account_brand',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='customer',
            name='contact_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='productionorder',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_orders', to='crm.customer'),
        ),
        migrations.CreateModel(
            name='CustomerEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('lead_created', 'Lead created'), ('opportunity_created', 'Opportunity created'), ('moved_to_production', 'Moved to production'), ('production_status', 'Production status changed'), ('production_completed', 'Production completed'), ('production_closed_won', 'Production closed won'), ('production_closed_lost', 'Production closed lost')], max_length=40)),
                ('title', models.CharField(max_length=200)),
                ('details', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_events', to='crm.customer')),
                ('opportunity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_events', to='crm.opportunity')),
                ('production', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_events', to='crm.productionorder')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomerNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(blank=True, default='', max_length=100)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes_list', to='crm.customer')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RunPython(forwards, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='customer',
            name='lead',
        ),
    ]
