# Generated by Django 5.2.8 on 2026-01-31 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0090_remove_customer_lead_customer_address_line1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionorder',
            name='status',
            field=models.CharField(choices=[('planning', 'Planning'), ('in_progress', 'In progress'), ('hold', 'On hold'), ('done', 'Done'), ('closed_won', 'Closed Won'), ('closed_lost', 'Closed Lost')], default='planning', max_length=20),
        ),
    ]
