# Generated by Django 5.2.8 on 2026-01-31 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0091_alter_productionorder_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
