# Generated by Django 5.2.8 on 2026-02-01 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0092_opportunity_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionorder',
            name='accessories',
            field=models.ManyToManyField(blank=True, related_name='production_orders', to='crm.accessory'),
        ),
        migrations.AddField(
            model_name='productionorder',
            name='fabrics',
            field=models.ManyToManyField(blank=True, related_name='production_orders', to='crm.fabric'),
        ),
        migrations.AddField(
            model_name='productionorder',
            name='threads',
            field=models.ManyToManyField(blank=True, related_name='production_orders', to='crm.threadoption'),
        ),
        migrations.AddField(
            model_name='productionorder',
            name='trims',
            field=models.ManyToManyField(blank=True, related_name='production_orders', to='crm.trim'),
        ),
    ]
