# Generated by Django 5.2.8 on 2026-02-01 21:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0093_productionorder_accessories_productionorder_fabrics_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadcomment',
            name='production',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comments', to='crm.productionorder'),
        ),
        migrations.AlterField(
            model_name='leadcomment',
            name='lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comments', to='crm.lead'),
        ),
    ]
