# Generated by Django 5.2.8 on 2026-02-01 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0095_productionordermaterial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='last_notified_status',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='status',
            field=models.CharField(choices=[('planned', 'Planned'), ('booked', 'Booked'), ('shipped', 'Shipped'), ('out_for_delivery', 'Out for delivery'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='planned', max_length=20),
        ),
    ]
