# Generated by Django 5.2.8 on 2026-02-02 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0097_lead_first_touch_channel_lead_last_touch_channel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccess',
            name='can_whatsapp',
            field=models.BooleanField(default=True),
        ),
    ]
