# Generated by Codex on 2026-02-04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0098_useraccess_can_whatsapp"),
    ]

    operations = [
        migrations.AddField(
            model_name="leadcomment",
            name="attachment",
            field=models.FileField(blank=True, null=True, upload_to="chatter_attachments/"),
        ),
    ]
