# Generated by Codex on 2026-02-04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0096_shipment_last_notified_status_alter_shipment_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="whatsappmessage",
            name="media_url",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="whatsappmessage",
            name="media_type",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AddField(
            model_name="whatsappmessage",
            name="media_path",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="whatsappmessage",
            name="media_filename",
            field=models.CharField(blank=True, default="", max_length=180),
        ),
    ]
