# Generated by Django 6.0 on 2026-02-06 07:10

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0100_whatsappmessage_media_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccess',
            name='can_costing',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='useraccess',
            name='can_costing_approve',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='CostSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.CharField(choices=[('Activewear', 'Activewear'), ('Athleticwear', 'Athleticwear'), ('Streetwear', 'Streetwear'), ('Swimwear', 'Swimwear'), ('Undergarments', 'Undergarments'), ('Outerwear', 'Outerwear'), ('Casualwear', 'Casualwear'), ('Kidswear', 'Kidswear'), ('Corporate / Uniforms', 'Corporate / Uniforms'), ('Sustainable Collection', 'Sustainable Collection'), ('Accessories', 'Accessories'), ('Other', 'Other')], default='Other', max_length=50)),
                ('style_code', models.CharField(blank=True, max_length=50)),
                ('style_name', models.CharField(blank=True, max_length=200)),
                ('version_number', models.PositiveIntegerField(default=1)),
                ('currency', models.CharField(choices=[('USD', 'USD'), ('CAD', 'CAD'), ('BDT', 'BDT')], default='USD', max_length=10)),
                ('production_location', models.CharField(choices=[('bd', 'Bangladesh'), ('ca', 'Canada'), ('other', 'Other')], default='bd', max_length=20)),
                ('target_quantity', models.PositiveIntegerField(default=0)),
                ('overhead_method', models.CharField(choices=[('per_minute', 'Per minute'), ('percent_of_labor', 'Percent of labor'), ('per_piece', 'Per piece')], default='per_piece', max_length=20)),
                ('target_margin_percent', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=6)),
                ('quote_price_per_piece', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved'), ('locked', 'Locked')], default='draft', max_length=20)),
                ('is_active', models.BooleanField(default=False)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_cost_sheets', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cost_sheets', to='crm.customer')),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cost_sheets', to='crm.opportunity')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='CostLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('fabric', 'Fabric'), ('trims', 'Trims'), ('labor', 'Labor'), ('overhead', 'Overhead'), ('process', 'Process'), ('packaging', 'Packaging'), ('freight', 'Freight'), ('testing', 'Testing'), ('other', 'Other')], default='other', max_length=20)),
                ('item_name', models.CharField(max_length=200)),
                ('uom', models.CharField(blank=True, max_length=30)),
                ('consumption_per_piece', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=12)),
                ('waste_percent', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=6)),
                ('rate', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=12)),
                ('setup_cost', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('total_cost_per_piece', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=12)),
                ('notes', models.TextField(blank=True, default='')),
                ('cost_sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='crm.costsheet')),
            ],
            options={
                'ordering': ['section', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ActualCostEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('fabric', 'Fabric'), ('trims', 'Trims'), ('labor', 'Labor'), ('overhead', 'Overhead'), ('process', 'Process'), ('packaging', 'Packaging'), ('freight', 'Freight'), ('testing', 'Testing'), ('other', 'Other')], default='other', max_length=20)),
                ('item_name', models.CharField(max_length=200)),
                ('uom', models.CharField(blank=True, max_length=30)),
                ('actual_qty_total', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=12)),
                ('actual_rate', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=12)),
                ('actual_total_cost', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=14)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actual_cost_entries', to='crm.opportunity')),
                ('production_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actual_cost_entries', to='crm.productionorder')),
                ('cost_sheet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actual_cost_entries', to='crm.costsheet')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddField(
            model_name='productionorder',
            name='cost_sheet_active',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_orders', to='crm.costsheet'),
        ),
        migrations.CreateModel(
            name='CostSheetAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created_version', 'Created version'), ('approved', 'Approved'), ('locked', 'Locked'), ('exported', 'Exported'), ('uploaded_file', 'Uploaded file'), ('edited_actual', 'Edited actual costs')], max_length=20)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('before_data', models.JSONField(blank=True, null=True)),
                ('after_data', models.JSONField(blank=True, null=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cost_sheet_audits', to=settings.AUTH_USER_MODEL)),
                ('cost_sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audits', to='crm.costsheet')),
            ],
            options={
                'ordering': ['-changed_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='OpportunityDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='opportunity_documents/')),
                ('original_name', models.CharField(blank=True, max_length=255)),
                ('doc_type', models.CharField(choices=[('costing_pdf', 'Costing PDF'), ('costing_excel', 'Costing Excel'), ('costing_other', 'Costing Other'), ('other', 'Other')], default='other', max_length=30)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('cost_sheet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='crm.costsheet')),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='crm.opportunity')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opportunity_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at', '-id'],
            },
        ),
    ]
