# Generated by Codex on 2026-02-06

from decimal import Decimal

import django.db.models.deletion
from django.db import migrations, models


def _migrate_cost_sheets(apps, schema_editor):
    CostSheet = apps.get_model("crm", "CostSheet")
    CostLineItem = apps.get_model("crm", "CostLineItem")
    CostSheetSimple = apps.get_model("crm", "CostSheetSimple")

    section_keys = [
        "fabric",
        "trims",
        "labor",
        "overhead",
        "process",
        "packaging",
        "freight",
        "testing",
        "other",
    ]

    def compute_totals(sheet):
        totals = {key: Decimal("0") for key in section_keys}
        lines = CostLineItem.objects.filter(cost_sheet_id=sheet.id)
        for line in lines:
            key = line.section if line.section in totals else "other"
            value = line.total_cost_per_piece
            if value is None:
                consumption = line.consumption_per_piece or Decimal("0")
                rate = line.rate or Decimal("0")
                waste = line.waste_percent or Decimal("0")
                setup = line.setup_cost or Decimal("0")
                base = consumption * rate * (Decimal("1") + (waste / Decimal("100")))
                qty = sheet.target_quantity or 0
                setup_per_piece = setup / Decimal(qty) if qty else Decimal("0")
                value = base + setup_per_piece
            totals[key] += Decimal(value)
        return totals

    opp_ids = (
        CostSheet.objects.values_list("opportunity_id", flat=True)
        .distinct()
    )

    for opp_id in opp_ids:
        if CostSheetSimple.objects.filter(opportunity_id=opp_id).exists():
            continue
        qs = CostSheet.objects.filter(opportunity_id=opp_id)
        sheet = (
            qs.filter(is_active=True).order_by("-updated_at", "-id").first()
            or qs.order_by("-updated_at", "-id").first()
        )
        if not sheet:
            continue

        totals = compute_totals(sheet)
        status = "approved" if sheet.status in ("approved", "locked") else "draft"

        CostSheetSimple.objects.create(
            opportunity_id=sheet.opportunity_id,
            customer_id=sheet.customer_id,
            style_name=sheet.style_name or "",
            style_code=sheet.style_code or "",
            product_type=sheet.product_type or "Other",
            quantity=sheet.target_quantity or 0,
            factory_location=sheet.production_location or "bd",
            fabric_cost_per_piece=totals["fabric"],
            fabric_wastage_percent=Decimal("0"),
            trim_cost_per_piece=totals["trims"],
            labor_cost_per_piece=totals["labor"],
            overhead_cost_per_piece=totals["overhead"],
            process_cost_per_piece=totals["process"],
            packaging_cost_per_piece=totals["packaging"],
            freight_cost_per_piece=totals["freight"],
            testing_cost_per_piece=totals["testing"],
            other_cost_per_piece=totals["other"],
            quote_price_per_piece=sheet.quote_price_per_piece or Decimal("0"),
            status=status,
            notes="Migrated from detailed costing. Fabric wastage set to 0; adjust if needed.",
        )


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0105_merge_0103_0104"),
    ]

    operations = [
        migrations.CreateModel(
            name="CostSheetSimple",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("style_name", models.CharField(blank=True, max_length=200)),
                ("style_code", models.CharField(blank=True, max_length=50)),
                ("product_type", models.CharField(choices=[("Activewear", "Activewear"), ("Athleticwear", "Athleticwear"), ("Streetwear", "Streetwear"), ("Swimwear", "Swimwear"), ("Undergarments", "Undergarments"), ("Outerwear", "Outerwear"), ("Casualwear", "Casualwear"), ("Kidswear", "Kidswear"), ("Corporate / Uniforms", "Corporate / Uniforms"), ("Sustainable Collection", "Sustainable Collection"), ("Accessories", "Accessories"), ("Other", "Other")], default="Other", max_length=50)),
                ("quantity", models.PositiveIntegerField(default=0)),
                ("currency", models.CharField(choices=[("BDT", "BDT")], default="BDT", max_length=10)),
                ("factory_location", models.CharField(choices=[("bd", "Bangladesh"), ("ca", "Canada"), ("other", "Other")], default="bd", max_length=20)),
                ("fabric_cost_per_piece", models.DecimalField(decimal_places=4, default=Decimal("0"), max_digits=12)),
                ("fabric_wastage_percent", models.DecimalField(decimal_places=2, default=Decimal("0"), max_digits=6)),
                ("trim_cost_per_piece", models.DecimalField(decimal_places=4, default=Decimal("0"), max_digits=12)),
                ("labor_cost_per_piece", models.DecimalField(decimal_places=4, default=Decimal("0"), max_digits=12)),
                ("overhead_cost_per_piece", models.DecimalField(decimal_places=4, default=Decimal("0"), max_digits=12)),
                ("process_cost_per_piece", models.DecimalField(decimal_places=4, default=Decimal("0"), max_digits=12)),
                ("packaging_cost_per_piece", models.DecimalField(decimal_places=4, default=Decimal("0"), max_digits=12)),
                ("freight_cost_per_piece", models.DecimalField(decimal_places=4, default=Decimal("0"), max_digits=12)),
                ("testing_cost_per_piece", models.DecimalField(decimal_places=4, default=Decimal("0"), max_digits=12)),
                ("other_cost_per_piece", models.DecimalField(decimal_places=4, default=Decimal("0"), max_digits=12)),
                ("quote_price_per_piece", models.DecimalField(decimal_places=4, default=Decimal("0"), max_digits=12)),
                ("notes", models.TextField(blank=True, default="")),
                ("status", models.CharField(choices=[("draft", "Draft"), ("approved", "Approved")], default="draft", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("customer", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="simple_cost_sheets", to="crm.customer")),
                ("opportunity", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="simple_cost_sheets", to="crm.opportunity")),
            ],
            options={
                "ordering": ["-updated_at", "-id"],
            },
        ),
        migrations.AddField(
            model_name="opportunitydocument",
            name="cost_sheet_simple",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="documents", to="crm.costsheetsimple"),
        ),
        migrations.RunPython(_migrate_cost_sheets, migrations.RunPython.noop),
    ]
