# Generated by Django 5.2.8 on 2026-02-08 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0101_merge_0099_0100'),
        ('crm', '0109_productionorderline'),
    ]

    operations = [
    ]
