# Generated by Codex on 2026-02-09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def set_invoice_region(apps, schema_editor):
    Invoice = apps.get_model("crm", "Invoice")

    for inv in Invoice.objects.select_related("customer").all():
        region = "CA"
        customer = getattr(inv, "customer", None)
        if customer:
            country = (getattr(customer, "country", "") or "").lower().strip()
            if "canada" in country or country in {"ca", "canada"}:
                region = "CA"
            elif "bangladesh" in country or country in {"bd", "bangladesh"}:
                region = "BD"
            elif (inv.currency or "").upper().strip() == "CAD":
                region = "CA"
            else:
                region = "CA"
        else:
            if (inv.currency or "").upper().strip() == "CAD":
                region = "CA"

        inv.invoice_region = region
        inv.save(update_fields=["invoice_region"])


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0112_library_attachment"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="invoice_region",
            field=models.CharField(blank=True, choices=[("CA", "Canada"), ("BD", "Bangladesh")], default="", max_length=2),
        ),
        migrations.AddField(
            model_name="invoice",
            name="invoice_status",
            field=models.CharField(choices=[("DRAFT", "Draft"), ("APPROVED", "Approved")], default="DRAFT", max_length=12),
        ),
        migrations.AddField(
            model_name="invoice",
            name="approved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="invoice",
            name="approved_by",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="approved_invoices", to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name="InvoiceAudit",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("action", models.CharField(choices=[("approved", "Approved")], max_length=20)),
                ("changed_at", models.DateTimeField(auto_now_add=True)),
                ("note", models.CharField(blank=True, default="", max_length=255)),
                ("changed_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="invoice_audits", to=settings.AUTH_USER_MODEL)),
                ("invoice", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="audits", to="crm.invoice")),
            ],
            options={
                "ordering": ["-changed_at", "-id"],
            },
        ),
        migrations.RunPython(set_invoice_region, reverse_code=migrations.RunPython.noop),
    ]
