# Generated by Django 5.2.8 on 2026-03-04 01:26

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0120_merge_0110_0119'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CostingHeader",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("style_name", models.CharField(blank=True, max_length=200)),
                ("style_code", models.CharField(blank=True, max_length=50)),
                ("product_type", models.CharField(choices=[("Activewear", "Activewear"), ("Athleticwear", "Athleticwear"), ("Streetwear", "Streetwear"), ("Swimwear", "Swimwear"), ("Undergarments", "Undergarments"), ("Outerwear", "Outerwear"), ("Casualwear", "Casualwear"), ("Kidswear", "Kidswear"), ("Corporate / Uniforms", "Corporate / Uniforms"), ("Sustainable Collection", "Sustainable Collection"), ("Accessories", "Accessories"), ("Other", "Other")], default="Other", max_length=50)),
                ("factory_location", models.CharField(choices=[("bd", "Bangladesh"), ("ca", "Canada"), ("other", "Other")], default="bd", max_length=20)),
                ("order_quantity", models.PositiveIntegerField(default=0)),
                ("currency", models.CharField(choices=[("BDT", "BDT"), ("CAD", "CAD"), ("USD", "USD")], default="BDT", max_length=10)),
                ("exchange_rate", models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ("finance_percent_fabric", models.DecimalField(decimal_places=2, default=Decimal("0"), max_digits=6)),
                ("finance_percent_trims", models.DecimalField(decimal_places=2, default=Decimal("0"), max_digits=6)),
                ("commission_percent", models.DecimalField(decimal_places=2, default=Decimal("0"), max_digits=6)),
                ("target_margin_percent", models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ("manual_fob_per_piece", models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ("status", models.CharField(choices=[("draft", "Draft"), ("approved", "Approved")], default="draft", max_length=20)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("approved_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="approved_costing_headers", to=settings.AUTH_USER_MODEL)),
                ("customer", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="costing_headers", to="crm.customer")),
                ("opportunity", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="costing_headers", to="crm.opportunity")),
            ],
            options={"ordering": ["-updated_at", "-id"]},
        ),
        migrations.CreateModel(
            name="CostingLineItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("category", models.CharField(choices=[("fabric", "Fabric"), ("sewing_trim", "Sewing trims"), ("packaging_trim", "Packaging trims"), ("other", "Other")], default="other", max_length=30)),
                ("item_name", models.CharField(max_length=200)),
                ("item_reference", models.CharField(blank=True, default="", max_length=200)),
                ("supplier", models.CharField(blank=True, default="", max_length=200)),
                ("uom", models.CharField(choices=[("piece", "Per piece"), ("kg", "Per kg"), ("meter", "Per meter"), ("yard", "Per yard"), ("roll", "Per roll"), ("cone", "Per cone"), ("pack", "Per pack"), ("order", "Per order")], default="piece", max_length=20)),
                ("unit_price", models.DecimalField(decimal_places=4, default=Decimal("0"), max_digits=12)),
                ("freight", models.DecimalField(decimal_places=4, default=Decimal("0"), max_digits=12)),
                ("consumption_value", models.DecimalField(decimal_places=4, default=Decimal("0"), max_digits=12)),
                ("wastage_percent", models.DecimalField(decimal_places=2, default=Decimal("0"), max_digits=6)),
                ("denominator_value", models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ("placement", models.CharField(blank=True, default="", max_length=120)),
                ("color", models.CharField(blank=True, default="", max_length=120)),
                ("gsm", models.CharField(blank=True, default="", max_length=120)),
                ("cut_width", models.CharField(blank=True, default="", max_length=120)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("remarks", models.TextField(blank=True, default="")),
                ("costing", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="line_items", to="crm.costingheader")),
            ],
            options={"ordering": ["category", "sort_order", "id"]},
        ),
        migrations.CreateModel(
            name="CostingSMV",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("machine_smv", models.DecimalField(decimal_places=4, default=Decimal("0"), max_digits=12)),
                ("finishing_smv", models.DecimalField(decimal_places=4, default=Decimal("0"), max_digits=12)),
                ("cpm", models.DecimalField(decimal_places=4, default=Decimal("0"), max_digits=12)),
                ("efficiency_costing", models.DecimalField(decimal_places=2, default=Decimal("100"), max_digits=6)),
                ("efficiency_planned", models.DecimalField(decimal_places=2, default=Decimal("100"), max_digits=6)),
                ("costing", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="smv", to="crm.costingheader")),
            ],
        ),
        migrations.CreateModel(
            name="CostingAuditLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("action", models.CharField(choices=[("created", "Created"), ("updated", "Updated"), ("approved", "Approved"), ("unlocked", "Unlocked"), ("exported", "Exported")], max_length=20)),
                ("changed_at", models.DateTimeField(auto_now_add=True)),
                ("note", models.CharField(blank=True, default="", max_length=255)),
                ("before_data", models.JSONField(blank=True, null=True)),
                ("after_data", models.JSONField(blank=True, null=True)),
                ("changed_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="costing_audits", to=settings.AUTH_USER_MODEL)),
                ("costing", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="audits", to="crm.costingheader")),
            ],
            options={"ordering": ["-changed_at", "-id"]},
        ),
        migrations.AddField(
            model_name="opportunity",
            name="costing_fob_per_piece",
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name="opportunity",
            name="costing_margin_percent",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name="opportunity",
            name="costing_status",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AddField(
            model_name="opportunity",
            name="costing_total_cost_per_piece",
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
    ]
