# Generated by Django 5.2.8 on 2026-03-04 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0124_costing_snapshot'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='whatsappproviderlog',
            new_name='crm_whatsap_provide_f51ff8_idx',
            old_name='crm_whatsap_provider_3d8d2a_idx',
        ),
        migrations.RenameIndex(
            model_name='whatsappproviderlog',
            new_name='crm_whatsap_created_d7b6e3_idx',
            old_name='crm_whatsap_created_8fef63_idx',
        ),
        migrations.RenameIndex(
            model_name='whatsappwebhookevent',
            new_name='crm_whatsap_provide_469389_idx',
            old_name='crm_whatsa_provide_5d0f74_idx',
        ),
        migrations.RenameIndex(
            model_name='whatsappwebhookevent',
            new_name='crm_whatsap_receive_97df3e_idx',
            old_name='crm_whatsa_receive_9a5f5d_idx',
        ),
        migrations.AlterField(
            model_name='costingauditlog',
            name='action',
            field=models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('approved', 'Approved'), ('unlocked', 'Unlocked'), ('exported', 'Exported'), ('uploaded_file', 'Uploaded file')], max_length=20),
        ),
    ]
