# Generated by Django 5.2.8 on 2026-03-08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0125_costing_index_sync"),
    ]

    operations = [
        migrations.AddField(
            model_name="costingheader",
            name="buyer",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AddField(
            model_name="costingheader",
            name="brand",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AddField(
            model_name="costingheader",
            name="gender",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AddField(
            model_name="costingheader",
            name="size_range",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="costingheader",
            name="season",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="costingheader",
            name="moq",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="costingheader",
            name="costing_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="costingheader",
            name="merchandiser",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AddField(
            model_name="costingheader",
            name="fabric_type",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AddField(
            model_name="costingheader",
            name="fabric_gsm",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="costingheader",
            name="fabric_composition",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AddField(
            model_name="costingheader",
            name="wash_type",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AddField(
            model_name="costingheader",
            name="print_type",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AddField(
            model_name="costingheader",
            name="embroidery",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AddField(
            model_name="costingheader",
            name="label_type",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AddField(
            model_name="costingheader",
            name="packaging_type",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AddField(
            model_name="costingheader",
            name="special_trims",
            field=models.CharField(blank=True, default="", max_length=300),
        ),
        migrations.AddField(
            model_name="costingheader",
            name="fit_remarks",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="costinglineitem",
            name="description",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
    ]
