# Generated by Django 5.2.8 on 2026-03-17 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0125_costing_index_sync"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="whatsappproviderlog",
            name="message",
        ),
        migrations.RemoveField(
            model_name="whatsappproviderlog",
            name="thread",
        ),
        migrations.DeleteModel(
            name="WhatsAppWebhookEvent",
        ),
        migrations.RemoveField(
            model_name="whatsappmessage",
            name="status",
        ),
        migrations.RemoveField(
            model_name="whatsappthread",
            name="last_inbound_at",
        ),
        migrations.DeleteModel(
            name="WhatsAppProviderLog",
        ),
    ]
