# Generated by Django 5.2.8 on 2026-03-09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0126_costing_header_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="costinglineitem",
            name="ship_mode",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
        migrations.AddField(
            model_name="costinglineitem",
            name="pay_mode",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
    ]
