# Generated by Django 5.2.8 on 2026-03-14

from django.conf import settings
from django.db import migrations, models


def migrate_lead_types(apps, schema_editor):
    Lead = apps.get_model("crm", "Lead")
    for lead in Lead.objects.all():
        old_type = lead.lead_type
        if old_type and old_type not in ("inbound", "outbound"):
            if not lead.brand_stage:
                lead.brand_stage = old_type
            lead.lead_type = "inbound"
        if not lead.website and getattr(lead, "company_website", ""):
            lead.website = lead.company_website
        if not lead.next_follow_up_date and getattr(lead, "next_followup", None):
            lead.next_follow_up_date = lead.next_followup
        lead.save(update_fields=["brand_stage", "lead_type", "website", "next_follow_up_date"])


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0127_costing_lineitem_ship_pay_mode"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="lead",
            name="source_channel",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="lead",
            name="outbound_method",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="lead",
            name="outbound_status",
            field=models.CharField(blank=True, choices=[("Not Contacted", "Not Contacted"), ("First Contact Sent", "First Contact Sent"), ("Follow Up 1 Sent", "Follow Up 1 Sent"), ("Follow Up 2 Sent", "Follow Up 2 Sent"), ("Follow Up 3 Sent", "Follow Up 3 Sent"), ("Replied", "Replied"), ("Interested", "Interested"), ("Meeting Booked", "Meeting Booked"), ("Quote Requested", "Quote Requested"), ("Sample Discussion", "Sample Discussion"), ("Converted to Opportunity", "Converted to Opportunity"), ("No Response", "No Response"), ("Bad Fit", "Bad Fit"), ("Archived", "Archived")], db_index=True, default="", max_length=60),
        ),
        migrations.AddField(
            model_name="lead",
            name="priority_level",
            field=models.CharField(choices=[("Low", "Low"), ("Medium", "Medium"), ("High", "High"), ("Hot", "Hot")], db_index=True, default="Medium", max_length=20),
        ),
        migrations.AddField(
            model_name="lead",
            name="brand_stage",
            field=models.CharField(blank=True, choices=[("Startup / New Brand", "Startup / New Brand"), ("Brand Owner / Designer", "Brand Owner / Designer"), ("Retail Store / Boutique", "Retail Store / Boutique"), ("Corporate Client", "Corporate Client"), ("Distributor / Wholesaler", "Distributor / Wholesaler"), ("Private Label Client", "Private Label Client"), ("Manufacturer Collaboration", "Manufacturer Collaboration"), ("Influencer / Content Creator", "Influencer / Content Creator"), ("Returning Customer", "Returning Customer"), ("Other", "Other")], default="", max_length=50),
        ),
        migrations.AddField(
            model_name="lead",
            name="target_order_volume_min",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="lead",
            name="target_order_volume_max",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="lead",
            name="brand_fit_score",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="lead",
            name="region",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="lead",
            name="website",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="lead",
            name="instagram_handle",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AddField(
            model_name="lead",
            name="linkedin_url",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="lead",
            name="last_outreach_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="lead",
            name="next_follow_up_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="lead",
            name="last_reply_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="lead",
            name="ideal_customer_profile_match",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="lead",
            name="disqualification_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="lead",
            name="assigned_to",
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET_NULL, related_name="assigned_leads", to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name="leadactivity",
            name="channel",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AddField(
            model_name="leadactivity",
            name="user",
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET_NULL, related_name="lead_activities", to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name="leadactivity",
            name="note",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="leadactivity",
            name="message_copy",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="leadactivity",
            name="outcome",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
        migrations.AddField(
            model_name="leadactivity",
            name="follow_up_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.RunPython(migrate_lead_types, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="lead",
            name="lead_type",
            field=models.CharField(choices=[("inbound", "Inbound"), ("outbound", "Outbound")], db_index=True, default="inbound", max_length=20),
        ),
    ]
