# Generated by Django 5.2.8 on 2026-03-14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0128_lead_outbound_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="opportunity",
            name="converted_from_lead_type",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AddField(
            model_name="opportunity",
            name="converted_from_source_channel",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="opportunity",
            name="converted_from_outbound_status",
            field=models.CharField(blank=True, default="", max_length=60),
        ),
    ]

