# Generated by Django 6.0 on 2026-03-18 19:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0130_lead_fit_score_locked'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='confidence_level',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lead',
            name='last_enriched_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='product_category_guess',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='lead',
            name='qualification_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='lead',
            name='qualification_status',
            field=models.CharField(choices=[('Raw Imported', 'Raw Imported'), ('Researching', 'Researching'), ('Enriched', 'Enriched'), ('Qualified', 'Qualified'), ('Strong Fit', 'Strong Fit'), ('Needs Review', 'Needs Review'), ('Outreach Ready', 'Outreach Ready'), ('Contact Missing', 'Contact Missing'), ('Duplicate', 'Duplicate'), ('Bad Fit', 'Bad Fit'), ('Archived', 'Archived')], db_index=True, default='Raw Imported', max_length=40),
        ),
        migrations.AddField(
            model_name='lead',
            name='recommended_channel',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='lead',
            name='recommended_next_action',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='lead',
            name='target_order_range_estimate',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='costinglineitem',
            name='category',
            field=models.CharField(choices=[('fabric', 'Fabrics'), ('sewing_trim', 'Sewing trims'), ('packaging_trim', 'Packaging trims'), ('labels_branding', 'Labels and branding'), ('wash_process', 'Washing and process'), ('cm_labor', 'CM and labor'), ('logistics_compliance', 'Logistics and compliance'), ('other', 'Other costs')], default='other', max_length=30),
        ),
        migrations.AlterField(
            model_name='costinglineitem',
            name='description',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='leadactivity',
            name='activity_type',
            field=models.CharField(choices=[('lead_created', 'Lead created'), ('converted', 'Converted to opportunity'), ('ai_summary', 'AI summary created'), ('file_uploaded', 'File uploaded'), ('file_deleted', 'File deleted'), ('note_added', 'Note added'), ('task_created', 'Task created'), ('task_completed', 'Task completed'), ('shipping_updated', 'Shipping updated'), ('stage_updated', 'Stage updated'), ('cold_email_sent', 'Cold email sent'), ('linkedin_message_sent', 'LinkedIn message sent'), ('instagram_dm_sent', 'Instagram DM sent'), ('call_made', 'Call made'), ('follow_up_sent', 'Follow up sent'), ('reply_received', 'Reply received'), ('meeting_booked', 'Meeting booked'), ('quote_shared', 'Quote shared'), ('sample_discussion', 'Sample discussion')], max_length=40),
        ),
        migrations.CreateModel(
            name='LeadAIInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('auto', 'Auto'), ('manual', 'Manual')], default='auto', max_length=20)),
                ('summary_text', models.TextField(blank=True, default='')),
                ('data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_insights', to='crm.lead')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LeadContactPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_type', models.CharField(choices=[('email', 'Email'), ('phone', 'Phone'), ('contact_form', 'Contact form'), ('instagram', 'Instagram'), ('linkedin', 'LinkedIn'), ('website', 'Website'), ('other', 'Other')], max_length=30)),
                ('value', models.CharField(max_length=255)),
                ('label', models.CharField(blank=True, default='', max_length=120)),
                ('source_url', models.URLField(blank=True, default='')),
                ('confidence', models.PositiveIntegerField(default=0)),
                ('is_primary', models.BooleanField(default=False)),
                ('last_verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_points', to='crm.lead')),
            ],
            options={
                'ordering': ['-is_primary', '-confidence', 'contact_type'],
            },
        ),
        migrations.CreateModel(
            name='LeadImportJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='lead_imports/')),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('processing', 'Processing'), ('done', 'Done'), ('failed', 'Failed')], default='queued', max_length=20)),
                ('total_rows', models.PositiveIntegerField(default=0)),
                ('created_count', models.PositiveIntegerField(default=0)),
                ('updated_count', models.PositiveIntegerField(default=0)),
                ('duplicate_count', models.PositiveIntegerField(default=0)),
                ('strong_fit_count', models.PositiveIntegerField(default=0)),
                ('moderate_fit_count', models.PositiveIntegerField(default=0)),
                ('weak_fit_count', models.PositiveIntegerField(default=0)),
                ('bad_fit_count', models.PositiveIntegerField(default=0)),
                ('missing_contact_count', models.PositiveIntegerField(default=0)),
                ('error_count', models.PositiveIntegerField(default=0)),
                ('stats', models.JSONField(blank=True, default=dict)),
                ('error_log', models.TextField(blank=True, default='')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_import_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='lead',
            name='import_job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='crm.leadimportjob'),
        ),
        migrations.CreateModel(
            name='LeadResearchJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website', models.URLField(blank=True, default='')),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('processing', 'Processing'), ('done', 'Done'), ('failed', 'Failed')], default='queued', max_length=20)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True, default='')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_research_jobs', to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='research_jobs', to='crm.lead')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
