# Generated by Django 5.2.8 on 2026-03-24 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0131_lead_confidence_level_lead_last_enriched_at_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='aihealthruncheck',
            table='crm_aihealthruncheck',
        ),
    ]
