# Generated by Django 5.2.8 on 2026-03-23 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0126_remove_whatsappproviderlog_message_and_more"),
        ("crm", "0131_lead_confidence_level_lead_last_enriched_at_and_more"),
    ]

    operations = []
