# Generated by Django 5.2.8 on 2026-03-25 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0132_alter_aihealthruncheck_table"),
        ("crm", "0132_merge_20260323_1523"),
    ]

    operations = []
