# Generated by Django 6.0 on 2026-05-12

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0133_merge_20260325_0000"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InvoicePayment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("payment_date", models.DateField(default=django.utils.timezone.localdate)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=14)),
                (
                    "currency",
                    models.CharField(
                        choices=[("USD", "USD"), ("CAD", "CAD"), ("BDT", "BDT")],
                        default="CAD",
                        max_length=10,
                    ),
                ),
                (
                    "side",
                    models.CharField(
                        choices=[("CA", "Canada"), ("BD", "Bangladesh")],
                        default="CA",
                        max_length=2,
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("bank", "Bank transfer"),
                            ("cash", "Cash"),
                            ("cheque", "Cheque"),
                            ("card", "Card"),
                            ("mobile", "Mobile payment"),
                            ("other", "Other"),
                        ],
                        default="bank",
                        max_length=20,
                    ),
                ),
                ("rate_to_cad", models.DecimalField(decimal_places=6, default=Decimal("0"), max_digits=14)),
                ("rate_to_bdt", models.DecimalField(decimal_places=6, default=Decimal("0"), max_digits=14)),
                ("amount_cad", models.DecimalField(decimal_places=2, default=Decimal("0"), max_digits=14)),
                ("amount_bdt", models.DecimalField(decimal_places=2, default=Decimal("0"), max_digits=14)),
                ("notes", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "accounting_entry",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="invoice_payments",
                        to="crm.accountingentry",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_invoice_payments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="crm.invoice",
                    ),
                ),
                (
                    "production_order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="invoice_payments",
                        to="crm.productionorder",
                    ),
                ),
            ],
            options={
                "ordering": ["-payment_date", "-id"],
            },
        ),
    ]
