from django.db import migrations, models


PRODUCT_CATEGORY_CHOICES = [
    ("Leggings", "Leggings"),
    ("Sports Bra", "Sports Bra"),
    ("Crop Top", "Crop Top"),
    ("Yoga Set", "Yoga Set"),
    ("Tank Top", "Tank Top"),
    ("Joggers", "Joggers"),
    ("Track Pants", "Track Pants"),
    ("Tracksuit Set", "Tracksuit Set"),
    ("Training Jacket", "Training Jacket"),
    ("Windbreaker", "Windbreaker"),
    ("Hoodie", "Hoodie"),
    ("Sweatshirt", "Sweatshirt"),
    ("Cargo Pants", "Cargo Pants"),
    ("Oversized Tee", "Oversized Tee"),
    ("Denim Jacket", "Denim Jacket"),
    ("Bikini Set", "Bikini Set"),
    ("One Piece", "One Piece"),
    ("Mens Trunk", "Mens Trunk"),
    ("Rash Guard", "Rash Guard"),
    ("Mens Boxer", "Mens Boxer"),
    ("Brief", "Brief"),
    ("Womens Panty", "Womens Panty"),
    ("Bra", "Bra"),
    ("Camisole", "Camisole"),
    ("Padded Jacket", "Padded Jacket"),
    ("Light Jacket", "Light Jacket"),
    ("Pullover", "Pullover"),
    ("Zip Up Hoodie", "Zip Up Hoodie"),
    ("T Shirt", "T Shirt"),
    ("Polo Shirt", "Polo Shirt"),
    ("Lounge Set", "Lounge Set"),
    ("Shorts", "Shorts"),
    ("Onesie", "Onesie"),
    ("Romper", "Romper"),
    ("Hoodie Set", "Hoodie Set"),
    ("Jogger Set", "Jogger Set"),
    ("Baby Sleeper", "Baby Sleeper"),
    ("Office Shirt", "Office Shirt"),
    ("Polo Uniform", "Polo Uniform"),
    ("Work Jacket", "Work Jacket"),
    ("Promotional Tee", "Promotional Tee"),
    ("Organic Cotton Wear", "Organic Cotton Wear"),
    ("Recycled Polyester", "Recycled Polyester"),
    ("Eco Fabric Product", "Eco Fabric Product"),
    ("Cap", "Cap"),
    ("Tote Bag", "Tote Bag"),
    ("Socks", "Socks"),
    ("Headband", "Headband"),
    ("Other", "Other"),
    ("Basketball Jersey", "Basketball Jersey"),
    ("Soccer Jersey", "Soccer Jersey"),
    ("Football Jersey", "Football Jersey"),
    ("Baseball Jersey", "Baseball Jersey"),
    ("Hockey Jersey", "Hockey Jersey"),
    ("Volleyball Jersey", "Volleyball Jersey"),
    ("Rugby Jersey", "Rugby Jersey"),
    ("Sports Tracksuit", "Sports Tracksuit"),
    ("Team Uniform", "Team Uniform"),
    ("Training Jersey", "Training Jersey"),
    ("Warm Up Jacket", "Warm Up Jacket"),
    ("Warm Up Pants", "Warm Up Pants"),
    ("Athletic Shorts", "Athletic Shorts"),
    ("Compression Shirt", "Compression Shirt"),
    ("Compression Shorts", "Compression Shorts"),
    ("Sports Polo", "Sports Polo"),
    ("Coach Jacket", "Coach Jacket"),
    ("Sideline Jacket", "Sideline Jacket"),
    ("Practice Jersey", "Practice Jersey"),
]


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0135_useraccess_can_view_ceo_tools"),
    ]

    operations = [
        migrations.AlterField(
            model_name="opportunity",
            name="product_category",
            field=models.CharField(choices=PRODUCT_CATEGORY_CHOICES, default="Other", max_length=50),
        ),
        migrations.AlterField(
            model_name="product",
            name="product_category",
            field=models.CharField(choices=PRODUCT_CATEGORY_CHOICES, default="Other", max_length=50),
        ),
    ]
