# Generated by Django 6.0 on 2026-05-25 17:40

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0138_production_size_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='internal_cost_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='other_internal_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12),
        ),
        migrations.AddField(
            model_name='invoice',
            name='sewing_charge',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12),
        ),
    ]
