# Generated by Django 6.0 on 2026-05-25 23:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0141_order_lifecycle'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappmessage',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('read', 'Read'), ('failed', 'Failed'), ('received', 'Received')], default='received', max_length=20),
        ),
        migrations.AddField(
            model_name='whatsappthread',
            name='last_inbound_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='WhatsAppWebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('infobip', 'Infobip'), ('meta', 'Meta'), ('web', 'Web')], default='infobip', max_length=20)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('new', 'New'), ('processing', 'Processing'), ('processed', 'Processed'), ('failed', 'Failed')], default='new', max_length=20)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ('-received_at', '-id'),
                'indexes': [models.Index(fields=['provider', 'status'], name='crm_whatsap_provide_469389_idx'), models.Index(fields=['received_at'], name='crm_whatsap_receive_97df3e_idx')],
            },
        ),
        migrations.CreateModel(
            name='WhatsAppProviderLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('infobip', 'Infobip'), ('meta', 'Meta'), ('web', 'Web')], max_length=20)),
                ('direction', models.CharField(choices=[('outbound', 'Outbound'), ('inbound', 'Inbound')], max_length=10)),
                ('endpoint', models.CharField(max_length=200)),
                ('status_code', models.IntegerField(blank=True, null=True)),
                ('ok', models.BooleanField(default=False)),
                ('request_json', models.JSONField(blank=True, default=dict)),
                ('response_json', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True, default='')),
                ('status_name', models.CharField(blank=True, default='', max_length=60)),
                ('status_group_name', models.CharField(blank=True, default='', max_length=60)),
                ('status_group_id', models.CharField(blank=True, default='', max_length=20)),
                ('error_name', models.CharField(blank=True, default='', max_length=120)),
                ('error_description', models.TextField(blank=True, default='')),
                ('request_id', models.CharField(blank=True, default='', max_length=120)),
                ('provider_message_id', models.CharField(blank=True, default='', max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.whatsappmessage')),
                ('thread', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.whatsappthread')),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['provider', 'direction'], name='crm_whatsap_provide_f51ff8_idx'), models.Index(fields=['created_at'], name='crm_whatsap_created_d7b6e3_idx')],
            },
        ),
    ]
