# Generated by Django 6.0 on 2026-05-28 18:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def seed_inventory_intelligence_fields(apps, schema_editor):
    InventoryItem = apps.get_model('crm', 'InventoryItem')
    ProductionOrderMaterial = apps.get_model('crm', 'ProductionOrderMaterial')
    group_map = {
        'fabric_roll': 'fabric',
        'trim': 'trim',
        'polybag': 'packaging',
        'carton': 'packaging',
        'accessory': 'accessories',
        'thread': 'sample_material',
        'needle': 'sample_material',
    }
    for item in InventoryItem.objects.all().only('id', 'category', 'min_level'):
        min_level = item.min_level or 0
        item.material_group = group_map.get(item.category, 'other')
        item.minimum_stock = min_level
        item.reorder_level = min_level
        item.save(update_fields=['material_group', 'minimum_stock', 'reorder_level'])

    for line in ProductionOrderMaterial.objects.all().only('id', 'quantity'):
        line.allocated_quantity = line.quantity or 0
        line.save(update_fields=['allocated_quantity'])


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0143_useraccess_can_view_internal_costing'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventoryreorder',
            options={'ordering': ['-created_at', '-id']},
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='damaged_quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='incoming_quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='material_group',
            field=models.CharField(choices=[('fabric', 'Fabric'), ('trim', 'Trim'), ('label', 'Label'), ('packaging', 'Packaging'), ('printing_material', 'Printing Material'), ('accessories', 'Accessories'), ('sample_material', 'Sample Material'), ('other', 'Other')], db_index=True, default='other', max_length=40),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='minimum_stock',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='reorder_level',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='reserved_quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='supplier_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='waste_quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='inventoryreorder',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inventoryreorder',
            name='note',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='productionordermaterial',
            name='allocated_quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='productionordermaterial',
            name='consumed_quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='productionordermaterial',
            name='damaged_quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='productionordermaterial',
            name='status',
            field=models.CharField(choices=[('reserved', 'Reserved'), ('partial', 'Partially Consumed'), ('consumed', 'Consumed'), ('cancelled', 'Cancelled')], default='reserved', max_length=20),
        ),
        migrations.AlterField(
            model_name='inventoryreorder',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.RunPython(seed_inventory_intelligence_fields, migrations.RunPython.noop),
        migrations.CreateModel(
            name='InventoryMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('received', 'Received'), ('allocated', 'Allocated'), ('consumed', 'Consumed'), ('adjusted', 'Adjusted'), ('damaged', 'Damaged')], max_length=20)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reason', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='crm.inventoryitem')),
                ('production_material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements', to='crm.productionordermaterial')),
                ('production_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_movements', to='crm.productionorder')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['inventory_item', 'movement_type'], name='crm_invento_invento_1886ad_idx'), models.Index(fields=['production_order', 'movement_type'], name='crm_invento_product_716fac_idx'), models.Index(fields=['created_at'], name='crm_invento_created_3b4ed1_idx')],
            },
        ),
    ]
