# Generated by Django 6.0 on 2026-05-28 23:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('crm', '0144_alter_inventoryreorder_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AutomationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_name', models.CharField(max_length=160, unique=True)),
                ('rule_type', models.CharField(choices=[('invoice', 'Invoice'), ('production', 'Production'), ('inventory', 'Inventory'), ('lifecycle', 'Lifecycle'), ('general', 'General')], db_index=True, default='general', max_length=30)),
                ('enabled', models.BooleanField(db_index=True, default=True)),
                ('trigger', models.CharField(blank=True, default='', max_length=160)),
                ('condition', models.JSONField(blank=True, default=dict)),
                ('action', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_automation_rules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['rule_type', 'rule_name'],
            },
        ),
        migrations.CreateModel(
            name='AutomationNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_key', models.CharField(db_index=True, max_length=220, unique=True)),
                ('rule_type', models.CharField(choices=[('invoice', 'Invoice'), ('production', 'Production'), ('inventory', 'Inventory'), ('lifecycle', 'Lifecycle'), ('general', 'General')], db_index=True, default='general', max_length=30)),
                ('title', models.CharField(max_length=220)),
                ('message', models.TextField(blank=True, default='')),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('critical', 'Critical')], db_index=True, default='normal', max_length=20)),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('is_resolved', models.BooleanField(db_index=True, default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('record_object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('record_label', models.CharField(blank=True, default='', max_length=220)),
                ('target_url', models.CharField(blank=True, default='', max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('record_content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
                ('rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='crm.automationrule')),
            ],
            options={
                'ordering': ['is_read', '-updated_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='AutomationTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_key', models.CharField(db_index=True, max_length=220, unique=True)),
                ('title', models.CharField(max_length=220)),
                ('description', models.TextField(blank=True, default='')),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], db_index=True, default='normal', max_length=20)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('done', 'Done'), ('cancelled', 'Cancelled')], db_index=True, default='open', max_length=20)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('record_object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('record_label', models.CharField(blank=True, default='', max_length=220)),
                ('target_url', models.CharField(blank=True, default='', max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_automation_tasks', to=settings.AUTH_USER_MODEL)),
                ('notification', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='crm.automationnotification')),
                ('record_content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
                ('rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='crm.automationrule')),
            ],
            options={
                'ordering': ['status', 'due_date', '-updated_at'],
            },
        ),
        migrations.AddIndex(
            model_name='automationrule',
            index=models.Index(fields=['rule_type', 'enabled'], name='crm_automat_rule_ty_d38a5c_idx'),
        ),
        migrations.AddIndex(
            model_name='automationnotification',
            index=models.Index(fields=['rule_type', 'is_resolved', 'is_read'], name='crm_automat_rule_ty_e19bc2_idx'),
        ),
        migrations.AddIndex(
            model_name='automationnotification',
            index=models.Index(fields=['priority', 'is_resolved'], name='crm_automat_priorit_b6ce6f_idx'),
        ),
        migrations.AddIndex(
            model_name='automationnotification',
            index=models.Index(fields=['record_content_type', 'record_object_id'], name='crm_automat_record__e44815_idx'),
        ),
        migrations.AddIndex(
            model_name='automationtask',
            index=models.Index(fields=['status', 'priority'], name='crm_automat_status_383150_idx'),
        ),
        migrations.AddIndex(
            model_name='automationtask',
            index=models.Index(fields=['record_content_type', 'record_object_id'], name='crm_automat_record__b73824_idx'),
        ),
    ]
