# Generated by Django 6.0 on 2026-05-29 17:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0145_automationrule_automationnotification_automationtask_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductReferenceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='product_reference_images/%Y/%m/')),
                ('caption', models.CharField(blank=True, default='', max_length=160)),
                ('slot', models.PositiveSmallIntegerField(default=1)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_reference_images', to='crm.lead')),
                ('opportunity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_reference_images', to='crm.opportunity')),
                ('production_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_reference_images', to='crm.productionorder')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_reference_images', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['slot', 'uploaded_at', 'id'],
                'indexes': [models.Index(fields=['lead', 'slot'], name='crm_product_lead_id_b8b098_idx'), models.Index(fields=['opportunity'], name='crm_product_opportu_32d1e8_idx'), models.Index(fields=['production_order'], name='crm_product_product_dbd6a6_idx')],
                'constraints': [models.UniqueConstraint(fields=('lead', 'slot'), name='uniq_product_reference_image_lead_slot')],
            },
        ),
    ]
