# Generated by Django 6.0 on 2026-06-01 20:25

import crm.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0146_productreferenceimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='primary_product_type',
            field=models.CharField(blank=True, choices=crm.models.lead_product_type_choices, db_index=True, default='', max_length=100),
        ),
    ]
