# Generated by Django 6.0 on 2026-06-01 20:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0147_lead_primary_product_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionProgressPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('cutting', 'Cutting'), ('printing', 'Printing'), ('sewing', 'Sewing'), ('qc', 'QC'), ('packing', 'Packing')], db_index=True, max_length=20)),
                ('image', models.ImageField(upload_to='production_progress/%Y/%m/')),
                ('caption', models.CharField(blank=True, default='', max_length=160)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_photos', to='crm.productionorder')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_progress_photos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['stage', '-uploaded_at', '-id'],
                'indexes': [models.Index(fields=['order', 'stage'], name='crm_product_order_i_8ba331_idx'), models.Index(fields=['uploaded_at'], name='crm_product_uploade_9502cd_idx')],
            },
        ),
    ]
