# Generated by Django 6.0 on 2026-06-03 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0148_productionprogressphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionorder',
            name='production_order_type',
            field=models.CharField(choices=[('sampling', 'Sampling'), ('bulk', 'Bulk')], db_index=True, default='bulk', max_length=20),
        ),
    ]
