# Generated by Django 6.0 on 2026-06-03 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0149_productionorder_production_order_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionorder',
            name='production_order_type',
            field=models.CharField(choices=[('sampling', 'Sample Development'), ('bulk', 'Bulk Production')], db_index=True, default='bulk', max_length=20),
        ),
    ]
