# Generated by Django 6.0 on 2026-06-04 20:06

from collections import Counter
from decimal import Decimal

from django.db import migrations, models


SENT_SHIPMENT_STATUSES = {"booked", "shipped", "out_for_delivery", "delivered"}
READY_SHIPMENT_STATUSES = {"planned"}
ACTIVE_STAGE_STATUSES = {"in_progress", "hold", "delay"}


def _decimal(value):
    if value in (None, ""):
        return Decimal("0")
    try:
        return Decimal(str(value))
    except Exception:
        return Decimal("0")


def _needs_print(order):
    text = " ".join(
        [
            getattr(order, "title", "") or "",
            getattr(order, "style_name", "") or "",
            getattr(order, "notes", "") or "",
            getattr(order, "accessories_note", "") or "",
            getattr(order, "extra_order_note", "") or "",
        ]
    ).lower()
    return any(token in text for token in ["print", "embroidery", "screen", "sublimation", "puff"])


def _stage_done(stage_lookup, *keys):
    return any(stage_lookup.get(key) and stage_lookup[key].status == "done" for key in keys)


def _stage_active(stage_lookup, *keys):
    return any(
        stage_lookup.get(key) and stage_lookup[key].status in ACTIVE_STAGE_STATUSES
        for key in keys
    )


def _derive_operational_status(order, stages, shipments):
    stage_lookup = {stage.stage_key: stage for stage in stages}
    order_type = getattr(order, "production_order_type", "") or "bulk"
    legacy_status = getattr(order, "status", "") or ""

    if legacy_status in {"closed_lost", "cancelled"}:
        return "cancelled"

    if shipments and all(shipment.status == "cancelled" for shipment in shipments):
        return "cancelled"

    if order_type == "sampling" and any(
        shipment.shipment_type == "sample" and shipment.status in SENT_SHIPMENT_STATUSES
        for shipment in shipments
    ):
        return "sample_sent"

    if any(shipment.status in SENT_SHIPMENT_STATUSES for shipment in shipments):
        return "shipped"

    if any(shipment.status in READY_SHIPMENT_STATUSES for shipment in shipments):
        return "ready_to_ship"

    if _stage_done(stage_lookup, "shipping", "packing", "finishing"):
        return "ready_to_ship"

    if _stage_active(stage_lookup, "shipping"):
        return "ready_to_ship"

    if _stage_active(stage_lookup, "packing", "finishing", "ironing"):
        return "packing"

    if _stage_active(stage_lookup, "qc"):
        return "qc"

    if _stage_active(stage_lookup, "sewing"):
        return "sewing"

    if _needs_print(order) and _stage_done(stage_lookup, "cutting") and not _stage_done(stage_lookup, "sewing"):
        return "printing"

    if _stage_active(stage_lookup, "cutting"):
        return "cutting"

    if _stage_done(stage_lookup, "qc"):
        return "packing"

    if _stage_done(stage_lookup, "sewing"):
        return "qc"

    if _stage_done(stage_lookup, "cutting"):
        return "sewing"

    required_kg = _decimal(getattr(order, "fabric_required_kg", None))
    received_kg = _decimal(getattr(order, "fabric_received_kg", None))
    if required_kg and received_kg < required_kg:
        return "fabric_sourcing"

    if _stage_active(stage_lookup, "development", "sampling"):
        return "sample_development"

    if _stage_done(stage_lookup, "development", "sampling"):
        return "approved"

    if order_type == "sampling":
        return "sample_development"

    return "planning"


def backfill_operational_status(apps, schema_editor):
    ProductionOrder = apps.get_model("crm", "ProductionOrder")
    ProductionStage = apps.get_model("crm", "ProductionStage")
    Shipment = apps.get_model("crm", "Shipment")
    counts = Counter()

    for order in ProductionOrder.objects.all().iterator():
        stages = list(ProductionStage.objects.filter(order_id=order.pk))
        shipments = list(Shipment.objects.filter(order_id=order.pk))
        try:
            operational_status = _derive_operational_status(order, stages, shipments)
        except Exception:
            operational_status = "planning"
        ProductionOrder.objects.filter(pk=order.pk).update(operational_status=operational_status)
        counts[operational_status] += 1

    print("Production operational status backfill:", dict(sorted(counts.items())))


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0150_alter_productionorder_production_order_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionorder',
            name='operational_status',
            field=models.CharField(blank=True, choices=[('planning', 'Planning'), ('sample_development', 'Sample Development'), ('sample_sent', 'Sample Sent'), ('approved', 'Approved'), ('fabric_sourcing', 'Fabric Sourcing'), ('cutting', 'Cutting'), ('printing', 'Printing'), ('sewing', 'Sewing'), ('qc', 'QC'), ('packing', 'Packing'), ('ready_to_ship', 'Ready To Ship'), ('shipped', 'Shipped'), ('cancelled', 'Cancelled')], db_index=True, default='planning', max_length=32),
        ),
        migrations.RunPython(backfill_operational_status, migrations.RunPython.noop),
    ]
