# Generated by Django 6.0 on 2026-06-05 02:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0151_productionorder_operational_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountingentryaudit',
            name='entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entry_audits', related_query_name='entry_audit', to='crm.accountingentry'),
        ),
    ]
