# Generated by Django 6.0 on 2026-06-08 18:47

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0153_calendar_invites_reminders'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuickCosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('costing_type', models.CharField(choices=[('quick', 'Quick')], db_index=True, default='quick', editable=False, max_length=20)),
                ('buyer_name', models.CharField(max_length=200)),
                ('project_name', models.CharField(max_length=200)),
                ('product_type', models.CharField(choices=[('Activewear', 'Activewear'), ('Athleticwear', 'Athleticwear'), ('Streetwear', 'Streetwear'), ('Swimwear', 'Swimwear'), ('Undergarments', 'Undergarments'), ('Outerwear', 'Outerwear'), ('Casualwear', 'Casualwear'), ('Kidswear', 'Kidswear'), ('Corporate / Uniforms', 'Corporate / Uniforms'), ('Sustainable Collection', 'Sustainable Collection'), ('Accessories', 'Accessories'), ('Other', 'Other')], default='Other', max_length=50)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('material_cost', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('production_cost', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('other_expenses', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('selling_price_per_piece', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quick_costings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at', '-id'],
            },
        ),
    ]
