# Generated by Django 6.0 on 2026-06-08 22:41

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0154_quick_costing'),
    ]

    operations = [
        migrations.AddField(
            model_name='costingheader',
            name='shipping_cost',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), max_digits=12),
        ),
        migrations.AddField(
            model_name='quickcosting',
            name='shipping_cost',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), max_digits=12),
        ),
    ]
