# Generated by Django 6.0 on 2026-06-09 21:04

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0155_costing_shipping_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='quickcosting',
            name='commission_per_piece',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), max_digits=12),
        ),
        migrations.AddField(
            model_name='quickcosting',
            name='exchange_rate_bdt_per_cad',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='quickcosting',
            name='target_margin_percent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
