# Generated by Django 6.0 on 2026-06-09 21:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0156_quick_costing_currency_margin'),
    ]

    operations = [
        migrations.AddField(
            model_name='quickcosting',
            name='account_brand',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='quickcosting',
            name='contact_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='quickcosting',
            name='opportunity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quick_costings', to='crm.opportunity'),
        ),
    ]
