# Generated by Django 6.0 on 2026-06-11 19:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0157_quick_costing_opportunity_link'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='quickcosting',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quickcosting',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_quick_costings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='quickcosting',
            name='quotation_number',
            field=models.CharField(blank=True, db_index=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='quickcosting',
            name='quoted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quickcosting',
            name='quoted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quoted_quick_costings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='quickcosting',
            name='rejected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quickcosting',
            name='rejected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_quick_costings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='quickcosting',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('quoted', 'Quoted'), ('invoiced', 'Invoiced'), ('production', 'Production'), ('shipped', 'Shipped'), ('closed', 'Closed')], db_index=True, default='draft', max_length=20),
        ),
    ]
