# Generated by Django 6.0 on 2026-06-11 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0158_quick_costing_workflow'),
    ]

    operations = [
        migrations.AddField(
            model_name='quickcosting',
            name='costing_purpose',
            field=models.CharField(choices=[('sample', 'Sample'), ('bulk', 'Bulk Production')], db_index=True, default='bulk', max_length=20),
        ),
    ]
