# Generated by Django 6.0 on 2026-06-13 21:05

from decimal import Decimal
from django.db import migrations, models


def backfill_invoice_market(apps, schema_editor):
    Invoice = apps.get_model("crm", "Invoice")
    Invoice.objects.filter(invoice_region="BD").update(invoice_market="bangladesh")
    Invoice.objects.filter(currency="BDT").update(invoice_market="bangladesh")
    Invoice.objects.exclude(invoice_market="bangladesh").update(invoice_market="north_america")


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0160_costingheader_quotation_approved_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='deposit_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('50.00'), max_digits=6),
        ),
        migrations.AddField(
            model_name='invoice',
            name='invoice_market',
            field=models.CharField(choices=[('north_america', 'North America'), ('bangladesh', 'Bangladesh')], db_index=True, default='north_america', max_length=20),
        ),
        migrations.AddField(
            model_name='invoice',
            name='invoice_type',
            field=models.CharField(choices=[('sample', 'Sample'), ('bulk', 'Bulk Production'), ('sewing_charge', 'Sewing Charge')], db_index=True, default='bulk', max_length=20),
        ),
        migrations.RunPython(backfill_invoice_market, reverse_code=migrations.RunPython.noop),
    ]
