# Generated by Django 6.0 on 2026-06-15 20:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0161_invoice_market_type_deposit'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='quick_costing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='crm.quickcosting'),
        ),
    ]
