# Generated by Django 6.0 on 2026-06-16 02:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0162_invoice_quick_costing'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='production',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='crm.productionorder'),
        ),
    ]
