# Generated by Django 6.0 on 2026-06-16 20:28

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0163_event_production'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, default='Iconic Apparel House Inc.', max_length=200)),
                ('company_email', models.EmailField(blank=True, default='info@iconicapparelhouse.com', max_length=254)),
                ('company_phone', models.CharField(blank=True, default='604-500-6009', max_length=80)),
                ('website', models.CharField(blank=True, default='iconicapparelhouse.com', max_length=160)),
                ('slogan', models.CharField(blank=True, default='From Concept to Creation', max_length=255)),
                ('invoice_footer_note', models.CharField(blank=True, default='Iconic Apparel House Inc. Your Trusted Manufacturing Partner for Growth.', max_length=255)),
                ('authorized_by_name', models.CharField(blank=True, default='', max_length=160)),
                ('authorized_by_title', models.CharField(blank=True, default='', max_length=160)),
                ('paypal_email_or_id', models.CharField(blank=True, default='iconicapparelhouse', max_length=160)),
                ('paypal_qr_image', models.ImageField(blank=True, null=True, upload_to='invoice_settings/qr/')),
                ('etransfer_email', models.EmailField(blank=True, default='accounts@iconicapparelhouse.com', max_length=254)),
                ('canada_bank_name', models.CharField(blank=True, default='', max_length=160)),
                ('canada_account_name', models.CharField(blank=True, default='', max_length=160)),
                ('canada_account_number', models.CharField(blank=True, default='', max_length=120)),
                ('canada_transit_number', models.CharField(blank=True, default='', max_length=80)),
                ('canada_institution_number', models.CharField(blank=True, default='', max_length=80)),
                ('canada_wire_note', models.TextField(blank=True, default='')),
                ('canada_payment_terms', models.TextField(blank=True, default='')),
                ('bd_bank_name', models.CharField(blank=True, default='', max_length=160)),
                ('bd_account_name', models.CharField(blank=True, default='', max_length=160)),
                ('bd_account_number', models.CharField(blank=True, default='', max_length=120)),
                ('bd_branch', models.CharField(blank=True, default='', max_length=160)),
                ('bd_routing_number', models.CharField(blank=True, default='', max_length=80)),
                ('bd_swift', models.CharField(blank=True, default='', max_length=80)),
                ('bkash_number', models.CharField(blank=True, default='', max_length=80)),
                ('bkash_qr_image', models.ImageField(blank=True, null=True, upload_to='invoice_settings/qr/')),
                ('nagad_number', models.CharField(blank=True, default='', max_length=80)),
                ('nagad_qr_image', models.ImageField(blank=True, null=True, upload_to='invoice_settings/qr/')),
                ('rocket_number', models.CharField(blank=True, default='', max_length=80)),
                ('rocket_qr_image', models.ImageField(blank=True, null=True, upload_to='invoice_settings/qr/')),
                ('bd_payment_terms', models.TextField(blank=True, default='')),
                ('default_sample_deposit_percentage', models.DecimalField(decimal_places=2, default=Decimal('100.00'), max_digits=6)),
                ('default_bulk_deposit_percentage', models.DecimalField(decimal_places=2, default=Decimal('50.00'), max_digits=6)),
                ('default_bd_sewing_deposit_percentage', models.DecimalField(decimal_places=2, default=Decimal('50.00'), max_digits=6)),
                ('default_currency_na', models.CharField(blank=True, default='CAD', max_length=10)),
                ('default_currency_bd', models.CharField(blank=True, default='BDT', max_length=10)),
                ('default_tax_note', models.CharField(blank=True, default='', max_length=255)),
                ('terms_and_conditions_na', models.TextField(blank=True, default='')),
                ('terms_and_conditions_bd', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_invoice_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_active', '-updated_at', '-id'],
            },
        ),
    ]
