# Generated by Django 6.0 on 2026-06-18 18:39

import re
from django.db import migrations, models


SIZE_LABELS = (
    "YXS",
    "YS",
    "YM",
    "YL",
    "YXL",
    "XS",
    "S",
    "M",
    "L",
    "XL",
    "2XL",
    "3XL",
    "4XL",
    "5XL",
)


def _size_pattern(label):
    return re.compile(
        r"(?<![A-Z0-9])"
        + re.escape(label)
        + r"(?![A-Z0-9])\s*[:=]?\s*(\d+)",
        re.IGNORECASE,
    )


def _parse_line_quantity(size_ratio_note):
    text = (size_ratio_note or "").upper()
    if not text.strip():
        return None
    total = 0
    for label in SIZE_LABELS:
        match = _size_pattern(label).search(text)
        if match:
            total += int(match.group(1))
    return total or None


def backfill_production_line_quantity(apps, schema_editor):
    ProductionOrderLine = apps.get_model("crm", "ProductionOrderLine")
    updated = 0
    left_null = 0

    queryset = ProductionOrderLine.objects.filter(quantity__isnull=True).exclude(size_ratio_note="")
    for line in queryset.iterator():
        quantity = _parse_line_quantity(line.size_ratio_note)
        if quantity is None:
            left_null += 1
            continue
        line.quantity = quantity
        line.save(update_fields=["quantity"])
        updated += 1

    print(
        "ProductionOrderLine.quantity backfill: "
        f"{updated} line(s) updated from size_ratio_note; "
        f"{left_null} line(s) left null because quantity was not parseable."
    )


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0164_invoicesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionorderline',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.RunPython(backfill_production_line_quantity, noop_reverse),
    ]
