# Generated by Django 6.0 on 2026-06-27 03:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0166_quickcosting_detailed_currency_commission'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='productionorder',
            name='approved_costing_summary',
            field=models.JSONField(blank=True, default=dict, editable=False),
        ),
        migrations.AddField(
            model_name='productionorder',
            name='approved_currency',
            field=models.CharField(blank=True, choices=[('BDT', 'BDT'), ('CAD', 'CAD'), ('USD', 'USD')], editable=False, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='productionorder',
            name='approved_price_locked_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='productionorder',
            name='approved_selling_price',
            field=models.DecimalField(blank=True, decimal_places=4, editable=False, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='productionorder',
            name='approved_total_value',
            field=models.DecimalField(blank=True, decimal_places=4, editable=False, max_digits=16, null=True),
        ),
        migrations.AddField(
            model_name='productionorder',
            name='assigned_production_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_production_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productionorder',
            name='brand_name_snapshot',
            field=models.CharField(blank=True, default='', editable=False, max_length=200),
        ),
        migrations.AddField(
            model_name='productionorder',
            name='client_name_snapshot',
            field=models.CharField(blank=True, default='', editable=False, max_length=200),
        ),
        migrations.AddField(
            model_name='productionorder',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_production_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productionorder',
            name='product_name_snapshot',
            field=models.CharField(blank=True, default='', editable=False, max_length=200),
        ),
        migrations.AddField(
            model_name='productionorder',
            name='product_type_snapshot',
            field=models.CharField(blank=True, default='', editable=False, max_length=100),
        ),
        migrations.AddField(
            model_name='productionorder',
            name='quotation_number_snapshot',
            field=models.CharField(blank=True, default='', editable=False, max_length=50),
        ),
        migrations.AddField(
            model_name='productionorder',
            name='source_quotation',
            field=models.OneToOneField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auto_production_order', to='crm.costingheader'),
        ),
        migrations.AlterField(
            model_name='productionorder',
            name='operational_status',
            field=models.CharField(blank=True, choices=[('planning', 'Not Started'), ('pattern', 'Pattern'), ('sample_development', 'Sample'), ('sample_sent', 'Sample Sent'), ('approved', 'Approved'), ('fabric_sourcing', 'Fabric Sourcing'), ('cutting', 'Cutting'), ('sewing', 'Sewing'), ('printing', 'Print / Embroidery'), ('finishing', 'Finishing'), ('qc', 'Quality Check'), ('packing', 'Packing'), ('ready_to_ship', 'Ready To Ship'), ('shipped', 'Shipped'), ('on_hold', 'On Hold'), ('cancelled', 'Cancelled')], db_index=True, default='planning', max_length=32),
        ),
    ]
