# Generated by Django 6.0 on 2026-06-27 19:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('crm', '0167_production_order_quotation_snapshot'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CRMAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(db_index=True, max_length=40)),
                ('record_id', models.CharField(db_index=True, max_length=64)),
                ('record_label', models.CharField(blank=True, default='', max_length=220)),
                ('action_type', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('deleted', 'Deleted'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('converted', 'Converted'), ('payment_recorded', 'Payment Recorded'), ('status_changed', 'Status Changed')], db_index=True, max_length=30)),
                ('field_name', models.CharField(blank=True, default='', max_length=100)),
                ('previous_value', models.TextField(blank=True, default='')),
                ('new_value', models.TextField(blank=True, default='')),
                ('target_url', models.CharField(blank=True, default='', max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.AddField(
            model_name='automationnotification',
            name='assigned_role',
            field=models.CharField(blank=True, db_index=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='automationnotification',
            name='assigned_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='crm_notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='automationnotification',
            name='due_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='automationnotification',
            name='notification_type',
            field=models.CharField(choices=[('ceo_approval', 'CEO Approval'), ('production_due', 'Production Due'), ('shipping', 'Shipping'), ('invoice_overdue', 'Invoice Overdue'), ('general', 'General')], db_index=True, default='general', max_length=30),
        ),
        migrations.AlterField(
            model_name='automationnotification',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent'), ('critical', 'Critical')], db_index=True, default='normal', max_length=20),
        ),
        migrations.AddIndex(
            model_name='automationnotification',
            index=models.Index(fields=['assigned_user', 'is_resolved', 'is_read'], name='crm_automat_assigne_a68c8b_idx'),
        ),
        migrations.AddIndex(
            model_name='automationnotification',
            index=models.Index(fields=['assigned_role', 'is_resolved', 'is_read'], name='crm_automat_assigne_e188c7_idx'),
        ),
        migrations.AddField(
            model_name='crmauditlog',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_audit_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='crmauditlog',
            index=models.Index(fields=['module', 'record_id', '-created_at'], name='crm_crmaudi_module_3495e5_idx'),
        ),
        migrations.AddIndex(
            model_name='crmauditlog',
            index=models.Index(fields=['actor', '-created_at'], name='crm_crmaudi_actor_i_6ff9a0_idx'),
        ),
        migrations.AddIndex(
            model_name='crmauditlog',
            index=models.Index(fields=['action_type', '-created_at'], name='crm_crmaudi_action__891957_idx'),
        ),
    ]
