# Generated by Django 6.0 on 2026-06-27 23:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def create_employee_profiles(apps, schema_editor):
    User = apps.get_model(*settings.AUTH_USER_MODEL.split("."))
    Group = apps.get_model("auth", "Group")
    EmployeeProfile = apps.get_model("crm", "EmployeeProfile")
    groups = {
        name: Group.objects.get_or_create(name=name)[0]
        for name in (
            "CEO", "Manager", "Sales", "Merchandising", "Production", "Accounts",
            "Finance", "QC", "Warehouse", "HR", "Admin", "Read Only",
        )
    }
    ceo_variants = {"hossein", "hossain", "hussein", "hussain"}
    for user in User.objects.all().prefetch_related("groups"):
        display_name = user.first_name or user.username
        profile, _created = EmployeeProfile.objects.get_or_create(
            user=user,
            defaults={"display_name": display_name},
        )
        identifiers = {
            (user.username or "").casefold(),
            (user.first_name or "").casefold(),
            (profile.display_name or "").casefold(),
        }
        role_names = {group.name for group in user.groups.all()}
        if "CEO" in role_names and identifiers.intersection(ceo_variants):
            profile.display_name = "Hossein"
            profile.position = "ceo"
            profile.department = "management"
            profile.save(update_fields=["display_name", "position", "department", "updated_at"])
        if "talha" in identifiers:
            profile.display_name = "Talha"
            profile.position = "salesperson"
            profile.department = "sales"
            profile.save(update_fields=["display_name", "position", "department", "updated_at"])
            user.groups.add(groups["Sales"])
            user.groups.remove(groups["Production"])


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0168_operations_control_center'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='leadcomment',
            name='author_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chatter_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='automationnotification',
            name='notification_type',
            field=models.CharField(choices=[('ceo_approval', 'CEO Approval'), ('production_due', 'Production Due'), ('shipping', 'Shipping'), ('invoice_overdue', 'Invoice Overdue'), ('mention', 'Mention'), ('general', 'General')], db_index=True, default='general', max_length=30),
        ),
        migrations.CreateModel(
            name='EmployeeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('phone', models.CharField(blank=True, default='', max_length=50)),
                ('employee_id', models.CharField(blank=True, max_length=40, null=True, unique=True)),
                ('position', models.CharField(blank=True, choices=[('ceo', 'CEO'), ('director', 'Director'), ('general_manager', 'General Manager'), ('sales_manager', 'Sales Manager'), ('salesperson', 'Salesperson'), ('merchandiser', 'Merchandiser'), ('merchandising_manager', 'Merchandising Manager'), ('production_manager', 'Production Manager'), ('production_supervisor', 'Production Supervisor'), ('accounts_manager', 'Accounts Manager'), ('accounts_officer', 'Accounts Officer'), ('qc_manager', 'QC Manager'), ('qc_inspector', 'QC Inspector'), ('warehouse_manager', 'Warehouse Manager'), ('warehouse_officer', 'Warehouse Officer'), ('hr_manager', 'HR Manager'), ('hr_officer', 'HR Officer'), ('admin', 'Admin'), ('customer_service', 'Customer Service'), ('graphic_designer', 'Graphic Designer'), ('pattern_master', 'Pattern Master'), ('sample_coordinator', 'Sample Coordinator')], default='', max_length=40)),
                ('department', models.CharField(blank=True, choices=[('management', 'Management'), ('sales', 'Sales'), ('merchandising', 'Merchandising'), ('production', 'Production'), ('accounts', 'Accounts'), ('finance', 'Finance'), ('qc', 'QC'), ('warehouse', 'Warehouse'), ('hr', 'HR'), ('admin', 'Admin'), ('customer_service', 'Customer Service'), ('design', 'Design')], default='', max_length=40)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='employee_profiles/')),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_employee_profiles', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('display_name', 'user__username'),
                'permissions': [('manage_employee_profiles', 'Can manage employee profiles and roles'), ('view_all_sales_profiles', 'Can view all salesperson profiles')],
            },
        ),
        migrations.RunPython(create_employee_profiles, migrations.RunPython.noop),
    ]
