# Generated by Django 6.0 on 2026-06-28 01:19

from django.db import migrations, models
from django.db.models import Q
from django.utils import timezone


def normalize_notification_history(apps, schema_editor):
    Notification = apps.get_model("crm", "AutomationNotification")
    Notification.objects.filter(priority="low").update(priority="information")
    Notification.objects.filter(priority="urgent").update(priority="critical")
    legacy_generated = Q(source_key__startswith="crm-auto:")
    for prefix in (
        "operations:production_due:",
        "operations:ready_to_ship:",
        "operations:shipment_due:",
    ):
        legacy_generated |= Q(source_key__startswith=prefix)
    Notification.objects.filter(legacy_generated, is_resolved=False).update(
        is_resolved=True,
        resolved_at=timezone.now(),
    )


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0169_employee_profiles_multi_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automationnotification',
            name='notification_type',
            field=models.CharField(choices=[('ceo_approval', 'CEO Approval Required'), ('ceo_approved', 'CEO Approved Quotation'), ('ceo_rejected', 'CEO Rejected Quotation'), ('production_created', 'Production Order Created'), ('sample_due', 'Sample Due'), ('production_due', 'Production Overdue'), ('shipment_due', 'Shipment Due Today'), ('shipment_delayed', 'Shipment Delayed'), ('invoice_overdue', 'Invoice Overdue'), ('task_assigned', 'Task Assigned'), ('task_completed', 'Task Completed'), ('comment_added', 'Comment Added'), ('mention', 'Mention'), ('general', 'General')], db_index=True, default='general', max_length=30),
        ),
        migrations.AlterField(
            model_name='automationnotification',
            name='priority',
            field=models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('normal', 'Normal'), ('information', 'Information')], db_index=True, default='normal', max_length=20),
        ),
        migrations.RunPython(normalize_notification_history, migrations.RunPython.noop),
    ]
