# Generated by Django 6.0 on 2026-06-28 05:22

from django.db import migrations, models


def backfill_employee_structure(apps, schema_editor):
    EmployeeProfile = apps.get_model("crm", "EmployeeProfile")
    EmployeeIdSequence = apps.get_model("crm", "EmployeeIdSequence")
    Group = apps.get_model("auth", "Group")

    position_map = {
        "salesperson": "sales_executive",
        "production_supervisor": "production_coordinator",
        "accounts_officer": "accountant",
        "qc_manager": "quality_controller",
        "qc_inspector": "quality_controller",
        "warehouse_manager": "operations_manager",
        "warehouse_officer": "staff",
        "hr_manager": "administrator",
        "hr_officer": "staff",
        "admin": "administrator",
        "graphic_designer": "staff",
        "pattern_master": "staff",
        "sample_coordinator": "production_coordinator",
    }
    department_map = {
        "finance": "accounts",
        "qc": "quality_control",
        "warehouse": "logistics",
        "hr": "administration",
        "admin": "administration",
        "design": "marketing",
    }

    used_ids = set(
        EmployeeProfile.objects.exclude(employee_id__isnull=True)
        .exclude(employee_id="")
        .values_list("employee_id", flat=True)
    )
    sequence_value = 0
    for employee_id in used_ids:
        if employee_id.startswith("EMP") and employee_id[3:].isdigit():
            sequence_value = max(sequence_value, int(employee_id[3:]))

    for profile in EmployeeProfile.objects.order_by("created_at", "pk"):
        changed = []
        if not profile.employee_id:
            sequence_value += 1
            candidate = f"EMP{sequence_value:04d}"
            while candidate in used_ids:
                sequence_value += 1
                candidate = f"EMP{sequence_value:04d}"
            profile.employee_id = candidate
            used_ids.add(candidate)
            changed.append("employee_id")
        normalized_position = position_map.get(profile.position)
        if normalized_position:
            profile.position = normalized_position
            changed.append("position")
        normalized_department = department_map.get(profile.department)
        if normalized_department:
            profile.department = normalized_department
            changed.append("department")
        if changed:
            profile.save(update_fields=changed)

    EmployeeIdSequence.objects.update_or_create(
        key="employee",
        defaults={"last_value": sequence_value},
    )
    for role_name in ("Director", "Merchandiser", "Supervisor"):
        Group.objects.get_or_create(name=role_name)


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0171_employee_status_and_retention'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeIdSequence',
            fields=[
                ('key', models.CharField(default='employee', max_length=30, primary_key=True, serialize=False)),
                ('last_value', models.PositiveBigIntegerField(default=0)),
            ],
        ),
        migrations.RunPython(backfill_employee_structure, migrations.RunPython.noop),
        migrations.AddField(
            model_name='leadcomment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='closed_won_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='department',
            field=models.CharField(blank=True, choices=[('management', 'Management'), ('sales', 'Sales'), ('merchandising', 'Merchandising'), ('production', 'Production'), ('accounts', 'Accounts'), ('administration', 'Administration'), ('quality_control', 'Quality Control'), ('logistics', 'Logistics'), ('it', 'IT'), ('marketing', 'Marketing'), ('customer_service', 'Customer Service')], default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='employee_id',
            field=models.CharField(editable=False, max_length=40, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='position',
            field=models.CharField(blank=True, choices=[('ceo', 'CEO'), ('director', 'Director'), ('general_manager', 'General Manager'), ('operations_manager', 'Operations Manager'), ('sales_manager', 'Sales Manager'), ('production_manager', 'Production Manager'), ('merchandising_manager', 'Merchandising Manager'), ('accounts_manager', 'Accounts Manager'), ('sales_executive', 'Sales Executive'), ('merchandiser', 'Merchandiser'), ('production_coordinator', 'Production Coordinator'), ('quality_controller', 'Quality Controller'), ('accountant', 'Accountant'), ('customer_service', 'Customer Service'), ('administrator', 'Administrator'), ('staff', 'Staff'), ('other', 'Other')], default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('on_leave', 'On Leave'), ('suspended', 'Suspended'), ('resigned', 'Resigned'), ('inactive', 'Inactive')], default='active', max_length=20),
        ),
    ]
