# Generated by Django 6.0 on 2026-06-28 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0172_employee_profiles_final_polish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeprofile',
            name='employee_id',
            field=models.CharField(editable=False, max_length=40, unique=True),
        ),
    ]
