# Generated by Django 6.0 on 2026-06-28 07:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


POSITIONS = (
    ("ceo", "CEO"),
    ("director", "Director"),
    ("general_manager", "General Manager"),
    ("sales_manager", "Sales Manager"),
    ("sales_executive", "Sales Executive"),
    ("merchandiser", "Merchandiser"),
    ("senior_merchandiser", "Senior Merchandiser"),
    ("production_manager", "Production Manager"),
    ("production_executive", "Production Executive"),
    ("qc_manager", "QC Manager"),
    ("quality_inspector", "Quality Inspector"),
    ("accounts_manager", "Accounts Manager"),
    ("accounts_executive", "Accounts Executive"),
    ("hr", "HR"),
    ("administrator", "Administrator"),
    ("designer", "Designer"),
    ("pattern_master", "Pattern Master"),
    ("sampling_coordinator", "Sampling Coordinator"),
    ("warehouse", "Warehouse"),
    ("shipping", "Shipping"),
    ("factory_manager", "Factory Manager"),
)

DEPARTMENTS = (
    ("sales", "Sales"),
    ("merchandising", "Merchandising"),
    ("production", "Production"),
    ("quality", "Quality"),
    ("accounts", "Accounts"),
    ("hr", "HR"),
    ("management", "Management"),
    ("warehouse", "Warehouse"),
    ("shipping", "Shipping"),
    ("administration", "Administration"),
)


def seed_platform_libraries(apps, schema_editor):
    Position = apps.get_model("crm", "Position")
    Department = apps.get_model("crm", "Department")
    EmployeeProfile = apps.get_model("crm", "EmployeeProfile")
    Group = apps.get_model("auth", "Group")
    CRMSetting = apps.get_model("crm", "CRMSetting")

    positions = {}
    for sort_order, (code, name) in enumerate(POSITIONS, start=1):
        positions[code], _created = Position.objects.update_or_create(
            code=code,
            defaults={"name": name, "sort_order": sort_order, "is_active": True},
        )
    departments = {}
    for sort_order, (code, name) in enumerate(DEPARTMENTS, start=1):
        departments[code], _created = Department.objects.update_or_create(
            code=code,
            defaults={"name": name, "sort_order": sort_order, "is_active": True},
        )

    position_aliases = {
        "operations_manager": "general_manager",
        "merchandising_manager": "senior_merchandiser",
        "production_coordinator": "production_executive",
        "quality_controller": "quality_inspector",
        "accountant": "accounts_executive",
        "staff": "production_executive",
    }
    department_aliases = {
        "quality_control": "quality",
        "logistics": "shipping",
        "it": "administration",
        "marketing": "sales",
        "customer_service": "administration",
    }
    for profile in EmployeeProfile.objects.all().iterator():
        position_code = position_aliases.get(profile.position, profile.position)
        department_code = department_aliases.get(profile.department, profile.department)
        updates = {}
        if position_code in positions:
            updates["position_ref_id"] = positions[position_code].pk
        if department_code in departments:
            updates["department_ref_id"] = departments[department_code].pk
        if updates:
            EmployeeProfile.objects.filter(pk=profile.pk).update(**updates)

    for role in (
        "CEO", "Director", "Manager", "Sales Manager", "Sales", "Merchandising",
        "Merchandiser", "Production", "Accounts", "Finance", "QC", "Warehouse",
        "Supervisor", "HR", "Admin", "Read Only",
    ):
        Group.objects.get_or_create(name=role)

    settings_rows = (
        ("currencies", "bdt", "BDT", {"code": "BDT", "symbol": "৳"}),
        ("currencies", "cad", "CAD", {"code": "CAD", "symbol": "$"}),
        ("currencies", "usd", "USD", {"code": "USD", "symbol": "$"}),
        ("approval_rules", "quotation_ceo", "Quotation CEO approval", {"enabled": True}),
        ("notification_types", "crm_events", "CRM notification types", {"managed_by": "existing notification rules"}),
        ("status_lists", "lead", "Lead statuses", {"source": "Lead.LEAD_STATUS_CHOICES"}),
        ("status_lists", "production", "Production statuses", {"source": "ProductionOrder.OPERATIONAL_STATUS_CHOICES"}),
        ("status_lists", "invoice", "Invoice statuses", {"source": "Invoice.STATUS_CHOICES"}),
        ("company", "profile", "Company information", {}),
        ("tax", "defaults", "Tax settings", {}),
    )
    for category, key, label, value in settings_rows:
        CRMSetting.objects.get_or_create(
            category=category,
            key=key,
            defaults={"label": label, "value": value},
        )


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('crm', '0173_employee_id_required'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=60, unique=True)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ('sort_order', 'name'),
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=60, unique=True)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ('sort_order', 'name'),
            },
        ),
        migrations.AddField(
            model_name='costingheader',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='costingheader',
            name='archived_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archived_quotations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='costingheader',
            name='is_archived',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='customer',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='archived_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archived_customers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customer',
            name='is_archived',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='invoice',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='archived_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archived_invoices', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='invoice',
            name='is_archived',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='department_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='crm.department'),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='position_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='crm.position'),
        ),
        migrations.CreateModel(
            name='UserDashboardPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hidden_widgets', models.JSONField(blank=True, default=list)),
                ('widget_order', models.JSONField(blank=True, default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_preference', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CRMSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(db_index=True, max_length=40)),
                ('key', models.SlugField(max_length=80)),
                ('label', models.CharField(max_length=140)),
                ('value', models.JSONField(blank=True, default=dict)),
                ('description', models.CharField(blank=True, default='', max_length=240)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_crm_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('category', 'label'),
                'constraints': [models.UniqueConstraint(fields=('category', 'key'), name='crm_setting_category_key')],
            },
        ),
        migrations.CreateModel(
            name='FavoriteRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveBigIntegerField()),
                ('record_type', models.CharField(max_length=40)),
                ('record_label', models.CharField(max_length=220)),
                ('target_url', models.CharField(max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crm_favorites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at', '-id'),
                'indexes': [models.Index(fields=['user', '-created_at'], name='crm_favorit_user_id_e941b1_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'content_type', 'object_id'), name='crm_favorite_user_record')],
            },
        ),
        migrations.CreateModel(
            name='RecentlyViewedRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveBigIntegerField()),
                ('record_type', models.CharField(max_length=40)),
                ('record_label', models.CharField(max_length=220)),
                ('target_url', models.CharField(max_length=300)),
                ('viewed_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crm_recent_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-viewed_at', '-id'),
                'indexes': [models.Index(fields=['user', '-viewed_at'], name='crm_recentl_user_id_51ac2e_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'content_type', 'object_id'), name='crm_recent_user_record')],
            },
        ),
        migrations.CreateModel(
            name='RecentSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=160)),
                ('normalized_query', models.CharField(max_length=160)),
                ('search_count', models.PositiveIntegerField(default=1)),
                ('searched_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crm_recent_searches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-searched_at', '-id'),
                'indexes': [models.Index(fields=['user', '-searched_at'], name='crm_recents_user_id_65d33a_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'normalized_query'), name='crm_recent_search_user_query')],
            },
        ),
        migrations.CreateModel(
            name='SavedFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(db_index=True, max_length=40)),
                ('name', models.CharField(max_length=120)),
                ('query_params', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crm_saved_filters', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('module', 'name'),
                'constraints': [models.UniqueConstraint(fields=('user', 'module', 'name'), name='crm_saved_filter_user_module_name')],
            },
        ),
        migrations.RunPython(seed_platform_libraries, migrations.RunPython.noop),
    ]
