# Generated by Django 5.2.8 on 2026-06-29 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0174_department_position_costingheader_archived_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='aliases',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
