# Generated by Django 5.2.8 on 2026-07-07 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0180_quickcosting_local_sewing_workflow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunity',
            name='order_currency',
            field=models.CharField(choices=[('CAD', 'CAD'), ('USD', 'USD'), ('BDT', 'BDT')], default='CAD', max_length=3),
        ),
        migrations.AlterField(
            model_name='quickcosting',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted for Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('quoted', 'Quoted'), ('invoiced', 'Invoiced'), ('production', 'Production'), ('shipped', 'Shipped'), ('closed', 'Closed')], db_index=True, default='draft', max_length=20),
        ),
    ]
