# Generated by Django 6.0 on 2026-07-10 00:50

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


def backfill_salesperson_and_legacy_commission(apps, schema_editor):
    Opportunity = apps.get_model('crm', 'Opportunity')
    QuickCosting = apps.get_model('crm', 'QuickCosting')

    for opportunity in (
        Opportunity.objects
        .filter(assigned_to__isnull=True, lead__isnull=False, lead__assigned_to__isnull=False)
        .select_related('lead')
        .iterator()
    ):
        opportunity.assigned_to_id = opportunity.lead.assigned_to_id
        opportunity.save(update_fields=['assigned_to'])

    for costing in QuickCosting.objects.select_related('opportunity', 'opportunity__lead').iterator():
        update_fields = []
        if not costing.salesperson_id:
            salesperson_id = None
            if costing.opportunity_id:
                salesperson_id = (
                    getattr(costing.opportunity, 'assigned_to_id', None)
                    or getattr(getattr(costing.opportunity, 'lead', None), 'assigned_to_id', None)
                )
            if salesperson_id:
                costing.salesperson_id = salesperson_id
                update_fields.append('salesperson')

        legacy_total = Decimal('0')
        quantity = Decimal(costing.quantity or 0)
        if costing.commission_percent is not None and costing.commission_percent > 0:
            legacy_total = (
                (costing.selling_price_per_piece or Decimal('0'))
                * quantity
                * costing.commission_percent
                / Decimal('100')
            ).quantize(Decimal('0.01'))
        elif costing.commission_per_piece is not None and costing.commission_per_piece > 0:
            legacy_total = ((costing.commission_per_piece or Decimal('0')) * quantity).quantize(Decimal('0.01'))

        if legacy_total > 0:
            costing.commission_type = 'fixed'
            costing.commission_value = legacy_total
            costing.commission_currency = (costing.currency or 'BDT').upper()
            update_fields.extend(['commission_type', 'commission_value', 'commission_currency'])

        if update_fields:
            costing.save(update_fields=sorted(set(update_fields)))


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0182_invoice_opportunity_link'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_opportunities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='quickcosting',
            name='commission_currency',
            field=models.CharField(choices=[('BDT', 'BDT'), ('CAD', 'CAD'), ('USD', 'USD')], default='BDT', max_length=3),
        ),
        migrations.AddField(
            model_name='quickcosting',
            name='commission_type',
            field=models.CharField(choices=[('none', 'None'), ('fixed', 'Fixed Amount'), ('percentage', 'Percentage')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='quickcosting',
            name='commission_value',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), max_digits=12),
        ),
        migrations.AddField(
            model_name='quickcosting',
            name='salesperson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_quick_costings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opportunities', to='crm.lead'),
        ),
        migrations.RunPython(backfill_salesperson_and_legacy_commission, noop_reverse),
    ]
