# Generated by Django 5.2.8 on 2026-07-10 17:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0183_opportunity_assigned_to_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='quickcosting',
            name='previous_revision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_revisions', to='crm.quickcosting'),
        ),
        migrations.AddField(
            model_name='quickcosting',
            name='recall_previous_status',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='quickcosting',
            name='recall_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='quickcosting',
            name='quotation_revision_required',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='quickcosting',
            name='quotation_revision_required_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quickcosting',
            name='recall_rejected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quickcosting',
            name='recall_rejected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quick_costing_recall_rejections', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='quickcosting',
            name='recall_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quickcosting',
            name='recall_requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quick_costing_recall_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='quickcosting',
            name='recalled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quickcosting',
            name='recalled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quick_costings_recalled', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='quickcosting',
            name='revision_number',
            field=models.PositiveIntegerField(db_index=True, default=1),
        ),
        migrations.AddField(
            model_name='quickcosting',
            name='revision_root',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revision_children', to='crm.quickcosting'),
        ),
        migrations.AddField(
            model_name='quickcosting',
            name='superseded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='superseded_versions', to='crm.quickcosting'),
        ),
        migrations.AlterField(
            model_name='quickcosting',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Pending Approval'), ('approved', 'CEO Approved'), ('rejected', 'Rejected'), ('recall_requested', 'Recall Requested'), ('recalled', 'Recalled'), ('superseded', 'Superseded'), ('quoted', 'Quoted'), ('invoiced', 'Invoiced'), ('production', 'Production'), ('shipped', 'Shipped'), ('closed', 'Closed')], db_index=True, default='draft', max_length=20),
        ),
    ]
