# Generated by Django 5.2.8 on 2026-07-15 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0184_quick_costing_recall_workflow'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='invoice_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='opportunity_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
    ]
