# Generated by Django 5.2.8 on 2026-07-17 19:33

from django.db import migrations, models
from django.db.models import F, Q


REPAIRED_OPPORTUNITY_IDS = [83, 84, 88, 89, 185]


def move_repaired_opportunities_awaiting_payment(apps, schema_editor):
    Opportunity = apps.get_model("crm", "Opportunity")
    Invoice = apps.get_model("crm", "Invoice")
    ProductionOrder = apps.get_model("crm", "ProductionOrder")

    candidates = Opportunity.objects.filter(
        id__in=REPAIRED_OPPORTUNITY_IDS,
        stage__in=["Proposal", "Negotiation"],
        is_archived=False,
    )
    for opportunity in candidates:
        has_production = ProductionOrder.objects.filter(
            opportunity_id=opportunity.id,
            is_archived=False,
        ).exists()
        if has_production:
            continue
        has_open_invoice = (
            Invoice.objects.filter(is_archived=False)
            .exclude(status="cancelled")
            .filter(
                Q(opportunity_id=opportunity.id)
                | Q(quick_costing__opportunity_id=opportunity.id)
                | Q(costing_header__opportunity_id=opportunity.id)
                | Q(order__opportunity_id=opportunity.id)
            )
            .filter(total_amount__gt=F("paid_amount"))
            .exists()
        )
        if has_open_invoice:
            Opportunity.objects.filter(pk=opportunity.pk).update(stage="Awaiting Payment")


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0185_historical_revenue_dates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunity',
            name='stage',
            field=models.CharField(choices=[('Prospecting', 'Prospecting'), ('Qualification', 'Qualification'), ('Needs Analysis', 'Needs Analysis'), ('Proposal', 'Proposal or Quote'), ('Negotiation', 'Negotiation'), ('Awaiting Payment', 'Awaiting Payment'), ('Sampling', 'Sampling'), ('Production', 'Production'), ('Shipment Complete', 'Shipment Complete'), ('Closed Won', 'Closed Won'), ('Closed Lost', 'Closed Lost')], default='Prospecting', max_length=50),
        ),
        migrations.RunPython(move_repaired_opportunities_awaiting_payment, noop_reverse),
    ]
