# Generated by Codex on 2026-07-21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0186_add_awaiting_payment_opportunity_stage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productreferenceimage",
            name="lead",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product_reference_images",
                to="crm.lead",
            ),
        ),
        migrations.AddConstraint(
            model_name="productreferenceimage",
            constraint=models.UniqueConstraint(
                condition=models.Q(opportunity__isnull=False),
                fields=("opportunity", "slot"),
                name="uniq_product_reference_image_opportunity_slot",
            ),
        ),
    ]
