# Generated by Django 5.2.8 on 2026-07-25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0187_product_reference_images_six_slots"),
    ]

    operations = [
        migrations.AddField(
            model_name="shipment",
            name="estimated_delivery_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
