# Generated by Django 5.2.8 on 2026-07-27 00:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def map_legacy_inactive_catalog_rows(apps, schema_editor):
    for model_name in ("Product", "Fabric", "Accessory", "Trim", "ThreadOption"):
        Model = apps.get_model("crm", model_name)
        Model.objects.filter(is_active=False).update(status="Archived")


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('crm', '0188_shipment_estimated_delivery_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='accessory',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='accessory',
            name='archived_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archived_catalog_accessories', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='accessory',
            name='best_use',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='accessory',
            name='image_2',
            field=models.ImageField(blank=True, null=True, upload_to='accessory_images/'),
        ),
        migrations.AddField(
            model_name='accessory',
            name='image_3',
            field=models.ImageField(blank=True, null=True, upload_to='accessory_images/'),
        ),
        migrations.AddField(
            model_name='accessory',
            name='internal_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='accessory',
            name='internal_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='accessory',
            name='status',
            field=models.CharField(choices=[('Available', 'Available'), ('Special Order', 'Special Order'), ('Development', 'Development'), ('Not Available', 'Not Available'), ('Archived', 'Archived')], db_index=True, default='Available', max_length=40),
        ),
        migrations.AddField(
            model_name='accessory',
            name='suggested_selling_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='accessory',
            name='tags',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='fabric',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fabric',
            name='archived_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archived_catalog_fabrics', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fabric',
            name='best_use',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='fabric',
            name='image_2',
            field=models.ImageField(blank=True, null=True, upload_to='fabric_images/'),
        ),
        migrations.AddField(
            model_name='fabric',
            name='image_3',
            field=models.ImageField(blank=True, null=True, upload_to='fabric_images/'),
        ),
        migrations.AddField(
            model_name='fabric',
            name='internal_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='fabric',
            name='internal_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='fabric',
            name='status',
            field=models.CharField(choices=[('Available', 'Available'), ('Special Order', 'Special Order'), ('Development', 'Development'), ('Not Available', 'Not Available'), ('Archived', 'Archived')], db_index=True, default='Available', max_length=40),
        ),
        migrations.AddField(
            model_name='fabric',
            name='suggested_selling_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='fabric',
            name='tags',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='product',
            name='accessories',
            field=models.ManyToManyField(blank=True, related_name='catalog_products', to='crm.accessory'),
        ),
        migrations.AddField(
            model_name='product',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='archived_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archived_catalog_products', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='product',
            name='available_colours',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='product',
            name='fit',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='image_2',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_3',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/'),
        ),
        migrations.AddField(
            model_name='product',
            name='internal_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='internal_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='product',
            name='main_colour',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='main_decoration',
            field=models.CharField(blank=True, choices=[('Screen Print', 'Screen Print'), ('DTF', 'DTF'), ('Embroidery', 'Embroidery'), ('Puff Print', 'Puff Print'), ('Silicone Print', 'Silicone Print'), ('Applique', 'Applique'), ('Sublimation', 'Sublimation'), ('Heat Transfer', 'Heat Transfer'), ('None', 'None'), ('Other', 'Other')], default='None', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='main_fabric',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='catalog_products', to='crm.fabric'),
        ),
        migrations.AddField(
            model_name='product',
            name='short_description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='product',
            name='size_range',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('Available', 'Available'), ('Sample Available', 'Sample Available'), ('Development', 'Development'), ('Previously Produced', 'Previously Produced'), ('Archived', 'Archived')], db_index=True, default='Available', max_length=40),
        ),
        migrations.AddField(
            model_name='product',
            name='suggested_selling_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='tags',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='product',
            name='threads',
            field=models.ManyToManyField(blank=True, related_name='catalog_products', to='crm.threadoption'),
        ),
        migrations.AddField(
            model_name='product',
            name='trims',
            field=models.ManyToManyField(blank=True, related_name='catalog_products', to='crm.trim'),
        ),
        migrations.AddField(
            model_name='threadoption',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='threadoption',
            name='archived_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archived_catalog_threads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='threadoption',
            name='best_use',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='threadoption',
            name='image_2',
            field=models.ImageField(blank=True, null=True, upload_to='thread_images/'),
        ),
        migrations.AddField(
            model_name='threadoption',
            name='image_3',
            field=models.ImageField(blank=True, null=True, upload_to='thread_images/'),
        ),
        migrations.AddField(
            model_name='threadoption',
            name='internal_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='threadoption',
            name='internal_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='threadoption',
            name='status',
            field=models.CharField(choices=[('Available', 'Available'), ('Special Order', 'Special Order'), ('Development', 'Development'), ('Not Available', 'Not Available'), ('Archived', 'Archived')], db_index=True, default='Available', max_length=40),
        ),
        migrations.AddField(
            model_name='threadoption',
            name='suggested_selling_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='threadoption',
            name='tags',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='trim',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trim',
            name='archived_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archived_catalog_trims', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trim',
            name='best_use',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='trim',
            name='image_2',
            field=models.ImageField(blank=True, null=True, upload_to='trim_images/'),
        ),
        migrations.AddField(
            model_name='trim',
            name='image_3',
            field=models.ImageField(blank=True, null=True, upload_to='trim_images/'),
        ),
        migrations.AddField(
            model_name='trim',
            name='internal_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='trim',
            name='internal_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='trim',
            name='status',
            field=models.CharField(choices=[('Available', 'Available'), ('Special Order', 'Special Order'), ('Development', 'Development'), ('Not Available', 'Not Available'), ('Archived', 'Archived')], db_index=True, default='Available', max_length=40),
        ),
        migrations.AddField(
            model_name='trim',
            name='suggested_selling_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='trim',
            name='tags',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.RunPython(map_legacy_inactive_catalog_rows, migrations.RunPython.noop),
        migrations.CreateModel(
            name='LivingCatalogAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveBigIntegerField()),
                ('item_type', models.CharField(db_index=True, max_length=40)),
                ('action', models.CharField(choices=[('created', 'Record created'), ('edited', 'Record edited'), ('image_added', 'Image added'), ('image_replaced', 'Image replaced'), ('image_removed', 'Image removed'), ('status_changed', 'Status changed'), ('archived', 'Record archived'), ('restored', 'Record restored')], db_index=True, max_length=32)),
                ('summary', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='living_catalog_audits', to=settings.AUTH_USER_MODEL)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['item_type', 'object_id', '-created_at'], name='crm_livingc_item_ty_46c39e_idx'), models.Index(fields=['action', '-created_at'], name='crm_livingc_action_84817b_idx')],
            },
        ),
    ]
