# Generated by Django 5.2.8 on 2026-07-27 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0189_living_catalog'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccess',
            name='can_edit_library',
            field=models.BooleanField(default=False),
        ),
    ]
