# Generated by Django 5.2.8 on 2026-07-27 17:50

from django.db import migrations, models


def seed_library_permission_controls(apps, schema_editor):
    UserAccess = apps.get_model("crm", "UserAccess")
    EmployeeProfile = apps.get_model("crm", "EmployeeProfile")

    profiles = {
        profile.user_id: profile
        for profile in EmployeeProfile.objects.only("user_id", "department", "position")
    }

    for access in UserAccess.objects.select_related("user").all():
        user = access.user
        profile = profiles.get(user.id)
        position = (getattr(profile, "position", "") or "").strip().lower() if profile else ""
        department = (getattr(profile, "department", "") or "").strip().lower() if profile else ""
        groups = {name.strip().lower() for name in user.groups.values_list("name", flat=True)}

        is_ceo = position == "ceo" or "ceo" in groups or getattr(access, "can_view_ceo_tools", False)
        is_director = position == "director" or "director" in groups
        is_production_manager = position == "production_manager" or "production manager" in groups
        is_factory_manager = position == "factory_manager" or "factory manager" in groups
        is_approved_manager = position == "approved_manager" or "approved manager" in groups
        is_sales = department == "sales" or position in {"sales_manager", "sales_executive"} or groups.intersection({"sales", "sales manager"})
        is_accounts = department == "accounts" or position in {"accounts_manager", "accountant"} or groups.intersection({"accounts", "finance"})
        is_marketing = department == "marketing" or "marketing" in groups

        view = bool(access.can_library)
        add = False
        edit = bool(access.can_edit_library)
        upload = bool(access.can_edit_library)
        remove = False
        archive = False
        presentation = bool(access.can_library)
        pricing = bool(getattr(access, "can_view_internal_costing", False))

        if user.is_superuser or is_ceo or is_director:
            view = add = edit = upload = remove = archive = presentation = pricing = True
        elif is_production_manager or is_factory_manager or is_approved_manager:
            view = add = edit = upload = remove = presentation = True
        elif is_sales:
            view = presentation = True
        elif is_accounts:
            view = pricing = True
        elif is_marketing:
            view = presentation = True

        if edit or add or upload or remove or archive or presentation or pricing:
            view = True

        access.can_library = view
        access.can_add_library = add
        access.can_edit_library = edit
        access.can_upload_library_images = upload
        access.can_remove_library_images = remove
        access.can_archive_library = archive
        access.can_use_library_presentation = presentation
        access.can_view_library_pricing = pricing
        access.save(
            update_fields=[
                "can_library",
                "can_add_library",
                "can_edit_library",
                "can_upload_library_images",
                "can_remove_library_images",
                "can_archive_library",
                "can_use_library_presentation",
                "can_view_library_pricing",
                "updated_at",
            ]
        )


def reverse_library_permission_controls(apps, schema_editor):
    # Removing the fields through migration rollback is enough; do not mutate legacy flags.
    return


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0190_useraccess_can_edit_library'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccess',
            name='can_add_library',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='useraccess',
            name='can_archive_library',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='useraccess',
            name='can_remove_library_images',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='useraccess',
            name='can_upload_library_images',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='useraccess',
            name='can_use_library_presentation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='useraccess',
            name='can_view_library_pricing',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(seed_library_permission_controls, reverse_library_permission_controls),
    ]
