# Generated by Django 5.2.8 on 2026-07-28 21:31

import django.core.validators
import django.db.models.deletion
import django.db.models.expressions
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0191_library_permission_controls'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KPIRoleTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=80, unique=True)),
                ('name', models.CharField(max_length=140, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_kpi_role_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('name',),
                'indexes': [models.Index(fields=['is_active', 'name'], name='kpi_role_active_name_idx')],
            },
        ),
        migrations.CreateModel(
            name='KPISettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(unique=True)),
                ('is_active', models.BooleanField(db_index=True, default=False)),
                ('green_min', models.DecimalField(decimal_places=2, default=Decimal('85.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))])),
                ('green_max', models.DecimalField(decimal_places=2, default=Decimal('100.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))])),
                ('yellow_min', models.DecimalField(decimal_places=2, default=Decimal('70.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))])),
                ('yellow_max', models.DecimalField(decimal_places=2, default=Decimal('84.99'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))])),
                ('red_min', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))])),
                ('red_max', models.DecimalField(decimal_places=2, default=Decimal('69.99'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))])),
                ('individual_bonus_weight', models.DecimalField(decimal_places=2, default=Decimal('60.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))])),
                ('team_bonus_weight', models.DecimalField(decimal_places=2, default=Decimal('25.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))])),
                ('company_bonus_weight', models.DecimalField(decimal_places=2, default=Decimal('15.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))])),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_kpi_settings_versions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-version',),
                'constraints': [
                    models.CheckConstraint(condition=models.Q(('version__gte', 1)), name='kpi_settings_version_pos'),
                    models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('is_active',), name='kpi_settings_one_active'),
                    models.CheckConstraint(condition=models.Q(('red_min', Decimal('0.00')), ('red_min__lte', models.F('red_max')), ('yellow_min', django.db.models.expressions.CombinedExpression(models.F('red_max'), '+', models.Value(Decimal('0.01')))), ('yellow_min__lte', models.F('yellow_max')), ('green_min', django.db.models.expressions.CombinedExpression(models.F('yellow_max'), '+', models.Value(Decimal('0.01')))), ('green_min__lte', models.F('green_max')), ('green_max', Decimal('100.00'))), name='kpi_settings_ranges_ordered'),
                    models.CheckConstraint(condition=models.Q(('individual_bonus_weight__gte', 0), ('individual_bonus_weight__lte', 100), ('team_bonus_weight__gte', 0), ('team_bonus_weight__lte', 100), ('company_bonus_weight__gte', 0), ('company_bonus_weight__lte', 100)), name='kpi_settings_bonus_ranges'),
                    models.CheckConstraint(condition=models.Q(('individual_bonus_weight', django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(models.Value(Decimal('100.00')), '-', models.F('team_bonus_weight')), '-', models.F('company_bonus_weight')))), name='kpi_settings_bonus_total'),
                ],
            },
        ),
        migrations.CreateModel(
            name='KPITemplateVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('retired', 'Retired')], db_index=True, default='draft', max_length=20)),
                ('effective_start', models.DateField(blank=True, null=True)),
                ('effective_end', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_kpi_template_versions', to=settings.AUTH_USER_MODEL)),
                ('published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_kpi_template_versions', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='crm.kpiroletemplate')),
            ],
            options={
                'ordering': ('template__name', '-version'),
                'indexes': [models.Index(fields=['template', 'status', 'effective_start'], name='kpi_version_lookup_idx')],
                'constraints': [
                    models.UniqueConstraint(fields=('template', 'version'), name='kpi_template_version_uniq'),
                    models.CheckConstraint(condition=models.Q(('version__gte', 1)), name='kpi_template_version_pos'),
                ],
            },
        ),
        migrations.CreateModel(
            name='KPIItemDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180)),
                ('description', models.TextField(blank=True, default='')),
                ('purpose', models.TextField(blank=True, default='')),
                ('measurement_method', models.TextField(blank=True, default='')),
                ('target', models.TextField(blank=True, default='')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))])),
                ('review_frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('annual', 'Annual')], default='monthly', max_length=20)),
                ('data_source', models.CharField(blank=True, default='', max_length=240)),
                ('green_min', models.DecimalField(decimal_places=2, default=Decimal('85.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))])),
                ('green_max', models.DecimalField(decimal_places=2, default=Decimal('100.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))])),
                ('yellow_min', models.DecimalField(decimal_places=2, default=Decimal('70.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))])),
                ('yellow_max', models.DecimalField(decimal_places=2, default=Decimal('84.99'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))])),
                ('red_min', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))])),
                ('red_max', models.DecimalField(decimal_places=2, default=Decimal('69.99'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))])),
                ('manager_approval_required', models.BooleanField(default=True)),
                ('evidence_required', models.BooleanField(default=False)),
                ('bonus_eligible', models.BooleanField(default=True)),
                ('critical_failure_rule', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('template_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='crm.kpitemplateversion')),
            ],
            options={
                'ordering': ('sort_order', 'id'),
                'indexes': [models.Index(fields=['template_version', 'is_active', 'sort_order'], name='kpi_item_lookup_idx')],
                'constraints': [
                    models.UniqueConstraint(fields=('template_version', 'name'), name='kpi_item_version_name_uniq'),
                    models.CheckConstraint(condition=models.Q(('weight__gte', 0), ('weight__lte', 100)), name='kpi_item_weight_range'),
                    models.CheckConstraint(condition=models.Q(('red_min', Decimal('0.00')), ('red_min__lte', models.F('red_max')), ('yellow_min', django.db.models.expressions.CombinedExpression(models.F('red_max'), '+', models.Value(Decimal('0.01')))), ('yellow_min__lte', models.F('yellow_max')), ('green_min', django.db.models.expressions.CombinedExpression(models.F('yellow_max'), '+', models.Value(Decimal('0.01')))), ('green_min__lte', models.F('green_max')), ('green_max', Decimal('100.00'))), name='kpi_item_ranges_ordered'),
                ],
            },
        ),
    ]
