# Generated by Django 5.2.8 on 2026-07-31 22:58

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0191_library_permission_controls'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceivableEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('CASH_RECEIPT', 'Cash receipt'), ('CREDIT_NOTE', 'Credit note'), ('REFUND', 'Refund'), ('OPENING_RECEIPT', 'Opening receipt'), ('ADJUSTMENT', 'Adjustment'), ('REVERSAL', 'Reversal')], db_index=True, max_length=24)),
                ('state', models.CharField(choices=[('DRAFT', 'Draft'), ('POSTED', 'Posted'), ('REVERSED', 'Reversed')], db_index=True, default='DRAFT', max_length=12)),
                ('event_date', models.DateField(db_index=True)),
                ('effective_date', models.DateField(db_index=True)),
                ('posted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('native_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(choices=[('CAD', 'CAD'), ('USD', 'USD'), ('BDT', 'BDT')], max_length=3)),
                ('rate_to_cad', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=14)),
                ('rate_to_bdt', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=14)),
                ('amount_cad', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('amount_bdt', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('external_reference', models.CharField(blank=True, db_index=True, default='', max_length=120)),
                ('idempotency_key', models.CharField(max_length=120, unique=True)),
                ('reason', models.TextField(blank=True, default='')),
                ('evidence_reference', models.CharField(blank=True, default='', max_length=255)),
                ('migration_batch', models.CharField(blank=True, db_index=True, default='', max_length=120)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('accounting_entry', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='receivable_event', to='crm.accountingentry')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_receivable_events', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_receivable_events', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receivable_events', to='crm.customer')),
                ('legacy_invoice_payment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='receivable_event', to='crm.invoicepayment')),
                ('reverses_event', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversed_by_event', to='crm.receivableevent')),
            ],
            options={
                'ordering': ['-effective_date', '-id'],
                'indexes': [models.Index(fields=['state', 'kind', 'effective_date'], name='crm_recev_state_kind_idx'), models.Index(fields=['customer', 'currency', 'state'], name='crm_recev_customer_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('native_amount', Decimal('0')), _negated=True), name='crm_recev_native_nonzero'), models.CheckConstraint(condition=models.Q(('rate_to_bdt__gte', 0), ('rate_to_cad__gte', 0)), name='crm_recev_rates_nonnegative')],
            },
        ),
        migrations.CreateModel(
            name='ReceivableAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('DRAFT', 'Draft'), ('POSTED', 'Posted'), ('REVERSED', 'Reversed')], db_index=True, default='DRAFT', max_length=12)),
                ('signed_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(choices=[('CAD', 'CAD'), ('USD', 'USD'), ('BDT', 'BDT')], max_length=3)),
                ('allocation_date', models.DateField(db_index=True)),
                ('posted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('idempotency_key', models.CharField(max_length=120, unique=True)),
                ('reason', models.TextField(blank=True, default='')),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_receivable_allocations', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_receivable_allocations', to=settings.AUTH_USER_MODEL)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receivable_allocations', to='crm.invoice')),
                ('reverses_allocation', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversed_by_allocation', to='crm.receivableallocation')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='crm.receivableevent')),
            ],
            options={
                'ordering': ['-allocation_date', '-id'],
                'indexes': [models.Index(fields=['invoice', 'state', 'allocation_date'], name='crm_reca_invoice_idx'), models.Index(fields=['event', 'state'], name='crm_reca_event_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('signed_amount', Decimal('0')), _negated=True), name='crm_reca_amount_nonzero')],
            },
        ),
    ]
