# Generated by Django 5.2.8 on 2026-07-31 23:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0192_receivables_ledger_phase3b'),
    ]

    operations = [
        migrations.AddField(
            model_name='receivableevent',
            name='source_invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='receivable_events', to='crm.invoice'),
        ),
        migrations.AlterField(
            model_name='receivableevent',
            name='kind',
            field=models.CharField(choices=[('INVOICE_ISSUED', 'Invoice issued'), ('CASH_RECEIPT', 'Cash receipt'), ('CREDIT_NOTE', 'Credit note'), ('REFUND', 'Refund'), ('OPENING_RECEIPT', 'Opening receipt'), ('ADJUSTMENT', 'Adjustment'), ('REVERSAL', 'Reversal')], db_index=True, max_length=24),
        ),
    ]
