# Generated by Django 5.2.8 on 2026-07-28 23:05

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0192_kpi_template_foundation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeKPIRoleAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_weight', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.01')), django.core.validators.MaxValueValidator(Decimal('100.00'))])),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('bonus_eligible', models.BooleanField(db_index=True, default=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignment_version', models.PositiveIntegerField(default=1)),
                ('is_archived', models.BooleanField(db_index=True, default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_kpi_role_assignments', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='kpi_role_assignments', to='crm.employeeprofile')),
                ('kpi_template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employee_assignments', to='crm.kpiroletemplate')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_kpi_role_assignments', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_kpi_role_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('employee_id', 'start_date', 'kpi_template__name', 'id'),
                'default_permissions': (),
                'indexes': [
                    models.Index(fields=['employee', 'is_active', 'is_archived', 'start_date'], name='kpi_asn_employee_current_idx'),
                    models.Index(fields=['employee', 'start_date', 'end_date'], name='kpi_asn_employee_dates_idx'),
                    models.Index(fields=['manager', 'is_active', 'is_archived'], name='kpi_asn_manager_current_idx'),
                    models.Index(fields=['kpi_template', 'start_date'], name='kpi_asn_template_date_idx'),
                ],
                'constraints': [
                    models.CheckConstraint(condition=models.Q(('role_weight__gt', 0), ('role_weight__lte', 100)), name='kpi_asn_weight_range'),
                    models.CheckConstraint(condition=models.Q(('end_date__isnull', True), ('end_date__gte', models.F('start_date')), _connector='OR'), name='kpi_asn_dates_ordered'),
                    models.CheckConstraint(condition=models.Q(('is_archived', False), ('is_active', False), _connector='OR'), name='kpi_asn_archived_inactive'),
                    models.CheckConstraint(condition=models.Q(('assignment_version__gte', 1)), name='kpi_asn_version_positive'),
                ],
            },
        ),
        migrations.CreateModel(
            name='EmployeeKPIRoleAssignmentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_version', models.PositiveIntegerField()),
                ('change_type', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('deactivated', 'Deactivated'), ('archived', 'Archived')], max_length=20)),
                ('old_values', models.JSONField(blank=True, default=dict)),
                ('new_values', models.JSONField(default=dict)),
                ('reason', models.TextField(blank=True, default='')),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='history_entries', to='crm.employeekpiroleassignment')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kpi_assignment_history_changes', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='kpi_assignment_history', to='crm.employeeprofile')),
                ('kpi_template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employee_assignment_history', to='crm.kpiroletemplate')),
            ],
            options={
                'ordering': ('assignment_id', 'assignment_version'),
                'default_permissions': (),
                'indexes': [
                    models.Index(fields=['employee', 'changed_at'], name='kpi_asn_hist_employee_idx'),
                    models.Index(fields=['change_type', 'changed_at'], name='kpi_asn_hist_change_idx'),
                ],
                'constraints': [
                    models.UniqueConstraint(fields=('assignment', 'assignment_version'), name='kpi_asn_history_version_uniq'),
                    models.CheckConstraint(condition=models.Q(('assignment_version__gte', 1)), name='kpi_asn_hist_version_positive'),
                ],
            },
        ),
    ]
