# Generated by Django 5.2.8 on 2026-07-29 01:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0193_kpi_employee_role_assignments'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KPIReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_type', models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('annual', 'Annual')], max_length=20)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('review_date', models.DateField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('locked', 'Locked')], db_index=True, default='draft', max_length=20)),
                ('manager_comment', models.TextField(blank=True, default='')),
                ('approval_comment', models.TextField(blank=True, default='')),
                ('rejection_comment', models.TextField(blank=True, default='')),
                ('definition_snapshot', models.JSONField(default=dict)),
                ('calculation_snapshot', models.JSONField(blank=True, default=dict)),
                ('approved_snapshot', models.JSONField(blank=True, default=dict)),
                ('snapshot_digest', models.CharField(blank=True, default='', max_length=64)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('review_started_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_kpi_reviews', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_kpi_reviews', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='kpi_reviews', to='crm.employeeprofile')),
                ('locked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locked_kpi_reviews', to=settings.AUTH_USER_MODEL)),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_kpi_reviews', to=settings.AUTH_USER_MODEL)),
                ('rejected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_kpi_reviews', to=settings.AUTH_USER_MODEL)),
                ('review_started_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='started_kpi_reviews', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_kpi_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-period_end', '-review_date', '-id'),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='KPIReviewItemEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actual_value', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('critical_red', models.BooleanField(default=False)),
                ('critical_reason', models.TextField(blank=True, default='')),
                ('critical_trigger', models.CharField(blank=True, default='', max_length=160)),
                ('item_comment', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='kpi_review_entries', to='crm.employeekpiroleassignment')),
                ('kpi_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='review_entries', to='crm.kpiitemdefinition')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='item_entries', to='crm.kpireview')),
            ],
            options={
                'ordering': ('assignment_id', 'kpi_item__sort_order', 'kpi_item_id'),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='KPIReviewTransition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Created'), ('saved', 'Draft Saved'), ('submitted', 'Submitted'), ('review_started', 'Review Started'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('returned_to_draft', 'Returned to Draft'), ('locked', 'Locked')], max_length=30)),
                ('from_status', models.CharField(blank=True, choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('locked', 'Locked')], default='', max_length=20)),
                ('to_status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('locked', 'Locked')], max_length=20)),
                ('comment', models.TextField(blank=True, default='')),
                ('snapshot_digest', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kpi_review_transitions', to=settings.AUTH_USER_MODEL)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transitions', to='crm.kpireview')),
            ],
            options={
                'ordering': ('created_at', 'id'),
                'default_permissions': (),
            },
        ),
        migrations.AddIndex(
            model_name='kpireview',
            index=models.Index(fields=['employee', 'status', '-period_end'], name='kpi_review_employee_status_idx'),
        ),
        migrations.AddIndex(
            model_name='kpireview',
            index=models.Index(fields=['manager', 'status', '-period_end'], name='kpi_review_manager_status_idx'),
        ),
        migrations.AddIndex(
            model_name='kpireview',
            index=models.Index(fields=['status', '-submitted_at'], name='kpi_review_queue_idx'),
        ),
        migrations.AddConstraint(
            model_name='kpireview',
            constraint=models.UniqueConstraint(fields=('employee', 'period_type', 'period_start', 'period_end'), name='kpi_review_employee_period_uniq'),
        ),
        migrations.AddConstraint(
            model_name='kpireview',
            constraint=models.CheckConstraint(condition=models.Q(('period_end__gte', models.F('period_start'))), name='kpi_review_period_ordered'),
        ),
        migrations.AddConstraint(
            model_name='kpireview',
            constraint=models.CheckConstraint(condition=models.Q(('review_date__gte', models.F('period_start')), ('review_date__lte', models.F('period_end'))), name='kpi_review_date_in_period'),
        ),
        migrations.AddIndex(
            model_name='kpireviewitementry',
            index=models.Index(fields=['review', 'assignment', 'kpi_item'], name='kpi_review_item_lookup_idx'),
        ),
        migrations.AddConstraint(
            model_name='kpireviewitementry',
            constraint=models.UniqueConstraint(fields=('review', 'assignment', 'kpi_item'), name='kpi_review_item_assignment_uniq'),
        ),
        migrations.AddIndex(
            model_name='kpireviewtransition',
            index=models.Index(fields=['review', 'created_at'], name='kpi_review_transition_idx'),
        ),
        migrations.AddIndex(
            model_name='kpireviewtransition',
            index=models.Index(fields=['action', 'created_at'], name='kpi_review_action_idx'),
        ),
    ]
