# Generated by Django 5.2.8 on 2026-07-29 03:13

import django.core.validators
import django.db.models.deletion
import django.db.models.expressions
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0194_kpi_performance_reviews'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KPIBonusWeightProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=80)),
                ('name', models.CharField(max_length=140)),
                ('version', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('retired', 'Retired')], db_index=True, default='draft', max_length=20)),
                ('team_scope_code', models.SlugField(max_length=80)),
                ('team_scope_name', models.CharField(max_length=140)),
                ('individual_weight', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('team_weight', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('company_weight', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('effective_start', models.DateField()),
                ('effective_end', models.DateField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_kpi_bonus_weight_profiles', to=settings.AUTH_USER_MODEL)),
                ('published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_kpi_bonus_weight_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('code', '-version'),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='KPIBonusRuleSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=80)),
                ('name', models.CharField(max_length=140)),
                ('version', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('retired', 'Retired')], db_index=True, default='draft', max_length=20)),
                ('bonus_enabled', models.BooleanField(default=True)),
                ('minimum_score', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('attendance_multiplier_default', models.DecimalField(decimal_places=4, default=Decimal('1.0000'), max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('0.0000'))])),
                ('attendance_multiplier_min', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('0.0000'))])),
                ('attendance_multiplier_max', models.DecimalField(decimal_places=4, default=Decimal('1.0000'), max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('0.0000'))])),
                ('critical_red_behavior', models.CharField(choices=[('block', 'Block'), ('not_eligible', 'Not Eligible'), ('allow', 'Allow')], default='block', max_length=20)),
                ('bonus_floor', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('bonus_cap', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('currency', models.CharField(max_length=3)),
                ('eligible_employee_statuses', models.JSONField(default=list)),
                ('approval_required', models.BooleanField(default=True)),
                ('effective_start', models.DateField()),
                ('effective_end', models.DateField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_kpi_bonus_rule_sets', to=settings.AUTH_USER_MODEL)),
                ('published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_kpi_bonus_rule_sets', to=settings.AUTH_USER_MODEL)),
                ('weight_profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rule_sets', to='crm.kpibonusweightprofile')),
            ],
            options={
                'ordering': ('code', '-version'),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='KPIBonusCalculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_code', models.CharField(blank=True, default='', max_length=80)),
                ('department_name', models.CharField(blank=True, default='', max_length=140)),
                ('team_scope_code', models.CharField(max_length=80)),
                ('team_scope_name', models.CharField(max_length=140)),
                ('review_date', models.DateField()),
                ('eligibility_status', models.CharField(choices=[('eligible', 'Eligible'), ('not_eligible', 'Not Eligible'), ('blocked', 'Blocked')], db_index=True, max_length=20)),
                ('reason_codes', models.JSONField(blank=True, default=list)),
                ('formula_version', models.CharField(max_length=80)),
                ('bonus_rule_version', models.PositiveIntegerField()),
                ('calculation_version', models.CharField(max_length=80)),
                ('review_snapshot_digest', models.CharField(max_length=64)),
                ('result_snapshot', models.JSONField()),
                ('result_digest', models.CharField(max_length=64)),
                ('calculated_at', models.DateTimeField()),
                ('calculated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_kpi_bonus_calculations', to=settings.AUTH_USER_MODEL)),
                ('company_review', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='company_bonus_source_calculations', to='crm.kpireview')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='kpi_bonus_calculations', to='crm.employeeprofile')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_kpi_bonus_calculations', to=settings.AUTH_USER_MODEL)),
                ('review', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='bonus_calculation', to='crm.kpireview')),
                ('team_review', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='team_bonus_source_calculations', to='crm.kpireview')),
                ('rule_set', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='calculations', to='crm.kpibonusruleset')),
                ('weight_profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='calculations', to='crm.kpibonusweightprofile')),
            ],
            options={
                'ordering': ('-review_date', '-id'),
                'default_permissions': (),
            },
        ),
        migrations.AddIndex(
            model_name='kpibonusweightprofile',
            index=models.Index(fields=['code', 'status', 'effective_start'], name='kpi_bonus_weight_lookup_idx'),
        ),
        migrations.AddConstraint(
            model_name='kpibonusweightprofile',
            constraint=models.UniqueConstraint(fields=('code', 'version'), name='kpi_bonus_weight_version_uniq'),
        ),
        migrations.AddConstraint(
            model_name='kpibonusweightprofile',
            constraint=models.CheckConstraint(condition=models.Q(('version__gte', 1)), name='kpi_bonus_weight_version_pos'),
        ),
        migrations.AddConstraint(
            model_name='kpibonusweightprofile',
            constraint=models.CheckConstraint(condition=models.Q(('individual_weight__gte', 0), ('individual_weight__lte', 100), ('team_weight__gte', 0), ('team_weight__lte', 100), ('company_weight__gte', 0), ('company_weight__lte', 100)), name='kpi_bonus_weight_ranges'),
        ),
        migrations.AddConstraint(
            model_name='kpibonusweightprofile',
            constraint=models.CheckConstraint(condition=models.Q(('individual_weight', django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(models.Value(Decimal('100.00')), '-', models.F('team_weight')), '-', models.F('company_weight')))), name='kpi_bonus_weight_total'),
        ),
        migrations.AddConstraint(
            model_name='kpibonusweightprofile',
            constraint=models.CheckConstraint(condition=models.Q(('effective_end__isnull', True), ('effective_end__gte', models.F('effective_start')), _connector='OR'), name='kpi_bonus_weight_dates'),
        ),
        migrations.AddIndex(
            model_name='kpibonusruleset',
            index=models.Index(fields=['code', 'status', 'effective_start'], name='kpi_bonus_rule_lookup_idx'),
        ),
        migrations.AddConstraint(
            model_name='kpibonusruleset',
            constraint=models.UniqueConstraint(fields=('code', 'version'), name='kpi_bonus_rule_version_uniq'),
        ),
        migrations.AddConstraint(
            model_name='kpibonusruleset',
            constraint=models.CheckConstraint(condition=models.Q(('version__gte', 1)), name='kpi_bonus_rule_version_pos'),
        ),
        migrations.AddConstraint(
            model_name='kpibonusruleset',
            constraint=models.CheckConstraint(condition=models.Q(('minimum_score__gte', 0), ('minimum_score__lte', 100)), name='kpi_bonus_rule_min_score'),
        ),
        migrations.AddConstraint(
            model_name='kpibonusruleset',
            constraint=models.CheckConstraint(condition=models.Q(('attendance_multiplier_min__gte', 0), ('attendance_multiplier_default__gte', models.F('attendance_multiplier_min')), ('attendance_multiplier_default__lte', models.F('attendance_multiplier_max'))), name='kpi_bonus_rule_attendance'),
        ),
        migrations.AddConstraint(
            model_name='kpibonusruleset',
            constraint=models.CheckConstraint(condition=models.Q(('bonus_cap__isnull', True), ('bonus_cap__gte', models.F('bonus_floor')), _connector='OR'), name='kpi_bonus_rule_payout_range'),
        ),
        migrations.AddConstraint(
            model_name='kpibonusruleset',
            constraint=models.CheckConstraint(condition=models.Q(('effective_end__isnull', True), ('effective_end__gte', models.F('effective_start')), _connector='OR'), name='kpi_bonus_rule_dates'),
        ),
        migrations.AddIndex(
            model_name='kpibonuscalculation',
            index=models.Index(fields=['employee', 'eligibility_status', '-review_date'], name='kpi_bonus_calc_employee_idx'),
        ),
        migrations.AddIndex(
            model_name='kpibonuscalculation',
            index=models.Index(fields=['rule_set', '-review_date'], name='kpi_bonus_calc_rule_idx'),
        ),
        migrations.AddConstraint(
            model_name='kpibonuscalculation',
            constraint=models.CheckConstraint(condition=models.Q(('bonus_rule_version__gte', 1)), name='kpi_bonus_calc_rule_version_pos'),
        ),
    ]
