# Generated by Django 6.0 on 2026-08-01 22:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0194_financial_core'),
    ]

    operations = [
        migrations.AddField(
            model_name='receivableevent',
            name='financial_journal',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='receivable_event', to='crm.journalentry'),
        ),
    ]
