# Generated by Django 5.2.8 on 2026-07-29 16:49

import django.core.validators
import django.db.models.deletion
import django.db.models.expressions
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0195_kpi_bonus_engine'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KPIIntelligenceRuleSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=80)),
                ('name', models.CharField(max_length=140)),
                ('version', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('retired', 'Retired')], db_index=True, default='draft', max_length=20)),
                ('effective_start', models.DateField()),
                ('effective_end', models.DateField(blank=True, null=True)),
                ('minimum_score', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))])),
                ('health_green_threshold', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))])),
                ('critical_red_count', models.PositiveSmallIntegerField(default=1)),
                ('decline_percentage', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))])),
                ('trend_periods', models.PositiveSmallIntegerField()),
                ('overdue_days', models.PositiveSmallIntegerField()),
                ('review_completion_target', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))])),
                ('improvement_threshold', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))])),
                ('department_risk_threshold', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))])),
                ('manager_workload_threshold', models.PositiveSmallIntegerField()),
                ('overall_kpi_weight', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))])),
                ('review_completion_weight', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))])),
                ('bonus_readiness_weight', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))])),
                ('improvement_weight', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))])),
                ('risk_control_weight', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))])),
                ('critical_alert_severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='critical', max_length=20)),
                ('red_alert_severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='high', max_length=20)),
                ('yellow_alert_severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_kpi_intelligence_rule_sets', to=settings.AUTH_USER_MODEL)),
                ('published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_kpi_intelligence_rule_sets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('code', '-version'),
                'default_permissions': (),
                'indexes': [models.Index(fields=['code', 'status', 'effective_start'], name='kpi_intel_rule_lookup_idx')],
                'constraints': [models.UniqueConstraint(fields=('code', 'version'), name='kpi_intel_rule_version_uniq'), models.CheckConstraint(condition=models.Q(('version__gte', 1)), name='kpi_intel_rule_version_pos'), models.CheckConstraint(condition=models.Q(('effective_end__isnull', True), ('effective_end__gte', models.F('effective_start')), _connector='OR'), name='kpi_intel_rule_dates'), models.CheckConstraint(condition=models.Q(('minimum_score__lte', models.F('health_green_threshold'))), name='kpi_intel_health_thresholds'), models.CheckConstraint(condition=models.Q(('trend_periods__gte', 2), ('trend_periods__lte', 24)), name='kpi_intel_trend_periods'), models.CheckConstraint(condition=models.Q(('manager_workload_threshold__gte', 1)), name='kpi_intel_manager_workload'), models.CheckConstraint(condition=models.Q(('critical_red_count__gte', 1)), name='kpi_intel_critical_count'), models.CheckConstraint(condition=models.Q(('overall_kpi_weight', django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(models.Value(Decimal('100.00')), '-', models.F('review_completion_weight')), '-', models.F('bonus_readiness_weight')), '-', models.F('improvement_weight')), '-', models.F('risk_control_weight')))), name='kpi_intel_health_weight_total')],
            },
        ),
    ]
