# Generated by Django 5.2.8 on 2026-08-02 19:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0195_receivable_financial_journal'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialExceptionReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('change_reason', models.TextField(blank=True, default='')),
                ('exception_id', models.CharField(max_length=32, unique=True)),
                ('source_key', models.CharField(max_length=64, unique=True)),
                ('severity', models.CharField(choices=[('CRITICAL', 'Critical'), ('HIGH', 'High')], db_index=True, max_length=10)),
                ('area', models.CharField(db_index=True, max_length=80)),
                ('exception_type', models.CharField(db_index=True, max_length=100)),
                ('record_type', models.CharField(db_index=True, max_length=80)),
                ('record_number', models.CharField(db_index=True, max_length=120)),
                ('counterparty_name', models.CharField(blank=True, db_index=True, default='', max_length=200)),
                ('transaction_date', models.DateField(blank=True, db_index=True, null=True)),
                ('side', models.CharField(blank=True, choices=[('CA', 'Canada'), ('BD', 'Bangladesh')], db_index=True, default='', max_length=2)),
                ('currency', models.CharField(blank=True, db_index=True, default='', max_length=3)),
                ('current_value', models.TextField()),
                ('expected_value', models.TextField()),
                ('difference', models.TextField()),
                ('reason', models.TextField()),
                ('evidence_available', models.TextField(blank=True, default='')),
                ('evidence_needed', models.TextField()),
                ('recommended_action', models.TextField()),
                ('review_status', models.CharField(choices=[('OPEN', 'Open'), ('EVIDENCE_REQUIRED', 'Evidence required'), ('APPROVED', 'Correction approved'), ('REJECTED', 'Proposed correction rejected'), ('INCOMPLETE', 'Historical data incomplete'), ('DEFERRED', 'Deferred'), ('RESOLVED', 'Resolved')], db_index=True, default='OPEN', max_length=24)),
                ('review_notes', models.TextField(blank=True, default='')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('source_snapshot', models.JSONField(blank=True, default=dict)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='financial_exception_reviews', to='crm.customer')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_financial_exceptions', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='financial_exception_reviews', to='crm.supplier')),
            ],
            options={
                'ordering': ('severity', 'area', 'exception_id'),
            },
        ),
        migrations.CreateModel(
            name='FinancialAdjustmentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('change_reason', models.TextField(blank=True, default='')),
                ('request_id', models.CharField(max_length=40, unique=True)),
                ('adjustment_type', models.CharField(choices=[('MANUAL', 'Manual journal'), ('OPENING', 'Opening balance'), ('HISTORICAL', 'Historical adjustment'), ('REVERSAL', 'Journal reversal'), ('RECEIVABLE', 'Receivable correction'), ('PAYABLE', 'Payable correction'), ('CURRENCY', 'Currency snapshot correction')], db_index=True, max_length=16)),
                ('state', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('POSTED', 'Posted'), ('REVERSED', 'Reversed')], db_index=True, default='DRAFT', max_length=12)),
                ('journal_date', models.DateField(db_index=True)),
                ('side', models.CharField(choices=[('CA', 'Canada'), ('BD', 'Bangladesh')], db_index=True, max_length=2)),
                ('currency', models.CharField(choices=[('CAD', 'CAD'), ('USD', 'USD'), ('BDT', 'BDT')], db_index=True, max_length=3)),
                ('native_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('rate_to_cad', models.DecimalField(decimal_places=10, max_digits=20)),
                ('rate_to_bdt', models.DecimalField(decimal_places=10, max_digits=20)),
                ('reason', models.TextField()),
                ('before_values', models.JSONField(default=dict)),
                ('after_values', models.JSONField(default=dict)),
                ('approval_notes', models.TextField(blank=True, default='')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('credit_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credit_adjustment_requests', to='crm.financialaccount')),
                ('debit_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='debit_adjustment_requests', to='crm.financialaccount')),
                ('evidence_documents', models.ManyToManyField(blank=True, related_name='adjustment_requests', to='crm.financialdocument')),
                ('journal', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='adjustment_request', to='crm.journalentry')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('source_journal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='adjustment_requests_to_reverse', to='crm.journalentry')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('exception', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='adjustment_requests', to='crm.financialexceptionreview')),
            ],
            options={
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.AddIndex(
            model_name='financialexceptionreview',
            index=models.Index(fields=['severity', 'review_status'], name='fin_exc_severity_status_idx'),
        ),
        migrations.AddIndex(
            model_name='financialexceptionreview',
            index=models.Index(fields=['area', 'review_status'], name='fin_exc_area_status_idx'),
        ),
        migrations.AddIndex(
            model_name='financialexceptionreview',
            index=models.Index(fields=['side', 'currency'], name='fin_exc_side_currency_idx'),
        ),
        migrations.AddIndex(
            model_name='financialadjustmentrequest',
            index=models.Index(fields=['state', 'adjustment_type'], name='fin_adjust_state_type_idx'),
        ),
        migrations.AddIndex(
            model_name='financialadjustmentrequest',
            index=models.Index(fields=['side', 'journal_date'], name='fin_adjust_side_date_idx'),
        ),
        migrations.AddConstraint(
            model_name='financialadjustmentrequest',
            constraint=models.CheckConstraint(condition=models.Q(('native_amount__gt', 0)), name='financial_adjustment_positive'),
        ),
        migrations.AddConstraint(
            model_name='financialadjustmentrequest',
            constraint=models.CheckConstraint(condition=models.Q(('debit_account', models.F('credit_account')), _negated=True), name='financial_adjustment_distinct_accounts'),
        ),
    ]
