# Generated by Django 5.2.8 on 2026-07-29 17:57

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0196_kpi_intelligence_rules'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KPIEscalationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('review_open', 'Review Open'), ('review_due_soon', 'Review Due Soon'), ('review_due_today', 'Review Due Today'), ('review_overdue', 'Review Overdue'), ('approval_pending', 'Approval Pending'), ('rejected_correction', 'Rejected Review Correction'), ('locked_confirmation', 'Locked Review Confirmation'), ('improvement_action', 'Improvement Action'), ('critical_red', 'Critical Red'), ('yellow_attention', 'Yellow Attention'), ('green_recognition', 'Green Recognition'), ('bonus_ready', 'Bonus Ready'), ('bonus_pending', 'Bonus Pending Approval'), ('bonus_blocked', 'Bonus Blocked'), ('manager_queue', 'Manager Queue'), ('executive_intelligence', 'Executive Intelligence'), ('data_quality', 'Data Quality')], max_length=40)),
                ('stage', models.PositiveSmallIntegerField()),
                ('trigger_offset_days', models.IntegerField(default=0)),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('normal', 'Normal'), ('information', 'Information')], max_length=20)),
                ('recipient_scopes', models.JSONField(default=list)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('event_type', 'stage'),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='KPIAutomationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=120)),
                ('schedule', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('annual', 'Annual')], db_index=True, max_length=20)),
                ('source_date', models.DateField()),
                ('status', models.CharField(choices=[('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='running', max_length=20)),
                ('retry_count', models.PositiveSmallIntegerField(default=0)),
                ('retry_limit', models.PositiveSmallIntegerField(default=0)),
                ('batch_size', models.PositiveSmallIntegerField(default=100)),
                ('candidates_count', models.PositiveIntegerField(default=0)),
                ('created_count', models.PositiveIntegerField(default=0)),
                ('duplicate_count', models.PositiveIntegerField(default=0)),
                ('failure_type', models.CharField(blank=True, default='', max_length=120)),
                ('failure_message', models.CharField(blank=True, default='', max_length=300)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('initiated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initiated_kpi_automation_runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-started_at', '-id'),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='KPINotificationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=80)),
                ('name', models.CharField(max_length=140)),
                ('version', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('retired', 'Retired')], db_index=True, default='draft', max_length=20)),
                ('effective_start', models.DateField()),
                ('effective_end', models.DateField(blank=True, null=True)),
                ('enabled_event_types', models.JSONField(default=list)),
                ('reminder_offsets', models.JSONField(default=list)),
                ('improvement_reminder_days', models.JSONField(default=list)),
                ('enabled_schedules', models.JSONField(default=list)),
                ('positive_recognition_enabled', models.BooleanField(default=False)),
                ('retry_limit', models.PositiveSmallIntegerField(default=0)),
                ('batch_size', models.PositiveSmallIntegerField(default=100)),
                ('source_lookback_days', models.PositiveSmallIntegerField(default=90)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_kpi_notification_rules', to=settings.AUTH_USER_MODEL)),
                ('published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_kpi_notification_rules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('code', '-version'),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='KPINotificationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('review_open', 'Review Open'), ('review_due_soon', 'Review Due Soon'), ('review_due_today', 'Review Due Today'), ('review_overdue', 'Review Overdue'), ('approval_pending', 'Approval Pending'), ('rejected_correction', 'Rejected Review Correction'), ('locked_confirmation', 'Locked Review Confirmation'), ('improvement_action', 'Improvement Action'), ('critical_red', 'Critical Red'), ('yellow_attention', 'Yellow Attention'), ('green_recognition', 'Green Recognition'), ('bonus_ready', 'Bonus Ready'), ('bonus_pending', 'Bonus Pending Approval'), ('bonus_blocked', 'Bonus Blocked'), ('manager_queue', 'Manager Queue'), ('executive_intelligence', 'Executive Intelligence'), ('data_quality', 'Data Quality')], db_index=True, max_length=40)),
                ('related_department_code', models.CharField(blank=True, default='', max_length=80)),
                ('related_department_name', models.CharField(blank=True, default='', max_length=140)),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('normal', 'Normal'), ('information', 'Information')], db_index=True, max_length=20)),
                ('title', models.CharField(max_length=220)),
                ('message', models.TextField(blank=True, default='')),
                ('action_link', models.CharField(blank=True, default='', max_length=300)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('notification_version', models.CharField(max_length=80)),
                ('deduplication_key', models.CharField(max_length=64, unique=True)),
                ('source_event', models.CharField(max_length=120)),
                ('source_record_type', models.CharField(max_length=80)),
                ('source_record_id', models.CharField(max_length=80)),
                ('source_period', models.CharField(blank=True, default='', max_length=80)),
                ('source_state', models.CharField(max_length=64)),
                ('dismissed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('automation_notification', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='kpi_event', to='crm.automationnotification')),
                ('automation_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_events', to='crm.kpiautomationrun')),
                ('dismissed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dismissed_kpi_notification_events', to=settings.AUTH_USER_MODEL)),
                ('escalation_rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='notification_events', to='crm.kpiescalationrule')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='kpi_notification_events', to=settings.AUTH_USER_MODEL)),
                ('related_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='kpi_notification_events', to='crm.employeeprofile')),
                ('related_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_kpi_notification_events', to=settings.AUTH_USER_MODEL)),
                ('related_review', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='notification_events', to='crm.kpireview')),
                ('notification_rule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notification_events', to='crm.kpinotificationrule')),
            ],
            options={
                'ordering': ('-created_at', '-id'),
                'default_permissions': (),
            },
        ),
        migrations.AddField(
            model_name='kpiescalationrule',
            name='notification_rule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='escalation_rules', to='crm.kpinotificationrule'),
        ),
        migrations.AddIndex(
            model_name='kpiautomationrun',
            index=models.Index(fields=['task_name', 'status', '-started_at'], name='kpi_automation_task_status_idx'),
        ),
        migrations.AddIndex(
            model_name='kpiautomationrun',
            index=models.Index(fields=['schedule', 'source_date', '-started_at'], name='kpi_automation_schedule_idx'),
        ),
        migrations.AddConstraint(
            model_name='kpiautomationrun',
            constraint=models.CheckConstraint(condition=models.Q(('retry_count__lte', models.F('retry_limit'))), name='kpi_automation_retry_order'),
        ),
        migrations.AddConstraint(
            model_name='kpiautomationrun',
            constraint=models.CheckConstraint(condition=models.Q(('retry_limit__lte', 5)), name='kpi_automation_retry_limit'),
        ),
        migrations.AddConstraint(
            model_name='kpiautomationrun',
            constraint=models.CheckConstraint(condition=models.Q(('batch_size__gte', 1), ('batch_size__lte', 1000)), name='kpi_automation_batch_size'),
        ),
        migrations.AddIndex(
            model_name='kpinotificationrule',
            index=models.Index(fields=['code', 'status', 'effective_start'], name='kpi_notify_rule_lookup_idx'),
        ),
        migrations.AddConstraint(
            model_name='kpinotificationrule',
            constraint=models.UniqueConstraint(fields=('code', 'version'), name='kpi_notify_rule_version_uniq'),
        ),
        migrations.AddConstraint(
            model_name='kpinotificationrule',
            constraint=models.CheckConstraint(condition=models.Q(('version__gte', 1)), name='kpi_notify_rule_version_pos'),
        ),
        migrations.AddConstraint(
            model_name='kpinotificationrule',
            constraint=models.CheckConstraint(condition=models.Q(('effective_end__isnull', True), ('effective_end__gte', models.F('effective_start')), _connector='OR'), name='kpi_notify_rule_dates'),
        ),
        migrations.AddConstraint(
            model_name='kpinotificationrule',
            constraint=models.CheckConstraint(condition=models.Q(('retry_limit__lte', 5)), name='kpi_notify_rule_retry_limit'),
        ),
        migrations.AddConstraint(
            model_name='kpinotificationrule',
            constraint=models.CheckConstraint(condition=models.Q(('batch_size__gte', 1), ('batch_size__lte', 1000)), name='kpi_notify_rule_batch_size'),
        ),
        migrations.AddConstraint(
            model_name='kpinotificationrule',
            constraint=models.CheckConstraint(condition=models.Q(('source_lookback_days__gte', 1), ('source_lookback_days__lte', 3650)), name='kpi_notify_rule_lookback'),
        ),
        migrations.AddIndex(
            model_name='kpinotificationevent',
            index=models.Index(fields=['recipient', 'dismissed_at', '-created_at'], name='kpi_notify_event_recipient_idx'),
        ),
        migrations.AddIndex(
            model_name='kpinotificationevent',
            index=models.Index(fields=['related_review', 'notification_type', '-created_at'], name='kpi_notify_event_review_idx'),
        ),
        migrations.AddIndex(
            model_name='kpinotificationevent',
            index=models.Index(fields=['source_event', 'source_record_type', 'source_record_id'], name='kpi_notify_event_source_idx'),
        ),
        migrations.AddIndex(
            model_name='kpinotificationevent',
            index=models.Index(fields=['severity', 'dismissed_at', '-created_at'], name='kpi_notify_event_severity_idx'),
        ),
        migrations.AddConstraint(
            model_name='kpinotificationevent',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('dismissed_at__isnull', True), ('dismissed_by__isnull', True)), models.Q(('dismissed_at__isnull', False), ('dismissed_by__isnull', False)), _connector='OR'), name='kpi_notify_event_dismissal'),
        ),
        migrations.AddIndex(
            model_name='kpiescalationrule',
            index=models.Index(fields=['notification_rule', 'event_type', 'is_active'], name='kpi_escalation_lookup_idx'),
        ),
        migrations.AddConstraint(
            model_name='kpiescalationrule',
            constraint=models.UniqueConstraint(fields=('notification_rule', 'event_type', 'stage'), name='kpi_escalation_rule_stage_uniq'),
        ),
        migrations.AddConstraint(
            model_name='kpiescalationrule',
            constraint=models.CheckConstraint(condition=models.Q(('stage__lte', 20)), name='kpi_escalation_stage_limit'),
        ),
        migrations.AddConstraint(
            model_name='kpiescalationrule',
            constraint=models.CheckConstraint(condition=models.Q(('trigger_offset_days__gte', -3650), ('trigger_offset_days__lte', 365)), name='kpi_escalation_offset'),
        ),
    ]
