# Generated by Django 5.2.8 on 2026-07-29 18:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0197_kpi_notifications_automation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KPIPolicyApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_type', models.CharField(choices=[('template', 'KPI Template'), ('settings', 'KPI Status Settings'), ('bonus_weight', 'Bonus Weight Profile'), ('bonus_rule', 'Bonus Rule Set'), ('intelligence', 'Intelligence Rule Set'), ('notification', 'Notification Rule')], max_length=24)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('published', 'Published'), ('retired', 'Retired')], db_index=True, default='draft', max_length=24)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('retired_at', models.DateTimeField(blank=True, null=True)),
                ('review_reason', models.TextField(blank=True, default='')),
                ('approval_reason', models.TextField(blank=True, default='')),
                ('retirement_reason', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_kpi_policy_approvals', to=settings.AUTH_USER_MODEL)),
                ('bonus_rule_set', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='release_approval', to='crm.kpibonusruleset')),
                ('bonus_weight_profile', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='release_approval', to='crm.kpibonusweightprofile')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_kpi_policy_approvals', to=settings.AUTH_USER_MODEL)),
                ('intelligence_rule_set', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='release_approval', to='crm.kpiintelligenceruleset')),
                ('kpi_settings', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='release_approval', to='crm.kpisettings')),
                ('notification_rule', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='release_approval', to='crm.kpinotificationrule')),
                ('published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_kpi_policy_approvals', to=settings.AUTH_USER_MODEL)),
                ('retired_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retired_kpi_policy_approvals', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_kpi_policy_approvals', to=settings.AUTH_USER_MODEL)),
                ('template_version', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='release_approval', to='crm.kpitemplateversion')),
            ],
            options={
                'ordering': ('policy_type', 'id'),
                'default_permissions': (),
                'indexes': [models.Index(fields=['policy_type', 'status', '-updated_at'], name='kpi_policy_status_lookup_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('bonus_rule_set__isnull', True), ('bonus_weight_profile__isnull', True), ('intelligence_rule_set__isnull', True), ('kpi_settings__isnull', True), ('notification_rule__isnull', True), ('policy_type', 'template'), ('template_version__isnull', False)), models.Q(('bonus_rule_set__isnull', True), ('bonus_weight_profile__isnull', True), ('intelligence_rule_set__isnull', True), ('kpi_settings__isnull', False), ('notification_rule__isnull', True), ('policy_type', 'settings'), ('template_version__isnull', True)), models.Q(('bonus_rule_set__isnull', True), ('bonus_weight_profile__isnull', False), ('intelligence_rule_set__isnull', True), ('kpi_settings__isnull', True), ('notification_rule__isnull', True), ('policy_type', 'bonus_weight'), ('template_version__isnull', True)), models.Q(('bonus_rule_set__isnull', False), ('bonus_weight_profile__isnull', True), ('intelligence_rule_set__isnull', True), ('kpi_settings__isnull', True), ('notification_rule__isnull', True), ('policy_type', 'bonus_rule'), ('template_version__isnull', True)), models.Q(('bonus_rule_set__isnull', True), ('bonus_weight_profile__isnull', True), ('intelligence_rule_set__isnull', False), ('kpi_settings__isnull', True), ('notification_rule__isnull', True), ('policy_type', 'intelligence'), ('template_version__isnull', True)), models.Q(('bonus_rule_set__isnull', True), ('bonus_weight_profile__isnull', True), ('intelligence_rule_set__isnull', True), ('kpi_settings__isnull', True), ('notification_rule__isnull', False), ('policy_type', 'notification'), ('template_version__isnull', True)), _connector='OR'), name='kpi_policy_approval_one_target'), models.CheckConstraint(condition=models.Q(models.Q(('submitted_at__isnull', True), ('submitted_by__isnull', True)), models.Q(('submitted_at__isnull', False), ('submitted_by__isnull', False)), _connector='OR'), name='kpi_policy_submission_pair'), models.CheckConstraint(condition=models.Q(models.Q(('approved_at__isnull', True), ('approved_by__isnull', True)), models.Q(('approved_at__isnull', False), ('approved_by__isnull', False)), _connector='OR'), name='kpi_policy_approval_pair'), models.CheckConstraint(condition=models.Q(models.Q(('published_at__isnull', True), ('published_by__isnull', True)), models.Q(('published_at__isnull', False), ('published_by__isnull', False)), _connector='OR'), name='kpi_policy_publication_pair'), models.CheckConstraint(condition=models.Q(models.Q(('retired_at__isnull', True), ('retired_by__isnull', True)), models.Q(('retired_at__isnull', False), ('retired_by__isnull', False)), _connector='OR'), name='kpi_policy_retirement_pair')],
            },
        ),
    ]
