# Generated by Django 5.2.8 on 2026-08-08 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0198_approved_financial_relationship_repairs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenserecord',
            name='business_purpose',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='financeoperation',
            name='business_purpose',
            field=models.TextField(blank=True, default=''),
        ),
    ]
