# Generated by Django 5.2.8 on 2026-08-31 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0199_finance_optional_purpose'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicepayment',
            name='payment_method',
            field=models.CharField(choices=[('e_transfer', 'E Transfer'), ('paypal', 'PayPal'), ('bank_transfer', 'Bank Transfer'), ('cash', 'Cash'), ('bank', 'Bank transfer (historical)'), ('cheque', 'Cheque'), ('card', 'Card'), ('mobile', 'Mobile payment'), ('other', 'Other')], default='bank', max_length=20),
        ),
    ]
