# Generated by Django 5.2.8 on 2026-02-02 06:52

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0098_useraccess_can_whatsapp'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DoNotContactPhone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=30, unique=True)),
                ('reason', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='WhatsAppAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(db_index=True, max_length=30)),
                ('display_name', models.CharField(blank=True, default='', max_length=120)),
                ('status', models.CharField(choices=[('disconnected', 'Disconnected'), ('qr_required', 'QR required'), ('connected', 'Connected'), ('error', 'Error')], default='disconnected', max_length=20)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('phone_number',),
            },
        ),
        migrations.CreateModel(
            name='WhatsAppAutomationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('trigger', models.CharField(choices=[('first_inbound', 'First inbound'), ('after_hours', 'After hours'), ('keyword_match', 'Keyword match'), ('no_reply_followup', 'No reply followup')], max_length=30)),
                ('keyword_list_json', models.JSONField(blank=True, default=list)),
                ('response_template', models.TextField(blank=True, default='')),
                ('send_delay_seconds', models.PositiveIntegerField(default=0)),
                ('max_per_contact_per_day', models.PositiveIntegerField(default=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='WhatsAppThread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wa_chat_id', models.CharField(max_length=120)),
                ('contact_phone', models.CharField(db_index=True, max_length=30)),
                ('contact_name', models.CharField(blank=True, default='', max_length=120)),
                ('last_message_at', models.DateTimeField(blank=True, null=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('automation_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='threads', to='whatsapp.whatsappaccount')),
                ('linked_lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wa_threads_web', to='crm.lead')),
            ],
            options={
                'ordering': ('-last_message_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='WhatsAppSendQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_body', models.TextField()),
                ('scheduled_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('processing', 'Processing'), ('sent', 'Sent'), ('failed', 'Failed'), ('canceled', 'Canceled')], default='queued', max_length=20)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('last_error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queue_items', to='whatsapp.whatsappaccount')),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queue_items', to='whatsapp.whatsappthread')),
            ],
            options={
                'ordering': ('scheduled_at', 'id'),
            },
        ),
        migrations.CreateModel(
            name='WhatsAppMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('inbound', 'Inbound'), ('outbound', 'Outbound')], max_length=20)),
                ('wa_message_id', models.CharField(blank=True, default='', max_length=120)),
                ('body', models.TextField(blank=True, default='')),
                ('media_url', models.TextField(blank=True, default='')),
                ('media_type', models.CharField(blank=True, default='', max_length=50)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('read', 'Read'), ('failed', 'Failed')], default='queued', max_length=20)),
                ('error_text', models.TextField(blank=True, default='')),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wa_web_messages', to=settings.AUTH_USER_MODEL)),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='whatsapp.whatsappthread')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='WhatsAppEventLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(max_length=80)),
                ('level', models.CharField(choices=[('info', 'Info'), ('warn', 'Warn'), ('error', 'Error')], default='info', max_length=10)),
                ('message', models.TextField(blank=True, default='')),
                ('payload_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='whatsapp.whatsappaccount')),
                ('thread', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='whatsapp.whatsappthread')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddIndex(
            model_name='whatsappthread',
            index=models.Index(fields=['contact_phone'], name='whatsapp_wh_contact_57daa4_idx'),
        ),
        migrations.AddIndex(
            model_name='whatsappthread',
            index=models.Index(fields=['last_message_at'], name='whatsapp_wh_last_me_568dee_idx'),
        ),
        migrations.AddConstraint(
            model_name='whatsappthread',
            constraint=models.UniqueConstraint(fields=('account', 'wa_chat_id'), name='uniq_wa_web_thread'),
        ),
        migrations.AddIndex(
            model_name='whatsappsendqueue',
            index=models.Index(fields=['status', 'scheduled_at'], name='whatsapp_wh_status_7bb2c3_idx'),
        ),
        migrations.AddIndex(
            model_name='whatsappmessage',
            index=models.Index(fields=['thread'], name='whatsapp_wh_thread__2e358f_idx'),
        ),
        migrations.AddIndex(
            model_name='whatsappmessage',
            index=models.Index(fields=['sent_at'], name='whatsapp_wh_sent_at_5dc563_idx'),
        ),
        migrations.AddIndex(
            model_name='whatsappmessage',
            index=models.Index(fields=['received_at'], name='whatsapp_wh_receive_2cf4e4_idx'),
        ),
        migrations.AddConstraint(
            model_name='whatsappmessage',
            constraint=models.UniqueConstraint(fields=('thread', 'wa_message_id'), name='uniq_wa_web_msg'),
        ),
        migrations.AddIndex(
            model_name='whatsappeventlog',
            index=models.Index(fields=['event', 'level'], name='whatsapp_wh_event_5ebd25_idx'),
        ),
    ]
