# Generated by Codex on 2026-02-04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("whatsapp", "0002_thread_unread_and_media_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="whatsappmessage",
            name="media_filename",
            field=models.CharField(blank=True, default="", max_length=180),
        ),
    ]
