# Generated by Codex on 2026-02-04

from django.db import migrations


def create_default_auto_reply(apps, schema_editor):
    Rule = apps.get_model("whatsapp", "WhatsAppAutomationRule")
    if Rule.objects.filter(trigger="first_inbound").exists():
        return
    Rule.objects.create(
        name="Auto reply (first inbound)",
        trigger="first_inbound",
        response_template="Thank you for reaching out! We will get back to you shortly.",
        max_per_contact_per_day=1,
    )


def remove_default_auto_reply(apps, schema_editor):
    Rule = apps.get_model("whatsapp", "WhatsAppAutomationRule")
    Rule.objects.filter(name="Auto reply (first inbound)", trigger="first_inbound").delete()


class Migration(migrations.Migration):

    dependencies = [
        ("whatsapp", "0003_whatsappmessage_media_filename"),
    ]

    operations = [
        migrations.RunPython(create_default_auto_reply, remove_default_auto_reply),
    ]
