# Generated by Django 6.0 on 2026-05-25 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0004_default_first_inbound_auto_reply'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='whatsappmessage',
            name='media_filename',
        ),
        migrations.RemoveField(
            model_name='whatsappmessage',
            name='media_path',
        ),
        migrations.RemoveField(
            model_name='whatsappsendqueue',
            name='media_filename',
        ),
        migrations.RemoveField(
            model_name='whatsappsendqueue',
            name='media_mime',
        ),
        migrations.RemoveField(
            model_name='whatsappsendqueue',
            name='media_path',
        ),
        migrations.RemoveField(
            model_name='whatsappthread',
            name='last_inbound_at',
        ),
        migrations.RemoveField(
            model_name='whatsappthread',
            name='last_outbound_at',
        ),
        migrations.RemoveField(
            model_name='whatsappthread',
            name='unread_count',
        ),
    ]
